using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace gmc_api.Entities
{
    #region APPurchaseReturnReceipts
    //-----------------------------------------------------------
    //Generated By: GMC Studio
    //Class:APPurchaseReturnReceiptsInfo
    //Created Date:04 Tháng Chín 2012
    //-----------------------------------------------------------
    [Table("APPurchaseReturnReceipts")]
    public class APPurchaseReturnReceiptsInfo:BaseInfo
	{
		public APPurchaseReturnReceiptsInfo()
		{
		}
		#region Variables
		protected int _aPPurchaseReturnReceiptID;
		protected String _aAStatus=DefaultAAStatus;
		protected int _fK_APPurchaseReturnID;
		protected int _fK_ICReceiptID;
		#endregion
		[Key]		
		#region Public properties
		public int APPurchaseReturnReceiptID
		{
			get{return _aPPurchaseReturnReceiptID;}
			set
			{
				if (value != this._aPPurchaseReturnReceiptID)
				{
				_aPPurchaseReturnReceiptID=value;
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				}
			}
		}
		public int FK_APPurchaseReturnID
		{
			get{return _fK_APPurchaseReturnID;}
			set
			{
				if (value != this._fK_APPurchaseReturnID)
				{
				_fK_APPurchaseReturnID=value;
				}
			}
		}
		public int FK_ICReceiptID
		{
			get{return _fK_ICReceiptID;}
			set
			{
				if (value != this._fK_ICReceiptID)
				{
				_fK_ICReceiptID=value;
				}
			}
		}
		#endregion
	}
	#endregion
}