 using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region HREmployeeLRegs
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: HREmployeeLRegsInfo
    //Created Date: Monday, 04 Nov 2024
    //-----------------------------------------------------------
    [Table("HREmployeeLRegs")]
    public class HREmployeeLRegsInfo : BaseInfo
    {
        #region Variables
        protected int _hREmployeeLRegID;
        protected String _aAStatus = DefaultAAStatus;
        protected String _aACreatedUser = String.Empty;
        protected String _aAUpdatedUser = String.Empty;
        protected Nullable<DateTime> _aACreatedDate;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected bool _aASelected = true;
        protected int _fK_HREmployeeID;
        protected decimal _hREmployeeLRegDftDays;
        protected decimal _hREmployeeLRegPreviousDays;
        protected decimal _hREmployeeLRegExpDays;
        protected decimal _hREmployeeLRegTotDays;
        protected decimal _hREmployeeLRegLeaveDays;
        protected decimal _hREmployeeLRegRemainDays;
        protected String _hREmployeeLRegDesc = String.Empty;
        protected decimal _hREmployeeLRegAnnualLeaveTot;
        protected decimal _hREmployeeLRegNoxiouDays;
        protected decimal _hREmployeeLRegAnnualLeaveOtherDays;
        protected int _hREmployeeLRegYear;
        protected Nullable<DateTime> _hREmployeeLRegDateCal;
        protected decimal _hREmployeeLRegPreviousDayUsed;

        #endregion
        #region Public properties
        [Key]
        public int HREmployeeLRegID
        {
            get { return _hREmployeeLRegID; }
            set
            {
                if (value != this._hREmployeeLRegID)
                {
                    _hREmployeeLRegID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal HREmployeeLRegDftDays
        {
            get { return _hREmployeeLRegDftDays; }
            set
            {
                if (value != this._hREmployeeLRegDftDays)
                {
                    _hREmployeeLRegDftDays = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal HREmployeeLRegPreviousDays
        {
            get { return _hREmployeeLRegPreviousDays; }
            set
            {
                if (value != this._hREmployeeLRegPreviousDays)
                {
                    _hREmployeeLRegPreviousDays = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal HREmployeeLRegExpDays
        {
            get { return _hREmployeeLRegExpDays; }
            set
            {
                if (value != this._hREmployeeLRegExpDays)
                {
                    _hREmployeeLRegExpDays = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal HREmployeeLRegTotDays
        {
            get { return _hREmployeeLRegTotDays; }
            set
            {
                if (value != this._hREmployeeLRegTotDays)
                {
                    _hREmployeeLRegTotDays = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal HREmployeeLRegLeaveDays
        {
            get { return _hREmployeeLRegLeaveDays; }
            set
            {
                if (value != this._hREmployeeLRegLeaveDays)
                {
                    _hREmployeeLRegLeaveDays = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal HREmployeeLRegRemainDays
        {
            get { return _hREmployeeLRegRemainDays; }
            set
            {
                if (value != this._hREmployeeLRegRemainDays)
                {
                    _hREmployeeLRegRemainDays = value;
                }
            }
        }
        public String HREmployeeLRegDesc
        {
            get { return _hREmployeeLRegDesc; }
            set
            {
                if (value != this._hREmployeeLRegDesc)
                {
                    _hREmployeeLRegDesc = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal HREmployeeLRegAnnualLeaveTot
        {
            get { return _hREmployeeLRegAnnualLeaveTot; }
            set
            {
                if (value != this._hREmployeeLRegAnnualLeaveTot)
                {
                    _hREmployeeLRegAnnualLeaveTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal HREmployeeLRegNoxiouDays
        {
            get { return _hREmployeeLRegNoxiouDays; }
            set
            {
                if (value != this._hREmployeeLRegNoxiouDays)
                {
                    _hREmployeeLRegNoxiouDays = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal HREmployeeLRegAnnualLeaveOtherDays
        {
            get { return _hREmployeeLRegAnnualLeaveOtherDays; }
            set
            {
                if (value != this._hREmployeeLRegAnnualLeaveOtherDays)
                {
                    _hREmployeeLRegAnnualLeaveOtherDays = value;
                }
            }
        }
        public int HREmployeeLRegYear
        {
            get { return _hREmployeeLRegYear; }
            set
            {
                if (value != this._hREmployeeLRegYear)
                {
                    _hREmployeeLRegYear = value;
                }
            }
        }
        public Nullable<DateTime> HREmployeeLRegDateCal
        {
            get { return _hREmployeeLRegDateCal; }
            set
            {
                if (value != this._hREmployeeLRegDateCal)
                {
                    _hREmployeeLRegDateCal = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal HREmployeeLRegPreviousDayUsed
        {
            get { return _hREmployeeLRegPreviousDayUsed; }
            set
            {
                if (value != this._hREmployeeLRegPreviousDayUsed)
                {
                    _hREmployeeLRegPreviousDayUsed = value;
                }
            }
        }

        #endregion
    }
    #endregion
}