 using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region ICProductionUOMs
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: ICProductionUOMsInfo
    //Created Date: Tuesday, 26 Nov 2024
    //-----------------------------------------------------------
    [Table("ICProductionUOMs")]
    public class ICProductionUOMsInfo : BaseInfo
    {
        #region Variables
        protected int _iCProductionUOMID;
        protected String _aACreatedUser = String.Empty;
        protected Nullable<DateTime> _aACreatedDate;
        protected String _aAUpdatedUser = String.Empty;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _aAStatus = DefaultAAStatus;
        protected String _iCProductionUOMNo = String.Empty;
        protected String _iCProductionUOMName = String.Empty;
        protected int _fK_ICProductID;
        protected String _iCProductionUOMDesc = String.Empty;
        protected decimal _iCProductionUOMFactor;
        protected bool _iCProductionUOMIsStockUnit = true;
        protected String _iCProductionUOMMethodCombo = String.Empty;
        protected int _fK_ICUOMID;
        protected int _fK_ICUOMCalculatorID;
        protected int _fK_PPPhaseCfgID;
        protected decimal _iCProductionUOMLossPct;
        protected decimal _iCProductionUOMSetupQty;
        protected int _fK_PPLossCfgID;
        protected decimal _iCProductionUOMIvityQty;
        protected decimal _iCProductionUOMTimeChangePhase;

        #endregion
        #region Public properties
        [Key]
        public int ICProductionUOMID
        {
            get { return _iCProductionUOMID; }
            set
            {
                if (value != this._iCProductionUOMID)
                {
                    _iCProductionUOMID = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public String ICProductionUOMNo
        {
            get { return _iCProductionUOMNo; }
            set
            {
                if (value != this._iCProductionUOMNo)
                {
                    _iCProductionUOMNo = value;
                }
            }
        }
        public String ICProductionUOMName
        {
            get { return _iCProductionUOMName; }
            set
            {
                if (value != this._iCProductionUOMName)
                {
                    _iCProductionUOMName = value;
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                }
            }
        }
        public String ICProductionUOMDesc
        {
            get { return _iCProductionUOMDesc; }
            set
            {
                if (value != this._iCProductionUOMDesc)
                {
                    _iCProductionUOMDesc = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal ICProductionUOMFactor
        {
            get { return _iCProductionUOMFactor; }
            set
            {
                if (value != this._iCProductionUOMFactor)
                {
                    _iCProductionUOMFactor = value;
                }
            }
        }
        public bool ICProductionUOMIsStockUnit
        {
            get { return _iCProductionUOMIsStockUnit; }
            set
            {
                if (value != this._iCProductionUOMIsStockUnit)
                {
                    _iCProductionUOMIsStockUnit = value;
                }
            }
        }
        public String ICProductionUOMMethodCombo
        {
            get { return _iCProductionUOMMethodCombo; }
            set
            {
                if (value != this._iCProductionUOMMethodCombo)
                {
                    _iCProductionUOMMethodCombo = value;
                }
            }
        }
        public int FK_ICUOMID
        {
            get { return _fK_ICUOMID; }
            set
            {
                if (value != this._fK_ICUOMID)
                {
                    _fK_ICUOMID = value;
                }
            }
        }
        public int FK_ICUOMCalculatorID
        {
            get { return _fK_ICUOMCalculatorID; }
            set
            {
                if (value != this._fK_ICUOMCalculatorID)
                {
                    _fK_ICUOMCalculatorID = value;
                }
            }
        }
        public int FK_PPPhaseCfgID
        {
            get { return _fK_PPPhaseCfgID; }
            set
            {
                if (value != this._fK_PPPhaseCfgID)
                {
                    _fK_PPPhaseCfgID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal ICProductionUOMLossPct
        {
            get { return _iCProductionUOMLossPct; }
            set
            {
                if (value != this._iCProductionUOMLossPct)
                {
                    _iCProductionUOMLossPct = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal ICProductionUOMSetupQty
        {
            get { return _iCProductionUOMSetupQty; }
            set
            {
                if (value != this._iCProductionUOMSetupQty)
                {
                    _iCProductionUOMSetupQty = value;
                }
            }
        }
        public int FK_PPLossCfgID
        {
            get { return _fK_PPLossCfgID; }
            set
            {
                if (value != this._fK_PPLossCfgID)
                {
                    _fK_PPLossCfgID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal ICProductionUOMIvityQty
        {
            get { return _iCProductionUOMIvityQty; }
            set
            {
                if (value != this._iCProductionUOMIvityQty)
                {
                    _iCProductionUOMIvityQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal ICProductionUOMTimeChangePhase
        {
            get { return _iCProductionUOMTimeChangePhase; }
            set
            {
                if (value != this._iCProductionUOMTimeChangePhase)
                {
                    _iCProductionUOMTimeChangePhase = value;
                }
            }
        }

        #endregion
    }
    #endregion
}