using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region APApprovedPriceCriterias
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: APApprovedPriceCriteriasInfo
    //Created Date: Wednesday, 27 Nov 2024
    //-----------------------------------------------------------
    [Table("APApprovedPriceCriterias")]
    public class APApprovedPriceCriteriasInfo : BaseInfo
    {
        #region Variables
        protected int _aPApprovedPriceCriteriaID;
        protected String _aAStatus = DefaultAAStatus;
        protected String _aACreatedUser = String.Empty;
        protected String _aAUpdatedUser = String.Empty;
        protected Nullable<DateTime> _aACreatedDate;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected bool _aASelected = true;
        protected String _aPApprovedPriceCriteriaDesc = String.Empty;
        protected int _fK_APApprovedPriceID;
        protected int _fK_APCriteriaID;
        protected int _fK_APSupplierID;

        #endregion
        #region Public properties
        [Key]
        public int APApprovedPriceCriteriaID
        {
            get { return _aPApprovedPriceCriteriaID; }
            set
            {
                if (value != this._aPApprovedPriceCriteriaID)
                {
                    _aPApprovedPriceCriteriaID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public String APApprovedPriceCriteriaDesc
        {
            get { return _aPApprovedPriceCriteriaDesc; }
            set
            {
                if (value != this._aPApprovedPriceCriteriaDesc)
                {
                    _aPApprovedPriceCriteriaDesc = value;
                }
            }
        }
        public int FK_APApprovedPriceID
        {
            get { return _fK_APApprovedPriceID; }
            set
            {
                if (value != this._fK_APApprovedPriceID)
                {
                    _fK_APApprovedPriceID = value;
                }
            }
        }
        public int FK_APCriteriaID
        {
            get { return _fK_APCriteriaID; }
            set
            {
                if (value != this._fK_APCriteriaID)
                {
                    _fK_APCriteriaID = value;
                }
            }
        }
        public int FK_APSupplierID
        {
            get { return _fK_APSupplierID; }
            set
            {
                if (value != this._fK_APSupplierID)
                {
                    _fK_APSupplierID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}