using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region APRFQItems
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: APRFQItemsInfo
    //Created Date: Thursday, 28 Nov 2024
    //-----------------------------------------------------------
    [Table("APRFQItems")]
    public class APRFQItemsInfo : BaseInfo
    {
        #region Variables
        protected int _aPRFQItemID;
        protected String _aAStatus = DefaultAAStatus;
        protected bool _aASelected = true;
        protected String _aPRFQItemStatus = DefaultStatus;
        protected int _fK_APRFQID;
        protected int _fK_ICProductID;
        protected int _fK_ICProductTypeID;
        protected int _fK_ICStockID;
        protected int _fK_ICUOMID;
        protected String _aPRFQItemDesc = String.Empty;
        protected decimal _aPRFQItemUnitPrice;
        protected decimal _aPRFQItemUnitCost;
        protected decimal _aPRFQItemDisc;
        protected decimal _aPRFQItemTxPct;
        protected decimal _aPRFQItemRQty;
        protected decimal _aPRFQItemQty;
        protected decimal _aPRFQItemPrice;
        protected String _aPRFQItemComment = String.Empty;
        protected decimal _aPRFQItemTxAmt;
        protected decimal _aPRFQItemDiscAmt;
        protected decimal _aPRFQItemDiscPct;
        protected decimal _aPRFQItemNetAmt;
        protected decimal _aPRFQItemAmtTot;
        protected decimal _aPRFQItemCostTot;
        protected decimal _aPRFQItemFUnitPrice;
        protected decimal _aPRFQItemFPrice;
        protected decimal _aPRFQItemFTxAmt;
        protected decimal _aPRFQItemFNetAmt;
        protected decimal _aPRFQItemFAmtTot;
        protected decimal _aPRFQItemFImpTxAmt;
        protected decimal _aPRFQItemFDiscAmt;
        protected Nullable<DateTime> _aPRFQItemArrivalDate;
        protected int _fK_APPRItemID;
        protected decimal _aPRFQItemFact;
        protected String _aPRFQItemOrigin = String.Empty;
        protected String _aPRFQItemProductNo = String.Empty;
        protected String _aPRFQItemProductName = String.Empty;
        protected decimal _aPRFQItemExcQty;
        protected decimal _aPRFQItemOrgQty;
        protected int _fK_ICOrgUOMID;
        protected decimal _aPRFQItemStkQty;
        protected int _fK_ICStkUOMID;
        protected int _fK_APPriceListDetailID;
        protected decimal _aPRFQItemAdjStkQty;
        protected String _aPPRItemLine = String.Empty;
        protected String _aPRFQItemManufacturer = String.Empty;
        protected int _fK_TXTaxCodeID;

        #endregion
        #region Public properties
        [Key]
        public int APRFQItemID
        {
            get { return _aPRFQItemID; }
            set
            {
                if (value != this._aPRFQItemID)
                {
                    _aPRFQItemID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public String APRFQItemStatus
        {
            get { return _aPRFQItemStatus; }
            set
            {
                if (value != this._aPRFQItemStatus)
                {
                    _aPRFQItemStatus = value;
                }
            }
        }
        public int FK_APRFQID
        {
            get { return _fK_APRFQID; }
            set
            {
                if (value != this._fK_APRFQID)
                {
                    _fK_APRFQID = value;
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                }
            }
        }
        public int FK_ICProductTypeID
        {
            get { return _fK_ICProductTypeID; }
            set
            {
                if (value != this._fK_ICProductTypeID)
                {
                    _fK_ICProductTypeID = value;
                }
            }
        }
        public int FK_ICStockID
        {
            get { return _fK_ICStockID; }
            set
            {
                if (value != this._fK_ICStockID)
                {
                    _fK_ICStockID = value;
                }
            }
        }
        public int FK_ICUOMID
        {
            get { return _fK_ICUOMID; }
            set
            {
                if (value != this._fK_ICUOMID)
                {
                    _fK_ICUOMID = value;
                }
            }
        }
        public String APRFQItemDesc
        {
            get { return _aPRFQItemDesc; }
            set
            {
                if (value != this._aPRFQItemDesc)
                {
                    _aPRFQItemDesc = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemUnitPrice
        {
            get { return _aPRFQItemUnitPrice; }
            set
            {
                if (value != this._aPRFQItemUnitPrice)
                {
                    _aPRFQItemUnitPrice = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemUnitCost
        {
            get { return _aPRFQItemUnitCost; }
            set
            {
                if (value != this._aPRFQItemUnitCost)
                {
                    _aPRFQItemUnitCost = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemDisc
        {
            get { return _aPRFQItemDisc; }
            set
            {
                if (value != this._aPRFQItemDisc)
                {
                    _aPRFQItemDisc = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemTxPct
        {
            get { return _aPRFQItemTxPct; }
            set
            {
                if (value != this._aPRFQItemTxPct)
                {
                    _aPRFQItemTxPct = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemRQty
        {
            get { return _aPRFQItemRQty; }
            set
            {
                if (value != this._aPRFQItemRQty)
                {
                    _aPRFQItemRQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemQty
        {
            get { return _aPRFQItemQty; }
            set
            {
                if (value != this._aPRFQItemQty)
                {
                    _aPRFQItemQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemPrice
        {
            get { return _aPRFQItemPrice; }
            set
            {
                if (value != this._aPRFQItemPrice)
                {
                    _aPRFQItemPrice = value;
                }
            }
        }
        public String APRFQItemComment
        {
            get { return _aPRFQItemComment; }
            set
            {
                if (value != this._aPRFQItemComment)
                {
                    _aPRFQItemComment = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemTxAmt
        {
            get { return _aPRFQItemTxAmt; }
            set
            {
                if (value != this._aPRFQItemTxAmt)
                {
                    _aPRFQItemTxAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemDiscAmt
        {
            get { return _aPRFQItemDiscAmt; }
            set
            {
                if (value != this._aPRFQItemDiscAmt)
                {
                    _aPRFQItemDiscAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemDiscPct
        {
            get { return _aPRFQItemDiscPct; }
            set
            {
                if (value != this._aPRFQItemDiscPct)
                {
                    _aPRFQItemDiscPct = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemNetAmt
        {
            get { return _aPRFQItemNetAmt; }
            set
            {
                if (value != this._aPRFQItemNetAmt)
                {
                    _aPRFQItemNetAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemAmtTot
        {
            get { return _aPRFQItemAmtTot; }
            set
            {
                if (value != this._aPRFQItemAmtTot)
                {
                    _aPRFQItemAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemCostTot
        {
            get { return _aPRFQItemCostTot; }
            set
            {
                if (value != this._aPRFQItemCostTot)
                {
                    _aPRFQItemCostTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemFUnitPrice
        {
            get { return _aPRFQItemFUnitPrice; }
            set
            {
                if (value != this._aPRFQItemFUnitPrice)
                {
                    _aPRFQItemFUnitPrice = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemFPrice
        {
            get { return _aPRFQItemFPrice; }
            set
            {
                if (value != this._aPRFQItemFPrice)
                {
                    _aPRFQItemFPrice = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemFTxAmt
        {
            get { return _aPRFQItemFTxAmt; }
            set
            {
                if (value != this._aPRFQItemFTxAmt)
                {
                    _aPRFQItemFTxAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemFNetAmt
        {
            get { return _aPRFQItemFNetAmt; }
            set
            {
                if (value != this._aPRFQItemFNetAmt)
                {
                    _aPRFQItemFNetAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemFAmtTot
        {
            get { return _aPRFQItemFAmtTot; }
            set
            {
                if (value != this._aPRFQItemFAmtTot)
                {
                    _aPRFQItemFAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemFImpTxAmt
        {
            get { return _aPRFQItemFImpTxAmt; }
            set
            {
                if (value != this._aPRFQItemFImpTxAmt)
                {
                    _aPRFQItemFImpTxAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemFDiscAmt
        {
            get { return _aPRFQItemFDiscAmt; }
            set
            {
                if (value != this._aPRFQItemFDiscAmt)
                {
                    _aPRFQItemFDiscAmt = value;
                }
            }
        }
        public Nullable<DateTime> APRFQItemArrivalDate
        {
            get { return _aPRFQItemArrivalDate; }
            set
            {
                if (value != this._aPRFQItemArrivalDate)
                {
                    _aPRFQItemArrivalDate = value;
                }
            }
        }
        public int FK_APPRItemID
        {
            get { return _fK_APPRItemID; }
            set
            {
                if (value != this._fK_APPRItemID)
                {
                    _fK_APPRItemID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemFact
        {
            get { return _aPRFQItemFact; }
            set
            {
                if (value != this._aPRFQItemFact)
                {
                    _aPRFQItemFact = value;
                }
            }
        }
        public String APRFQItemOrigin
        {
            get { return _aPRFQItemOrigin; }
            set
            {
                if (value != this._aPRFQItemOrigin)
                {
                    _aPRFQItemOrigin = value;
                }
            }
        }
        public String APRFQItemProductNo
        {
            get { return _aPRFQItemProductNo; }
            set
            {
                if (value != this._aPRFQItemProductNo)
                {
                    _aPRFQItemProductNo = value;
                }
            }
        }
        public String APRFQItemProductName
        {
            get { return _aPRFQItemProductName; }
            set
            {
                if (value != this._aPRFQItemProductName)
                {
                    _aPRFQItemProductName = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemExcQty
        {
            get { return _aPRFQItemExcQty; }
            set
            {
                if (value != this._aPRFQItemExcQty)
                {
                    _aPRFQItemExcQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemOrgQty
        {
            get { return _aPRFQItemOrgQty; }
            set
            {
                if (value != this._aPRFQItemOrgQty)
                {
                    _aPRFQItemOrgQty = value;
                }
            }
        }
        public int FK_ICOrgUOMID
        {
            get { return _fK_ICOrgUOMID; }
            set
            {
                if (value != this._fK_ICOrgUOMID)
                {
                    _fK_ICOrgUOMID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemStkQty
        {
            get { return _aPRFQItemStkQty; }
            set
            {
                if (value != this._aPRFQItemStkQty)
                {
                    _aPRFQItemStkQty = value;
                }
            }
        }
        public int FK_ICStkUOMID
        {
            get { return _fK_ICStkUOMID; }
            set
            {
                if (value != this._fK_ICStkUOMID)
                {
                    _fK_ICStkUOMID = value;
                }
            }
        }
        public int FK_APPriceListDetailID
        {
            get { return _fK_APPriceListDetailID; }
            set
            {
                if (value != this._fK_APPriceListDetailID)
                {
                    _fK_APPriceListDetailID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal APRFQItemAdjStkQty
        {
            get { return _aPRFQItemAdjStkQty; }
            set
            {
                if (value != this._aPRFQItemAdjStkQty)
                {
                    _aPRFQItemAdjStkQty = value;
                }
            }
        }
        public String APPRItemLine
        {
            get { return _aPPRItemLine; }
            set
            {
                if (value != this._aPPRItemLine)
                {
                    _aPPRItemLine = value;
                }
            }
        }
        public String APRFQItemManufacturer
        {
            get { return _aPRFQItemManufacturer; }
            set
            {
                if (value != this._aPRFQItemManufacturer)
                {
                    _aPRFQItemManufacturer = value;
                }
            }
        }
        public int FK_TXTaxCodeID
        {
            get { return _fK_TXTaxCodeID; }
            set
            {
                if (value != this._fK_TXTaxCodeID)
                {
                    _fK_TXTaxCodeID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}