 using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region APSupplierCriterias
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: APSupplierCriteriasInfo
    //Created Date: Friday, 08 Nov 2024
    //-----------------------------------------------------------
    [Table("APSupplierCriterias")]
    public class APSupplierCriteriasInfo : BaseInfo
    {
        #region Variables
        protected int _aPSupplierCriteriaID;
        protected String _aAStatus = DefaultAAStatus;
        protected String _aACreatedUser = String.Empty;
        protected String _aAUpdatedUser = String.Empty;
        protected Nullable<DateTime> _aACreatedDate;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected bool _aASelected = true;
        protected String _aPSupplierCriteriaDesc = String.Empty;
        protected String _aPSupplierCriteriaInfo = String.Empty;
        protected int _fK_APSupplierID;
        protected int _fK_APCriteriaID;

        #endregion
        #region Public properties
        [Key]
        public int APSupplierCriteriaID
        {
            get { return _aPSupplierCriteriaID; }
            set
            {
                if (value != this._aPSupplierCriteriaID)
                {
                    _aPSupplierCriteriaID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public String APSupplierCriteriaDesc
        {
            get { return _aPSupplierCriteriaDesc; }
            set
            {
                if (value != this._aPSupplierCriteriaDesc)
                {
                    _aPSupplierCriteriaDesc = value;
                }
            }
        }
        public String APSupplierCriteriaInfo
        {
            get { return _aPSupplierCriteriaInfo; }
            set
            {
                if (value != this._aPSupplierCriteriaInfo)
                {
                    _aPSupplierCriteriaInfo = value;
                }
            }
        }
        public int FK_APSupplierID
        {
            get { return _fK_APSupplierID; }
            set
            {
                if (value != this._fK_APSupplierID)
                {
                    _fK_APSupplierID = value;
                }
            }
        }
        public int FK_APCriteriaID
        {
            get { return _fK_APCriteriaID; }
            set
            {
                if (value != this._fK_APCriteriaID)
                {
                    _fK_APCriteriaID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}