using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region ICShipmentItemPurchaseExchangeItems
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: ICShipmentItemPurchaseExchangeItemsInfo
    //Created Date: Thursday, 06 Feb 2025
    //-----------------------------------------------------------
    [Table("ICShipmentItemPurchaseExchangeItems")]
    public class ICShipmentItemPurchaseExchangeItemsInfo : BaseInfo
    {
        #region Variables
        protected int _iCShipmentItemPurchaseExchangeItemID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ICShipmentItemID;
        protected int _fK_APPurchaseExchangeItemID;

        #endregion
        #region Public properties
        [Key]
        public int ICShipmentItemPurchaseExchangeItemID
        {
            get { return _iCShipmentItemPurchaseExchangeItemID; }
            set
            {
                if (value != this._iCShipmentItemPurchaseExchangeItemID)
                {
                    _iCShipmentItemPurchaseExchangeItemID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public int FK_ICShipmentItemID
        {
            get { return _fK_ICShipmentItemID; }
            set
            {
                if (value != this._fK_ICShipmentItemID)
                {
                    _fK_ICShipmentItemID = value;
                }
            }
        }
        public int FK_APPurchaseExchangeItemID
        {
            get { return _fK_APPurchaseExchangeItemID; }
            set
            {
                if (value != this._fK_APPurchaseExchangeItemID)
                {
                    _fK_APPurchaseExchangeItemID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}