using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region ICShipmentPurchaseExchanges
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: ICShipmentPurchaseExchangesInfo
    //Created Date: Thursday, 06 Feb 2025
    //-----------------------------------------------------------
    [Table("ICShipmentPurchaseExchanges")]
    public class ICShipmentPurchaseExchangesInfo : BaseInfo
    {
        #region Variables
        protected int _iCShipmentPurchaseExchangeID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ICShipmentID;
        protected int _fK_APPurchaseExchangeID;

        #endregion
        #region Public properties
        [Key]
        public int ICShipmentPurchaseExchangeID
        {
            get { return _iCShipmentPurchaseExchangeID; }
            set
            {
                if (value != this._iCShipmentPurchaseExchangeID)
                {
                    _iCShipmentPurchaseExchangeID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public int FK_ICShipmentID
        {
            get { return _fK_ICShipmentID; }
            set
            {
                if (value != this._fK_ICShipmentID)
                {
                    _fK_ICShipmentID = value;
                }
            }
        }
        public int FK_APPurchaseExchangeID
        {
            get { return _fK_APPurchaseExchangeID; }
            set
            {
                if (value != this._fK_APPurchaseExchangeID)
                {
                    _fK_APPurchaseExchangeID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}