using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region ICShipmentItemSaleReturnItems
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: ICShipmentItemSaleReturnItemsInfo
    //Created Date: Monday, 16 Dec 2024
    //-----------------------------------------------------------
    [Table("ICShipmentItemSaleReturnItems")]
    public class ICShipmentItemSaleReturnItemsInfo : BaseInfo
    {
        #region Variables
        protected int _iCShipmentItemSaleReturnItemID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ICShipmentItemID;
        protected int _fK_ARSaleReturnItemID;

        #endregion
        #region Public properties
        [Key]
        public int ICShipmentItemSaleReturnItemID
        {
            get { return _iCShipmentItemSaleReturnItemID; }
            set
            {
                if (value != this._iCShipmentItemSaleReturnItemID)
                {
                    _iCShipmentItemSaleReturnItemID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public int FK_ICShipmentItemID
        {
            get { return _fK_ICShipmentItemID; }
            set
            {
                if (value != this._fK_ICShipmentItemID)
                {
                    _fK_ICShipmentItemID = value;
                }
            }
        }
        public int FK_ARSaleReturnItemID
        {
            get { return _fK_ARSaleReturnItemID; }
            set
            {
                if (value != this._fK_ARSaleReturnItemID)
                {
                    _fK_ARSaleReturnItemID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}