using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region ACCostSimulationItemColumns
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: ACCostSimulationItemColumnsInfo
    //Created Date: Wednesday, 17 Sep 2025
    //-----------------------------------------------------------
    [Table("ACCostSimulationItemColumns")]
    public class ACCostSimulationItemColumnsInfo : BaseInfo
    {
        #region Variables
        protected int _aCCostSimulationItemColumnID;
        protected String _aACreatedUser = String.Empty;
        protected String _aAUpdatedUser = String.Empty;
        protected Nullable<DateTime> _aACreatedDate;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _aAStatus = DefaultAAStatus;
        protected bool _aASelected = true;
        protected int _fK_ACCostSimulationID;
        protected int _fK_ACCostSimulationItemID;
        protected int _fK_ACCostSimulationMethodItemID;
        protected String _aCCostSimulationItemColumnParamType = String.Empty;
        protected String _aCCostSimulationItemColumnParamValue = String.Empty;
        protected String _aCCostSimulationItemColumnPublicCombo = String.Empty;
        protected int _aCCostSimulationItemColumnOrder;
        protected String _aCCostSimulationItemColumnColMap = String.Empty;
        protected String _aCCostSimulationItemColumnColDisplay = String.Empty;
        protected String _aCCostSimulationItemColumnFunction = String.Empty;
        protected int _fK_ACCostSimulationFuncID;
        protected int _fK_ACCostSimulationMethodItemParamID;
        protected int _fK_ACCostSimulationFactorID;
        protected String _aCCostSimulationObjectTypeCombo = String.Empty;
        protected int _fK_ACCostSimulationMethodCatalogID;

        #endregion
        #region Public properties
        [Key]
        public int ACCostSimulationItemColumnID
        {
            get { return _aCCostSimulationItemColumnID; }
            set
            {
                if (value != this._aCCostSimulationItemColumnID)
                {
                    _aCCostSimulationItemColumnID = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public int FK_ACCostSimulationID
        {
            get { return _fK_ACCostSimulationID; }
            set
            {
                if (value != this._fK_ACCostSimulationID)
                {
                    _fK_ACCostSimulationID = value;
                }
            }
        }
        public int FK_ACCostSimulationItemID
        {
            get { return _fK_ACCostSimulationItemID; }
            set
            {
                if (value != this._fK_ACCostSimulationItemID)
                {
                    _fK_ACCostSimulationItemID = value;
                }
            }
        }
        public int FK_ACCostSimulationMethodItemID
        {
            get { return _fK_ACCostSimulationMethodItemID; }
            set
            {
                if (value != this._fK_ACCostSimulationMethodItemID)
                {
                    _fK_ACCostSimulationMethodItemID = value;
                }
            }
        }
        public String ACCostSimulationItemColumnParamType
        {
            get { return _aCCostSimulationItemColumnParamType; }
            set
            {
                if (value != this._aCCostSimulationItemColumnParamType)
                {
                    _aCCostSimulationItemColumnParamType = value;
                }
            }
        }
        public String ACCostSimulationItemColumnParamValue
        {
            get { return _aCCostSimulationItemColumnParamValue; }
            set
            {
                if (value != this._aCCostSimulationItemColumnParamValue)
                {
                    _aCCostSimulationItemColumnParamValue = value;
                }
            }
        }
        public String ACCostSimulationItemColumnPublicCombo
        {
            get { return _aCCostSimulationItemColumnPublicCombo; }
            set
            {
                if (value != this._aCCostSimulationItemColumnPublicCombo)
                {
                    _aCCostSimulationItemColumnPublicCombo = value;
                }
            }
        }
        public int ACCostSimulationItemColumnOrder
        {
            get { return _aCCostSimulationItemColumnOrder; }
            set
            {
                if (value != this._aCCostSimulationItemColumnOrder)
                {
                    _aCCostSimulationItemColumnOrder = value;
                }
            }
        }
        public String ACCostSimulationItemColumnColMap
        {
            get { return _aCCostSimulationItemColumnColMap; }
            set
            {
                if (value != this._aCCostSimulationItemColumnColMap)
                {
                    _aCCostSimulationItemColumnColMap = value;
                }
            }
        }
        public String ACCostSimulationItemColumnColDisplay
        {
            get { return _aCCostSimulationItemColumnColDisplay; }
            set
            {
                if (value != this._aCCostSimulationItemColumnColDisplay)
                {
                    _aCCostSimulationItemColumnColDisplay = value;
                }
            }
        }
        public String ACCostSimulationItemColumnFunction
        {
            get { return _aCCostSimulationItemColumnFunction; }
            set
            {
                if (value != this._aCCostSimulationItemColumnFunction)
                {
                    _aCCostSimulationItemColumnFunction = value;
                }
            }
        }
        public int FK_ACCostSimulationFuncID
        {
            get { return _fK_ACCostSimulationFuncID; }
            set
            {
                if (value != this._fK_ACCostSimulationFuncID)
                {
                    _fK_ACCostSimulationFuncID = value;
                }
            }
        }
        public int FK_ACCostSimulationMethodItemParamID
        {
            get { return _fK_ACCostSimulationMethodItemParamID; }
            set
            {
                if (value != this._fK_ACCostSimulationMethodItemParamID)
                {
                    _fK_ACCostSimulationMethodItemParamID = value;
                }
            }
        }
        public int FK_ACCostSimulationFactorID
        {
            get { return _fK_ACCostSimulationFactorID; }
            set
            {
                if (value != this._fK_ACCostSimulationFactorID)
                {
                    _fK_ACCostSimulationFactorID = value;
                }
            }
        }
        public String ACCostSimulationObjectTypeCombo
        {
            get { return _aCCostSimulationObjectTypeCombo; }
            set
            {
                if (value != this._aCCostSimulationObjectTypeCombo)
                {
                    _aCCostSimulationObjectTypeCombo = value;
                }
            }
        }
        public int FK_ACCostSimulationMethodCatalogID
        {
            get { return _fK_ACCostSimulationMethodCatalogID; }
            set
            {
                if (value != this._fK_ACCostSimulationMethodCatalogID)
                {
                    _fK_ACCostSimulationMethodCatalogID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}