using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region ACCostSimulationFuncs
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: ACCostSimulationFuncsInfo
    //Created Date: Thursday, 09 Oct 2025
    //-----------------------------------------------------------
    [Table("ACCostSimulationFuncs")]
    public class ACCostSimulationFuncsInfo : BaseInfo
    {
        #region Variables
        protected int _aCCostSimulationFuncID;
        protected String _aCCostSimulationFuncNo = String.Empty;
        protected String _aCCostSimulationFuncName = String.Empty;
        protected Nullable<DateTime> _aCCostSimulationFuncDate;
        protected String _aCCostSimulationFuncDesc = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected Nullable<DateTime> _aACreatedDate;
        protected String _aACreatedUser = String.Empty;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aCCostSimulationFuncQuery = String.Empty;

        #endregion
        #region Public properties
        [Key]
        public int ACCostSimulationFuncID
        {
            get { return _aCCostSimulationFuncID; }
            set
            {
                if (value != this._aCCostSimulationFuncID)
                {
                    _aCCostSimulationFuncID = value;
                }
            }
        }
        public String ACCostSimulationFuncNo
        {
            get { return _aCCostSimulationFuncNo; }
            set
            {
                if (value != this._aCCostSimulationFuncNo)
                {
                    _aCCostSimulationFuncNo = value;
                }
            }
        }
        public String ACCostSimulationFuncName
        {
            get { return _aCCostSimulationFuncName; }
            set
            {
                if (value != this._aCCostSimulationFuncName)
                {
                    _aCCostSimulationFuncName = value;
                }
            }
        }
        public Nullable<DateTime> ACCostSimulationFuncDate
        {
            get { return _aCCostSimulationFuncDate; }
            set
            {
                if (value != this._aCCostSimulationFuncDate)
                {
                    _aCCostSimulationFuncDate = value;
                }
            }
        }
        public String ACCostSimulationFuncDesc
        {
            get { return _aCCostSimulationFuncDesc; }
            set
            {
                if (value != this._aCCostSimulationFuncDesc)
                {
                    _aCCostSimulationFuncDesc = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public String ACCostSimulationFuncQuery
        {
            get { return _aCCostSimulationFuncQuery; }
            set
            {
                if (value != this._aCCostSimulationFuncQuery)
                {
                    _aCCostSimulationFuncQuery = value;
                }
            }
        }

        #endregion
    }
    #endregion
}