using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region ACCostSimulationFactors
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: ACCostSimulationFactorsInfo
    //Created Date: Wednesday, 08 Oct 2025
    //-----------------------------------------------------------
    [Table("ACCostSimulationFactors")]
    public class ACCostSimulationFactorsInfo : BaseInfo
    {
        #region Variables
        protected int _aCCostSimulationFactorID;
        protected Nullable<DateTime> _aACreatedDate;
        protected String _aACreatedUser = String.Empty;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected bool _aASelected = true;
        protected String _aCCostSimulationFactorNo = String.Empty;
        protected String _aCCostSimulationFactorName = String.Empty;
        protected Nullable<DateTime> _aCCostSimulationFactorDate;
        protected String _aCCostSimulationFactorDesc = String.Empty;
        protected int _fK_ACCostSimulationFactorParentID;
        protected bool _aCCostSimulationFactorActiveCheck = true;
        protected int _fK_ACProductionCostingFactorID;
        protected String _aCCostSimulationFactorRegEx = String.Empty;
        protected int _fK_ARClassifyAccountID;
        protected int _fK_ARClassifyTypeID;
        protected int _fK_ARClassifyGroupID;

        #endregion
        #region Public properties
        [Key]
        public int ACCostSimulationFactorID
        {
            get { return _aCCostSimulationFactorID; }
            set
            {
                if (value != this._aCCostSimulationFactorID)
                {
                    _aCCostSimulationFactorID = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public String ACCostSimulationFactorNo
        {
            get { return _aCCostSimulationFactorNo; }
            set
            {
                if (value != this._aCCostSimulationFactorNo)
                {
                    _aCCostSimulationFactorNo = value;
                }
            }
        }
        public String ACCostSimulationFactorName
        {
            get { return _aCCostSimulationFactorName; }
            set
            {
                if (value != this._aCCostSimulationFactorName)
                {
                    _aCCostSimulationFactorName = value;
                }
            }
        }
        public Nullable<DateTime> ACCostSimulationFactorDate
        {
            get { return _aCCostSimulationFactorDate; }
            set
            {
                if (value != this._aCCostSimulationFactorDate)
                {
                    _aCCostSimulationFactorDate = value;
                }
            }
        }
        public String ACCostSimulationFactorDesc
        {
            get { return _aCCostSimulationFactorDesc; }
            set
            {
                if (value != this._aCCostSimulationFactorDesc)
                {
                    _aCCostSimulationFactorDesc = value;
                }
            }
        }
        public int FK_ACCostSimulationFactorParentID
        {
            get { return _fK_ACCostSimulationFactorParentID; }
            set
            {
                if (value != this._fK_ACCostSimulationFactorParentID)
                {
                    _fK_ACCostSimulationFactorParentID = value;
                }
            }
        }
        public bool ACCostSimulationFactorActiveCheck
        {
            get { return _aCCostSimulationFactorActiveCheck; }
            set
            {
                if (value != this._aCCostSimulationFactorActiveCheck)
                {
                    _aCCostSimulationFactorActiveCheck = value;
                }
            }
        }
        public int FK_ACProductionCostingFactorID
        {
            get { return _fK_ACProductionCostingFactorID; }
            set
            {
                if (value != this._fK_ACProductionCostingFactorID)
                {
                    _fK_ACProductionCostingFactorID = value;
                }
            }
        }
        public String ACCostSimulationFactorRegEx
        {
            get { return _aCCostSimulationFactorRegEx; }
            set
            {
                if (value != this._aCCostSimulationFactorRegEx)
                {
                    _aCCostSimulationFactorRegEx = value;
                }
            }
        }
        public int FK_ARClassifyAccountID
        {
            get { return _fK_ARClassifyAccountID; }
            set
            {
                if (value != this._fK_ARClassifyAccountID)
                {
                    _fK_ARClassifyAccountID = value;
                }
            }
        }
        public int FK_ARClassifyTypeID
        {
            get { return _fK_ARClassifyTypeID; }
            set
            {
                if (value != this._fK_ARClassifyTypeID)
                {
                    _fK_ARClassifyTypeID = value;
                }
            }
        }
        public int FK_ARClassifyGroupID
        {
            get { return _fK_ARClassifyGroupID; }
            set
            {
                if (value != this._fK_ARClassifyGroupID)
                {
                    _fK_ARClassifyGroupID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}