using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace gmc_api.DTO.ROProductionOrdr
{
    public class ROProductionOrdrCreateRequest
    {
        public int ICROID { get; set; }
        public Boolean AASelected { get; set; }
        public int FK_GECurrencyID { get; set; }
        public int FK_ARCustomerID { get; set; }
        public int FK_APSupplierID { get; set; }
        public int FK_GEShpMthID { get; set; }
        public int FK_ARSellerID { get; set; }
        public int FK_ARPriceListID { get; set; }
        public int FK_ICStockID { get; set; }
        public int FK_BRBranchID { get; set; }
        public int FK_LOShpPlanID { get; set; }
        public int FK_LOCarID { get; set; }
        public int FK_LODirectionID { get; set; }
        public decimal ICSellerComAmt { get; set; }
        public decimal ICSellerComPct { get; set; }
        public string ICSalePriceCombo { get; set; }
        public string ICROStatusCombo { get; set; }
        public string ICROPmtTerm { get; set; }
        public decimal ICROPmtDueDays { get; set; }
        public string ICPmtMthCombo { get; set; }
        public string ICRONo { get; set; }
        public string ICROName { get; set; }
        public string ICRODesc { get; set; }
        public Boolean ICROOnHoldCheck { get; set; }
        public string ICROText { get; set; }
        public Nullable<DateTime> ICRODate { get; set; }
        public int ICROFiscPer { get; set; }
        public int ICROFiscYr { get; set; }
        public Nullable<DateTime> ICROShpDate { get; set; }
        public Nullable<DateTime> ICROExpireDate { get; set; }
        public decimal ICRODiscPct { get; set; }
        public decimal ICRODiscAmt { get; set; }
        public string ICRORef { get; set; }
        public string ICROCusRef { get; set; }
        public string ICROComment { get; set; }
        public decimal ICROWeight { get; set; }
        public decimal ICROVol { get; set; }
        public Boolean ICROActive { get; set; }
        public string ICROTxNo { get; set; }
        public decimal ICROExcRate { get; set; }
        public decimal ICROAmt { get; set; }
        public decimal ICROCAmt { get; set; }
        public string ICROSubType { get; set; }
        public string ICROOF01Combo { get; set; }
        public string ICROOF02Combo { get; set; }
        public string ICROOF03Combo { get; set; }
        public string ICROOF04Combo { get; set; }
        public string ICROOF05Combo { get; set; }
        public string ICROOF06Combo { get; set; }
        public string ICROOF07Combo { get; set; }
        public string ICROOF08Combo { get; set; }
        public string ICROOF09Combo { get; set; }
        public string ICROOF10Combo { get; set; }
        public string ICROPrj { get; set; }
        public string ICROCustomerName { get; set; }
        public string ICROCustomerDesc { get; set; }
        public int FK_ARCustomerConBTID { get; set; }
        public string ICROBTConName { get; set; }
        public string ICROBTConFName { get; set; }
        public string ICROBTConLName { get; set; }
        public string ICROBTConTitle { get; set; }
        public string ICROBTConHLet { get; set; }
        public string ICROBTConHMsg { get; set; }
        public string ICROBTConEmail { get; set; }
        public string ICROBTConEmail1 { get; set; }
        public string ICROBTConPhone { get; set; }
        public string ICROBTConCPhone { get; set; }
        public string ICROBTConFax { get; set; }
        public string ICROBTConInfo { get; set; }
        public string ICROBTConDept { get; set; }
        public string ICROBTConRoom { get; set; }
        public string ICROBTAddL1 { get; set; }
        public string ICROBTAddL2 { get; set; }
        public string ICROBTAddL3 { get; set; }
        public string ICROBTAddStr { get; set; }
        public string ICROBTAddCity { get; set; }
        public string ICROBTAddPCode { get; set; }
        public string ICROBTAddStProv { get; set; }
        public string ICROBTAddZCode { get; set; }
        public string ICROBTAddCountry { get; set; }
        public int FK_ARCustomerConCMID { get; set; }
        public string ICROCMConName { get; set; }
        public Nullable<DateTime> ICROCMConBday { get; set; }
        public string ICROCMConFName { get; set; }
        public string ICROCMConLName { get; set; }
        public string ICROCMConTitle { get; set; }
        public string ICROCMConHLet { get; set; }
        public string ICROCMConHMsg { get; set; }
        public string ICROCMConEmail { get; set; }
        public string ICROCMConEmail1 { get; set; }
        public string ICROCMConPhone { get; set; }
        public string ICROCMConCPhone { get; set; }
        public string ICROCMConFax { get; set; }
        public string ICROCMConInfo { get; set; }
        public string ICROCMConDept { get; set; }
        public string ICROCMConRoom { get; set; }
        public string ICROCMAddL1 { get; set; }
        public string ICROCMAddL2 { get; set; }
        public string ICROCMAddL3 { get; set; }
        public string ICROCMAddStr { get; set; }
        public string ICROCMAddCity { get; set; }
        public string ICROCMAddPCode { get; set; }
        public string ICROCMAddStProv { get; set; }
        public string ICROCMAddZCode { get; set; }
        public string ICROCMAddCountry { get; set; }
        public int FK_ARCustomerConSTID { get; set; }
        public string ICROSTConName { get; set; }
        public Nullable<DateTime> ICROSTConBday { get; set; }
        public string ICROSTConFName { get; set; }
        public string ICROSTConLName { get; set; }
        public string ICROSTConTitle { get; set; }
        public string ICROSTConHLet { get; set; }
        public string ICROSTConHMsg { get; set; }
        public string ICROSTConEmail { get; set; }
        public string ICROSTConEmail1 { get; set; }
        public string ICROSTConPhone { get; set; }
        public string ICROSTConCPhone { get; set; }
        public string ICROSTConFax { get; set; }
        public string ICROSTConInfo { get; set; }
        public string ICROSTConDept { get; set; }
        public string ICROSTConRoom { get; set; }
        public string ICROSTAddL1 { get; set; }
        public string ICROSTAddL2 { get; set; }
        public string ICROSTAddL3 { get; set; }
        public string ICROSTAddStr { get; set; }
        public string ICROSTAddCity { get; set; }
        public string ICROSTAddPCode { get; set; }
        public string ICROSTAddStProv { get; set; }
        public string ICROSTAddZCode { get; set; }
        public string ICROSTAddCountry { get; set; }
        public decimal ICROShpAmt { get; set; }
        public decimal ICROItmPriceTot { get; set; }
        public decimal ICROItmDiscAmtTot { get; set; }
        public decimal ICROItmAmtTot { get; set; }
        public decimal ICROTxAmtTot { get; set; }
        public decimal ICRONetAmtTot { get; set; }
        public decimal ICROAmtTot { get; set; }
        public decimal ICROMiscChargeAmt { get; set; }
        public decimal ICROCostTot { get; set; }
        public decimal ICROMargPct { get; set; }
        public string ICROStatus { get; set; }
        public Nullable<DateTime> ICROHoldDate { get; set; }
        public Nullable<DateTime> ICROHoldBy { get; set; }
        public int ICROHoldTot { get; set; }
        public decimal ICROWCapTot { get; set; }
        public decimal ICROVCapTot { get; set; }
        public decimal ICRODistance { get; set; }
        public int FK_PPWOID { get; set; }
        public string AAPostStatus { get; set; }
        public int FK_HRDepartmentID { get; set; }
        public string ICROEquipmentTypeCombo { get; set; }
        public int FK_ICROTypeID { get; set; }
        public int FK_HREmployeeID { get; set; }
        public decimal ICRORAmtTot { get; set; }
        public Boolean ICROAutoCreateWarantyCheck { get; set; }
        public decimal ICROFRAmtTot { get; set; }
        public decimal ICROFAmtTot { get; set; }
        public decimal ICROFImpTxAmtTot { get; set; }
        public decimal ICROFTxAmtTot { get; set; }
        public decimal ICROFItmAmtTot { get; set; }
        public decimal ICROFItmDiscAmtTot { get; set; }
        public decimal ICROFItmPriceTot { get; set; }
        public int FK_PMProjectID { get; set; }
        public string AALastPostNo { get; set; }
        public Nullable<DateTime> AALastPostDate { get; set; }
        public string ICROWarantyStatus { get; set; }
        public string ICROTypeCombo { get; set; }
        public string SaleReturnStatusCombo { get; set; }
        public decimal ICRODiscFAmt { get; set; }
        public decimal ICRODriverPmtAmtTot { get; set; }
        public decimal ICROItmFPriceTot { get; set; }
        public decimal ICROItmDiscFAmtTot { get; set; }
        public decimal ICROItmFAmtTot { get; set; }
        public decimal ICROTxFAmtTot { get; set; }
        public decimal ICRONetFAmtTot { get; set; }
        public decimal ICRORFAmtTot { get; set; }
        public int FK_ARContractID { get; set; }
        public string ICROApprovalStatusCombo { get; set; }
        public string ICROCarNo { get; set; }
        public string ICROContNo { get; set; }
        public string ICROSealNo { get; set; }
        public string ApprovalStatusCombo { get; set; }
        public Nullable<DateTime> ICROTimeIn { get; set; }
        public Nullable<DateTime> ICROTimeOut { get; set; }
        public int FK_ICCarryTypeID { get; set; }
        public int FK_ICCarrierTeamID { get; set; }
        public string ICROInvNo { get; set; }
        public string ICServiceChargeStatusCombo { get; set; }
        public Nullable<DateTime> ICServiceChargeLastdate { get; set; }
        public string ICServiceChargeLastUser { get; set; }
        public string ICROVoucherRefNo { get; set; }
        public string APPurchaseReturnStatusCombo { get; set; }
        public int FK_ARCustomerOwnerID { get; set; }
        public int FK_LOPortPOLID { get; set; }
        public int FK_LOPortPODID { get; set; }
        public Nullable<DateTime> ICROETDDate { get; set; }
        public Nullable<DateTime> ICROETADate { get; set; }
        public Nullable<DateTime> ICROReceivedDate { get; set; }
        public int FK_ARShipperID { get; set; }
        public string ICROShipperTaxNo { get; set; }
        public string ICROShipperAddress { get; set; }
        public int FK_ARConsigneeID { get; set; }
        public string ICROConsigneeTaxNo { get; set; }
        public string ICROConsigneeAddress { get; set; }
        public int FK_LOAgentID { get; set; }
        public string ICROAgentTaxNo { get; set; }
        public string ICROAgentAddress { get; set; }
        public int FK_LOCarrierID { get; set; }
        public string ICROCarrierTaxNo { get; set; }
        public string ICROCarrierAddress { get; set; }
        public string ICROPONo { get; set; }
        public int FK_GLTranCfgID { get; set; }
        public string ICROLPortName { get; set; }
        public string ICRODPortName { get; set; }
        public string ICROConsigneeName { get; set; }
        public string ICROShipperName { get; set; }
        public string ICROAgentName { get; set; }
        public string ICROCarrierName { get; set; }
        public int FK_LOConsigneeID { get; set; }
        public string ICROTransferStatusCombo { get; set; }
        public int FK_APPOID { get; set; }
        public int FK_PPProductionOrdrID { get; set; }
        public string AAModule { get; set; }
        public string ICROSupAdd { get; set; }
        public string ICROOptional01 { get; set; }
        public string ICROOptional02 { get; set; }
        public string ICROOptional03 { get; set; }
        public int FK_ARTradeTermID { get; set; }
        public int FK_GECurrencyExObjID { get; set; }
        public int FK_ARSOID { get; set; }
        public int FK_GEIncoTermID { get; set; }
        public string ICRODestination { get; set; }
        public int ICROExportCount { get; set; }
        public string ICROExportStatus { get; set; }
        public int FK_GLOrgTranCfgID { get; set; }
        public string ICROOF11Combo { get; set; }
        public string ICROOF12Combo { get; set; }
        public string ICROOF13Combo { get; set; }
        public string ICROOF14Combo { get; set; }
        public string ICROOF15Combo { get; set; }
        public string ICROCStatusCombo { get; set; }
        public decimal ICROActPrice { get; set; }
        public decimal ICROTotalPkgCBM { get; set; }
        public int FK_ARShpPlanID { get; set; }
        public string ICROLCNo { get; set; }
        public Nullable<DateTime> ICRODueTime { get; set; }
        public int ICROContQty { get; set; }
        public string ICROBillLadingNo { get; set; }
        public string ICROCustomsNo { get; set; }
        public string ICROTPortName { get; set; }
        public Nullable<DateTime> ICROCustomsDate { get; set; }
        public string ICROShipName { get; set; }
        public string ICROTripNo { get; set; }
        public string ICROExportStatusCombo { get; set; }
        public string ICROBooking { get; set; }
        public int FK_ADApprovalProcID { get; set; }
    }
}
