using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region ICKitItems
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: ICKitItemsInfo
    //Created Date: Tuesday, 26 Nov 2024
    //-----------------------------------------------------------
    [Table("ICKitItems")]
    public class ICKitItemsInfo : BaseInfo
    {
        #region Variables
        protected int _iCKitItemID;
        protected int _fK_ICKitID;
        protected int _fK_ICProductID;
        protected int _fK_ICUOMID;
        protected decimal _iCKitItemQty;
        protected decimal _iCKitItemMinQty;
        protected decimal _iCKitItemMaxQty;
        protected bool _iCKitItemAllowVariance = true;
        protected String _aAStatus = DefaultAAStatus;
        protected bool _aASelected = true;
        protected String _aACreatedUser = String.Empty;
        protected String _aAUpdatedUser = String.Empty;
        protected Nullable<DateTime> _aACreatedDate;
        protected Nullable<DateTime> _aAUpdatedDate;

        #endregion
        #region Public properties
        [Key]
        public int ICKitItemID
        {
            get { return _iCKitItemID; }
            set
            {
                if (value != this._iCKitItemID)
                {
                    _iCKitItemID = value;
                }
            }
        }
        public int FK_ICKitID
        {
            get { return _fK_ICKitID; }
            set
            {
                if (value != this._fK_ICKitID)
                {
                    _fK_ICKitID = value;
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                }
            }
        }
        public int FK_ICUOMID
        {
            get { return _fK_ICUOMID; }
            set
            {
                if (value != this._fK_ICUOMID)
                {
                    _fK_ICUOMID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal ICKitItemQty
        {
            get { return _iCKitItemQty; }
            set
            {
                if (value != this._iCKitItemQty)
                {
                    _iCKitItemQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal ICKitItemMinQty
        {
            get { return _iCKitItemMinQty; }
            set
            {
                if (value != this._iCKitItemMinQty)
                {
                    _iCKitItemMinQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal ICKitItemMaxQty
        {
            get { return _iCKitItemMaxQty; }
            set
            {
                if (value != this._iCKitItemMaxQty)
                {
                    _iCKitItemMaxQty = value;
                }
            }
        }
        public bool ICKitItemAllowVariance
        {
            get { return _iCKitItemAllowVariance; }
            set
            {
                if (value != this._iCKitItemAllowVariance)
                {
                    _iCKitItemAllowVariance = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }

        #endregion
    }
    #endregion
}