using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region ICRFIDProfiles
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ? H??? ???? (v3.0.73)
    //Class: ICRFIDProfilesInfo
    //Created Date: Wednesday, 26 Feb 2025
    //-----------------------------------------------------------
    [Table("ICRFIDProfiles")]
    public class ICRFIDProfilesInfo : BaseInfo
    {
        #region Variables
        protected int _iCRFIDProfileID;
        protected String _aAStatus = DefaultAAStatus;
        protected String _aACreatedUser = String.Empty;
        protected String _aAUpdatedUser = String.Empty;
        protected Nullable<DateTime> _aACreatedDate;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _iCRFIDProfileNo = String.Empty;
        protected DateTime _iCRFIDProfileDate = DateTime.Now;
        protected String _iCRFIDProfileData = String.Empty;
        protected String _iCRFIDProfileDesc = String.Empty;

        #endregion
        #region Public properties
        [Key]
        public int ICRFIDProfileID
        {
            get { return _iCRFIDProfileID; }
            set
            {
                if (value != this._iCRFIDProfileID)
                {
                    _iCRFIDProfileID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String ICRFIDProfileNo
        {
            get { return _iCRFIDProfileNo; }
            set
            {
                if (value != this._iCRFIDProfileNo)
                {
                    _iCRFIDProfileNo = value;
                }
            }
        }
        public DateTime ICRFIDProfileDate
        {
            get { return _iCRFIDProfileDate; }
            set
            {
                if (value != this._iCRFIDProfileDate)
                {
                    _iCRFIDProfileDate = value;
                }
            }
        }
        public String ICRFIDProfileData
        {
            get { return _iCRFIDProfileData; }
            set
            {
                if (value != this._iCRFIDProfileData)
                {
                    _iCRFIDProfileData = value;
                }
            }
        }
        public String ICRFIDProfileDesc
        {
            get { return _iCRFIDProfileDesc; }
            set
            {
                if (value != this._iCRFIDProfileDesc)
                {
                    _iCRFIDProfileDesc = value;
                }
            }
        }

        #endregion
    }
    #endregion
}