using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region PPNormAlternatives
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: PPNormAlternativesInfo
    //Created Date: Tuesday, 30 Sep 2025
    //-----------------------------------------------------------
    [Table("PPNormAlternatives")]
    public class PPNormAlternativesInfo : BaseInfo
    {
        #region Variables
        protected int _pPNormAlternativeID;
        protected Nullable<DateTime> _aACreatedDate;
        protected String _aACreatedUser = String.Empty;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_PPNormRMID;
        protected int _fK_ICProductID;
        protected decimal _pPNormAlternativeQty;
        protected int _pPNormAlternativeOrder;

        #endregion
        #region Public properties
        [Key]
        public int PPNormAlternativeID
        {
            get { return _pPNormAlternativeID; }
            set
            {
                if (value != this._pPNormAlternativeID)
                {
                    _pPNormAlternativeID = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public int FK_PPNormRMID
        {
            get { return _fK_PPNormRMID; }
            set
            {
                if (value != this._fK_PPNormRMID)
                {
                    _fK_PPNormRMID = value;
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPNormAlternativeQty
        {
            get { return _pPNormAlternativeQty; }
            set
            {
                if (value != this._pPNormAlternativeQty)
                {
                    _pPNormAlternativeQty = value;
                }
            }
        }
        public int PPNormAlternativeOrder
        {
            get { return _pPNormAlternativeOrder; }
            set
            {
                if (value != this._pPNormAlternativeOrder)
                {
                    _pPNormAlternativeOrder = value;
                }
            }
        }

        #endregion
    }
    #endregion
}