using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region PPPkgOrders
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.77)
    //Class: PPPkgOrdersInfo
    //Created Date: Tuesday, 24 Feb 2026
    //-----------------------------------------------------------
    [Table("PPPkgOrders")]
    public class PPPkgOrdersInfo : BaseInfo
    {
        #region Variables
        protected int _pPPkgOrderID;
        protected Nullable<DateTime> _aACreatedDate;
        protected String _aACreatedUser = String.Empty;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected bool _aASelected = true;
        protected String _pPPkgOrderNo = String.Empty;
        protected DateTime _pPPkgOrderDate = DateTime.Now;
        protected String _pPPkgOrderDesc = String.Empty;
        protected String _pPPkgOrderPONo = String.Empty;
        protected String _pPPkgOrderContNo = String.Empty;
        protected String _pPPkgOrderSealNo = String.Empty;
        protected int _fK_HREmployeeID;
        protected decimal _pPPkgOrderActPrice;
        protected decimal _pPPkgOrderTotalPkgCBM;
        protected int _fK_ARShpPlanID;
        protected int _fK_LOPortPOLID;
        protected int _fK_LOPortPODID;
        protected Nullable<DateTime> _pPPkgOrderETDDate;
        protected Nullable<DateTime> _pPPkgOrderETADate;
        protected Nullable<DateTime> _pPPkgOrderReceivedDate;
        protected int _fK_ARShipperID;
        protected String _pPPkgOrderShipperTaxNo = String.Empty;
        protected String _pPPkgOrderShipperAddress = String.Empty;
        protected int _fK_ARConsigneeID;
        protected String _pPPkgOrderConsigneeTaxNo = String.Empty;
        protected String _pPPkgOrderConsigneeAddress = String.Empty;
        protected int _fK_LOAgentID;
        protected String _pPPkgOrderAgentTaxNo = String.Empty;
        protected String _pPPkgOrderAgentAddress = String.Empty;
        protected int _fK_LOCarrierID;
        protected String _pPPkgOrderCarrierTaxNo = String.Empty;
        protected String _pPPkgOrderCarrierAddress = String.Empty;
        protected decimal _pPPkgOrderAmtTot;
        protected String _pPPkgOrderLPortName = String.Empty;
        protected String _pPPkgOrderDPortName = String.Empty;
        protected String _pPPkgOrderConsigneeName = String.Empty;
        protected String _pPPkgOrderShipperName = String.Empty;
        protected String _pPPkgOrderAgentName = String.Empty;
        protected String _pPPkgOrderCarrierName = String.Empty;
        protected int _fK_ARCustomerID;
        protected String _pPPkgOrderLCNo = String.Empty;
        protected String _approvalStatusCombo = DefaultStatus;
        protected Nullable<DateTime> _pPPkgOrderDueTime;
        protected int _pPPkgOrderContQty;
        protected String _pPPkgOrderBillLadingNo = String.Empty;
        protected String _pPPkgOrderCustomsNo = String.Empty;
        protected String _pPPkgOrderTPortName = String.Empty;
        protected Nullable<DateTime> _pPPkgOrderCustomsDate;
        protected String _pPPkgOrderShipName = String.Empty;
        protected String _pPPkgOrderTripNo = String.Empty;
        protected String _pPPkgOrderExportStatusCombo = DefaultStatus;
        protected int _fK_GLTranCfgID;
        protected String _pPKkgOrderBooking = String.Empty;

        #endregion
        #region Public properties
        [Key]
        public int PPPkgOrderID
        {
            get { return _pPPkgOrderID; }
            set
            {
                if (value != this._pPPkgOrderID)
                {
                    _pPPkgOrderID = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public String PPPkgOrderNo
        {
            get { return _pPPkgOrderNo; }
            set
            {
                if (value != this._pPPkgOrderNo)
                {
                    _pPPkgOrderNo = value;
                }
            }
        }
        public DateTime PPPkgOrderDate
        {
            get { return _pPPkgOrderDate; }
            set
            {
                if (value != this._pPPkgOrderDate)
                {
                    _pPPkgOrderDate = value;
                }
            }
        }
        public String PPPkgOrderDesc
        {
            get { return _pPPkgOrderDesc; }
            set
            {
                if (value != this._pPPkgOrderDesc)
                {
                    _pPPkgOrderDesc = value;
                }
            }
        }
        public String PPPkgOrderPONo
        {
            get { return _pPPkgOrderPONo; }
            set
            {
                if (value != this._pPPkgOrderPONo)
                {
                    _pPPkgOrderPONo = value;
                }
            }
        }
        public String PPPkgOrderContNo
        {
            get { return _pPPkgOrderContNo; }
            set
            {
                if (value != this._pPPkgOrderContNo)
                {
                    _pPPkgOrderContNo = value;
                }
            }
        }
        public String PPPkgOrderSealNo
        {
            get { return _pPPkgOrderSealNo; }
            set
            {
                if (value != this._pPPkgOrderSealNo)
                {
                    _pPPkgOrderSealNo = value;
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPPkgOrderActPrice
        {
            get { return _pPPkgOrderActPrice; }
            set
            {
                if (value != this._pPPkgOrderActPrice)
                {
                    _pPPkgOrderActPrice = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPPkgOrderTotalPkgCBM
        {
            get { return _pPPkgOrderTotalPkgCBM; }
            set
            {
                if (value != this._pPPkgOrderTotalPkgCBM)
                {
                    _pPPkgOrderTotalPkgCBM = value;
                }
            }
        }
        public int FK_ARShpPlanID
        {
            get { return _fK_ARShpPlanID; }
            set
            {
                if (value != this._fK_ARShpPlanID)
                {
                    _fK_ARShpPlanID = value;
                }
            }
        }
        public int FK_LOPortPOLID
        {
            get { return _fK_LOPortPOLID; }
            set
            {
                if (value != this._fK_LOPortPOLID)
                {
                    _fK_LOPortPOLID = value;
                }
            }
        }
        public int FK_LOPortPODID
        {
            get { return _fK_LOPortPODID; }
            set
            {
                if (value != this._fK_LOPortPODID)
                {
                    _fK_LOPortPODID = value;
                }
            }
        }
        public Nullable<DateTime> PPPkgOrderETDDate
        {
            get { return _pPPkgOrderETDDate; }
            set
            {
                if (value != this._pPPkgOrderETDDate)
                {
                    _pPPkgOrderETDDate = value;
                }
            }
        }
        public Nullable<DateTime> PPPkgOrderETADate
        {
            get { return _pPPkgOrderETADate; }
            set
            {
                if (value != this._pPPkgOrderETADate)
                {
                    _pPPkgOrderETADate = value;
                }
            }
        }
        public Nullable<DateTime> PPPkgOrderReceivedDate
        {
            get { return _pPPkgOrderReceivedDate; }
            set
            {
                if (value != this._pPPkgOrderReceivedDate)
                {
                    _pPPkgOrderReceivedDate = value;
                }
            }
        }
        public int FK_ARShipperID
        {
            get { return _fK_ARShipperID; }
            set
            {
                if (value != this._fK_ARShipperID)
                {
                    _fK_ARShipperID = value;
                }
            }
        }
        public String PPPkgOrderShipperTaxNo
        {
            get { return _pPPkgOrderShipperTaxNo; }
            set
            {
                if (value != this._pPPkgOrderShipperTaxNo)
                {
                    _pPPkgOrderShipperTaxNo = value;
                }
            }
        }
        public String PPPkgOrderShipperAddress
        {
            get { return _pPPkgOrderShipperAddress; }
            set
            {
                if (value != this._pPPkgOrderShipperAddress)
                {
                    _pPPkgOrderShipperAddress = value;
                }
            }
        }
        public int FK_ARConsigneeID
        {
            get { return _fK_ARConsigneeID; }
            set
            {
                if (value != this._fK_ARConsigneeID)
                {
                    _fK_ARConsigneeID = value;
                }
            }
        }
        public String PPPkgOrderConsigneeTaxNo
        {
            get { return _pPPkgOrderConsigneeTaxNo; }
            set
            {
                if (value != this._pPPkgOrderConsigneeTaxNo)
                {
                    _pPPkgOrderConsigneeTaxNo = value;
                }
            }
        }
        public String PPPkgOrderConsigneeAddress
        {
            get { return _pPPkgOrderConsigneeAddress; }
            set
            {
                if (value != this._pPPkgOrderConsigneeAddress)
                {
                    _pPPkgOrderConsigneeAddress = value;
                }
            }
        }
        public int FK_LOAgentID
        {
            get { return _fK_LOAgentID; }
            set
            {
                if (value != this._fK_LOAgentID)
                {
                    _fK_LOAgentID = value;
                }
            }
        }
        public String PPPkgOrderAgentTaxNo
        {
            get { return _pPPkgOrderAgentTaxNo; }
            set
            {
                if (value != this._pPPkgOrderAgentTaxNo)
                {
                    _pPPkgOrderAgentTaxNo = value;
                }
            }
        }
        public String PPPkgOrderAgentAddress
        {
            get { return _pPPkgOrderAgentAddress; }
            set
            {
                if (value != this._pPPkgOrderAgentAddress)
                {
                    _pPPkgOrderAgentAddress = value;
                }
            }
        }
        public int FK_LOCarrierID
        {
            get { return _fK_LOCarrierID; }
            set
            {
                if (value != this._fK_LOCarrierID)
                {
                    _fK_LOCarrierID = value;
                }
            }
        }
        public String PPPkgOrderCarrierTaxNo
        {
            get { return _pPPkgOrderCarrierTaxNo; }
            set
            {
                if (value != this._pPPkgOrderCarrierTaxNo)
                {
                    _pPPkgOrderCarrierTaxNo = value;
                }
            }
        }
        public String PPPkgOrderCarrierAddress
        {
            get { return _pPPkgOrderCarrierAddress; }
            set
            {
                if (value != this._pPPkgOrderCarrierAddress)
                {
                    _pPPkgOrderCarrierAddress = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPPkgOrderAmtTot
        {
            get { return _pPPkgOrderAmtTot; }
            set
            {
                if (value != this._pPPkgOrderAmtTot)
                {
                    _pPPkgOrderAmtTot = value;
                }
            }
        }
        public String PPPkgOrderLPortName
        {
            get { return _pPPkgOrderLPortName; }
            set
            {
                if (value != this._pPPkgOrderLPortName)
                {
                    _pPPkgOrderLPortName = value;
                }
            }
        }
        public String PPPkgOrderDPortName
        {
            get { return _pPPkgOrderDPortName; }
            set
            {
                if (value != this._pPPkgOrderDPortName)
                {
                    _pPPkgOrderDPortName = value;
                }
            }
        }
        public String PPPkgOrderConsigneeName
        {
            get { return _pPPkgOrderConsigneeName; }
            set
            {
                if (value != this._pPPkgOrderConsigneeName)
                {
                    _pPPkgOrderConsigneeName = value;
                }
            }
        }
        public String PPPkgOrderShipperName
        {
            get { return _pPPkgOrderShipperName; }
            set
            {
                if (value != this._pPPkgOrderShipperName)
                {
                    _pPPkgOrderShipperName = value;
                }
            }
        }
        public String PPPkgOrderAgentName
        {
            get { return _pPPkgOrderAgentName; }
            set
            {
                if (value != this._pPPkgOrderAgentName)
                {
                    _pPPkgOrderAgentName = value;
                }
            }
        }
        public String PPPkgOrderCarrierName
        {
            get { return _pPPkgOrderCarrierName; }
            set
            {
                if (value != this._pPPkgOrderCarrierName)
                {
                    _pPPkgOrderCarrierName = value;
                }
            }
        }
        public int FK_ARCustomerID
        {
            get { return _fK_ARCustomerID; }
            set
            {
                if (value != this._fK_ARCustomerID)
                {
                    _fK_ARCustomerID = value;
                }
            }
        }
        public String PPPkgOrderLCNo
        {
            get { return _pPPkgOrderLCNo; }
            set
            {
                if (value != this._pPPkgOrderLCNo)
                {
                    _pPPkgOrderLCNo = value;
                }
            }
        }
        public String ApprovalStatusCombo
        {
            get { return _approvalStatusCombo; }
            set
            {
                if (value != this._approvalStatusCombo)
                {
                    _approvalStatusCombo = value;
                }
            }
        }
        public Nullable<DateTime> PPPkgOrderDueTime
        {
            get { return _pPPkgOrderDueTime; }
            set
            {
                if (value != this._pPPkgOrderDueTime)
                {
                    _pPPkgOrderDueTime = value;
                }
            }
        }
        public int PPPkgOrderContQty
        {
            get { return _pPPkgOrderContQty; }
            set
            {
                if (value != this._pPPkgOrderContQty)
                {
                    _pPPkgOrderContQty = value;
                }
            }
        }
        public String PPPkgOrderBillLadingNo
        {
            get { return _pPPkgOrderBillLadingNo; }
            set
            {
                if (value != this._pPPkgOrderBillLadingNo)
                {
                    _pPPkgOrderBillLadingNo = value;
                }
            }
        }
        public String PPPkgOrderCustomsNo
        {
            get { return _pPPkgOrderCustomsNo; }
            set
            {
                if (value != this._pPPkgOrderCustomsNo)
                {
                    _pPPkgOrderCustomsNo = value;
                }
            }
        }
        public String PPPkgOrderTPortName
        {
            get { return _pPPkgOrderTPortName; }
            set
            {
                if (value != this._pPPkgOrderTPortName)
                {
                    _pPPkgOrderTPortName = value;
                }
            }
        }
        public Nullable<DateTime> PPPkgOrderCustomsDate
        {
            get { return _pPPkgOrderCustomsDate; }
            set
            {
                if (value != this._pPPkgOrderCustomsDate)
                {
                    _pPPkgOrderCustomsDate = value;
                }
            }
        }
        public String PPPkgOrderShipName
        {
            get { return _pPPkgOrderShipName; }
            set
            {
                if (value != this._pPPkgOrderShipName)
                {
                    _pPPkgOrderShipName = value;
                }
            }
        }
        public String PPPkgOrderTripNo
        {
            get { return _pPPkgOrderTripNo; }
            set
            {
                if (value != this._pPPkgOrderTripNo)
                {
                    _pPPkgOrderTripNo = value;
                }
            }
        }
        public String PPPkgOrderExportStatusCombo
        {
            get { return _pPPkgOrderExportStatusCombo; }
            set
            {
                if (value != this._pPPkgOrderExportStatusCombo)
                {
                    _pPPkgOrderExportStatusCombo = value;
                }
            }
        }
        public int FK_GLTranCfgID
        {
            get { return _fK_GLTranCfgID; }
            set
            {
                if (value != this._fK_GLTranCfgID)
                {
                    _fK_GLTranCfgID = value;
                }
            }
        }
        public String PPKkgOrderBooking
        {
            get { return _pPKkgOrderBooking; }
            set
            {
                if (value != this._pPKkgOrderBooking)
                {
                    _pPKkgOrderBooking = value;
                }
            }
        }

        #endregion
    }
    #endregion
}