using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities.PP
{
    #region PPWOPItems
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: PPWOPItemsInfo
    //Created Date: Monday, 29 Sep 2025
    //-----------------------------------------------------------
    [Table("PPWOPItems")]
    public class PPWOPItemsInfo : BaseInfo
    {
        #region Variables
        protected int _pPWOPItemID;
        protected bool _aASelected = true;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_PPWOID;
        protected int _fK_ICProductID;
        protected int _fK_ICStockID;
        protected int _fK_ICStockSlotID;
        protected int _fK_ICProductTypeID;
        protected int _fK_ARPriceListID;
        protected int _fK_TXTaxCodeID;
        protected String _pPWOPItemSerialNo = String.Empty;
        protected String _pPWOPItemType = String.Empty;
        protected bool _pPWOPItemIsStkItm = false;
        protected String _pPWOPItemDesc = String.Empty;
        protected decimal _pPWOPItemFact;
        protected decimal _pPWOPItemUnitPrice;
        protected decimal _pPWOPItemUnitCost;
        protected decimal _pPWOPItemDiscPct;
        protected decimal _pPWOPItemTxPct;
        protected decimal _pPWOPItemQty;
        protected decimal _pPWOPItemStkQty;
        protected decimal _pPWOPItemRQty;
        protected decimal _pPWOPItemRStkQty;
        protected decimal _pPWOPItemPrice;
        protected String _pPWOPItemComment = String.Empty;
        protected decimal _pPWOPItemUnitVol;
        protected decimal _pPWOPItemUnitWeight;
        protected decimal _pPWOPItemTxAmt;
        protected decimal _pPWOPItemDiscAmt;
        protected decimal _pPWOPItemNetAmt;
        protected decimal _pPWOPItemAmtTot;
        protected decimal _pPWOPItemCostTot;
        protected String _pPWOPItemStatus = DefaultStatus;
        protected decimal _pPWOPItemRORQty;
        protected String _pPWOPItemROStatusCombo = DefaultStatus;
        protected decimal _pPWOPItemROQty;
        protected decimal _pPWOItemShpQty;
        protected String _pPWOPItemNo = String.Empty;
        protected String _pPWOPItemName = String.Empty;
        protected int _fK_ICUOMID;
        protected int _fK_ICStkUOMID;
        protected int _fK_PPMPSItemID;
        protected int _pPWOPItemPeriod;
        protected int _pPWOPItemYear;
        protected int _pPWOPItemWeek;
        protected int _fK_ARSOID;
        protected int _fK_ARSOItemID;
        protected DateTime _pPWOPItemShpDate = DateTime.Now;
        protected String _pPWOPItemLotNo = String.Empty;
        protected int _fK_ARContractID;
        protected int _fK_ARContractItemID;
        protected int _pPWOPItemKey;
        protected decimal _pPWOPItemWasteQty;
        protected decimal _pPWOPItemInvQty;
        protected decimal _pPWOPItemPOQty;
        protected decimal _pPWOPItemBalanceQty;
        protected decimal _pPWOPItemActAllocateQty;
        protected decimal _pPWOPItemAllocateQty;
        protected decimal _pPWOPItemWOQty;
        protected decimal _pPWOPItemWastePct;
        protected String _gLTOF01Combo = String.Empty;
        protected String _gLTOF02Combo = String.Empty;
        protected String _gLTOF03Combo = String.Empty;
        protected String _gLTOF04Combo = String.Empty;
        protected String _gLTOF05Combo = String.Empty;
        protected String _gLTOF06Combo = String.Empty;
        protected String _gLTOF07Combo = String.Empty;
        protected String _gLTOF08Combo = String.Empty;
        protected String _gLTOF09Combo = String.Empty;
        protected String _gLTOF10Combo = String.Empty;
        protected String _gLTOF11Combo = String.Empty;
        protected String _gLTOF12Combo = String.Empty;
        protected String _gLTOF13Combo = String.Empty;
        protected String _gLTOF14Combo = String.Empty;
        protected String _gLTOF15Combo = String.Empty;
        protected String _pPWOPItemMSRevision = String.Empty;
        protected int _fK_ARSaleReturnID;
        protected int _fK_ARSaleReturnItemID;
        protected String _pPWOPItemPONumber = String.Empty;
        protected String _pPWOPItemDesc2 = String.Empty;
        protected decimal _pPWOPItemCQty;
        protected int _pPWOPItemBOMLevel;
        protected decimal _pPWOPItemMinStockQty;
        protected int _fK_PPMPSID;
        protected String _pPWOPItemBOMRevision = String.Empty;
        protected int _fK_PPRoutingID;
        protected int _fK_PPResourceID;
        protected String _pPWOPItemPOF01Combo = String.Empty;
        protected String _pPWOPItemPOF02Combo = String.Empty;
        protected String _pPWOPItemPOF03Combo = String.Empty;
        protected String _pPWOPItemPOF04Combo = String.Empty;
        protected String _pPWOPItemPOF05Combo = String.Empty;
        protected int _pPWOPItemSortOrder;
        protected int _fK_PPWOParentID;
        protected decimal _pPWOPItemRollLengthQty;
        protected decimal _pPWOPItemThicknessQty;
        protected decimal _pPWOPItemDensityQty;
        protected int _pPWOPItemWOKey;
        protected int _fK_PPWORID;
        protected int _fK_PPWORItemID;
        protected decimal _pPWOPItemLastQty;

        #endregion
        #region Public properties
        [Key]
        public int PPWOPItemID
        {
            get { return _pPWOPItemID; }
            set
            {
                if (value != this._pPWOPItemID)
                {
                    _pPWOPItemID = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public int FK_PPWOID
        {
            get { return _fK_PPWOID; }
            set
            {
                if (value != this._fK_PPWOID)
                {
                    _fK_PPWOID = value;
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                }
            }
        }
        public int FK_ICStockID
        {
            get { return _fK_ICStockID; }
            set
            {
                if (value != this._fK_ICStockID)
                {
                    _fK_ICStockID = value;
                }
            }
        }
        public int FK_ICStockSlotID
        {
            get { return _fK_ICStockSlotID; }
            set
            {
                if (value != this._fK_ICStockSlotID)
                {
                    _fK_ICStockSlotID = value;
                }
            }
        }
        public int FK_ICProductTypeID
        {
            get { return _fK_ICProductTypeID; }
            set
            {
                if (value != this._fK_ICProductTypeID)
                {
                    _fK_ICProductTypeID = value;
                }
            }
        }
        public int FK_ARPriceListID
        {
            get { return _fK_ARPriceListID; }
            set
            {
                if (value != this._fK_ARPriceListID)
                {
                    _fK_ARPriceListID = value;
                }
            }
        }
        public int FK_TXTaxCodeID
        {
            get { return _fK_TXTaxCodeID; }
            set
            {
                if (value != this._fK_TXTaxCodeID)
                {
                    _fK_TXTaxCodeID = value;
                }
            }
        }
        public String PPWOPItemSerialNo
        {
            get { return _pPWOPItemSerialNo; }
            set
            {
                if (value != this._pPWOPItemSerialNo)
                {
                    _pPWOPItemSerialNo = value;
                }
            }
        }
        public String PPWOPItemType
        {
            get { return _pPWOPItemType; }
            set
            {
                if (value != this._pPWOPItemType)
                {
                    _pPWOPItemType = value;
                }
            }
        }
        public bool PPWOPItemIsStkItm
        {
            get { return _pPWOPItemIsStkItm; }
            set
            {
                if (value != this._pPWOPItemIsStkItm)
                {
                    _pPWOPItemIsStkItm = value;
                }
            }
        }
        public String PPWOPItemDesc
        {
            get { return _pPWOPItemDesc; }
            set
            {
                if (value != this._pPWOPItemDesc)
                {
                    _pPWOPItemDesc = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemFact
        {
            get { return _pPWOPItemFact; }
            set
            {
                if (value != this._pPWOPItemFact)
                {
                    _pPWOPItemFact = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemUnitPrice
        {
            get { return _pPWOPItemUnitPrice; }
            set
            {
                if (value != this._pPWOPItemUnitPrice)
                {
                    _pPWOPItemUnitPrice = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemUnitCost
        {
            get { return _pPWOPItemUnitCost; }
            set
            {
                if (value != this._pPWOPItemUnitCost)
                {
                    _pPWOPItemUnitCost = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemDiscPct
        {
            get { return _pPWOPItemDiscPct; }
            set
            {
                if (value != this._pPWOPItemDiscPct)
                {
                    _pPWOPItemDiscPct = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemTxPct
        {
            get { return _pPWOPItemTxPct; }
            set
            {
                if (value != this._pPWOPItemTxPct)
                {
                    _pPWOPItemTxPct = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemQty
        {
            get { return _pPWOPItemQty; }
            set
            {
                if (value != this._pPWOPItemQty)
                {
                    _pPWOPItemQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemStkQty
        {
            get { return _pPWOPItemStkQty; }
            set
            {
                if (value != this._pPWOPItemStkQty)
                {
                    _pPWOPItemStkQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemRQty
        {
            get { return _pPWOPItemRQty; }
            set
            {
                if (value != this._pPWOPItemRQty)
                {
                    _pPWOPItemRQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemRStkQty
        {
            get { return _pPWOPItemRStkQty; }
            set
            {
                if (value != this._pPWOPItemRStkQty)
                {
                    _pPWOPItemRStkQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemPrice
        {
            get { return _pPWOPItemPrice; }
            set
            {
                if (value != this._pPWOPItemPrice)
                {
                    _pPWOPItemPrice = value;
                }
            }
        }
        public String PPWOPItemComment
        {
            get { return _pPWOPItemComment; }
            set
            {
                if (value != this._pPWOPItemComment)
                {
                    _pPWOPItemComment = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemUnitVol
        {
            get { return _pPWOPItemUnitVol; }
            set
            {
                if (value != this._pPWOPItemUnitVol)
                {
                    _pPWOPItemUnitVol = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemUnitWeight
        {
            get { return _pPWOPItemUnitWeight; }
            set
            {
                if (value != this._pPWOPItemUnitWeight)
                {
                    _pPWOPItemUnitWeight = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemTxAmt
        {
            get { return _pPWOPItemTxAmt; }
            set
            {
                if (value != this._pPWOPItemTxAmt)
                {
                    _pPWOPItemTxAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemDiscAmt
        {
            get { return _pPWOPItemDiscAmt; }
            set
            {
                if (value != this._pPWOPItemDiscAmt)
                {
                    _pPWOPItemDiscAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemNetAmt
        {
            get { return _pPWOPItemNetAmt; }
            set
            {
                if (value != this._pPWOPItemNetAmt)
                {
                    _pPWOPItemNetAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemAmtTot
        {
            get { return _pPWOPItemAmtTot; }
            set
            {
                if (value != this._pPWOPItemAmtTot)
                {
                    _pPWOPItemAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemCostTot
        {
            get { return _pPWOPItemCostTot; }
            set
            {
                if (value != this._pPWOPItemCostTot)
                {
                    _pPWOPItemCostTot = value;
                }
            }
        }
        public String PPWOPItemStatus
        {
            get { return _pPWOPItemStatus; }
            set
            {
                if (value != this._pPWOPItemStatus)
                {
                    _pPWOPItemStatus = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemRORQty
        {
            get { return _pPWOPItemRORQty; }
            set
            {
                if (value != this._pPWOPItemRORQty)
                {
                    _pPWOPItemRORQty = value;
                }
            }
        }
        public String PPWOPItemROStatusCombo
        {
            get { return _pPWOPItemROStatusCombo; }
            set
            {
                if (value != this._pPWOPItemROStatusCombo)
                {
                    _pPWOPItemROStatusCombo = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemROQty
        {
            get { return _pPWOPItemROQty; }
            set
            {
                if (value != this._pPWOPItemROQty)
                {
                    _pPWOPItemROQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOItemShpQty
        {
            get { return _pPWOItemShpQty; }
            set
            {
                if (value != this._pPWOItemShpQty)
                {
                    _pPWOItemShpQty = value;
                }
            }
        }
        public String PPWOPItemNo
        {
            get { return _pPWOPItemNo; }
            set
            {
                if (value != this._pPWOPItemNo)
                {
                    _pPWOPItemNo = value;
                }
            }
        }
        public String PPWOPItemName
        {
            get { return _pPWOPItemName; }
            set
            {
                if (value != this._pPWOPItemName)
                {
                    _pPWOPItemName = value;
                }
            }
        }
        public int FK_ICUOMID
        {
            get { return _fK_ICUOMID; }
            set
            {
                if (value != this._fK_ICUOMID)
                {
                    _fK_ICUOMID = value;
                }
            }
        }
        public int FK_ICStkUOMID
        {
            get { return _fK_ICStkUOMID; }
            set
            {
                if (value != this._fK_ICStkUOMID)
                {
                    _fK_ICStkUOMID = value;
                }
            }
        }
        public int FK_PPMPSItemID
        {
            get { return _fK_PPMPSItemID; }
            set
            {
                if (value != this._fK_PPMPSItemID)
                {
                    _fK_PPMPSItemID = value;
                }
            }
        }
        public int PPWOPItemPeriod
        {
            get { return _pPWOPItemPeriod; }
            set
            {
                if (value != this._pPWOPItemPeriod)
                {
                    _pPWOPItemPeriod = value;
                }
            }
        }
        public int PPWOPItemYear
        {
            get { return _pPWOPItemYear; }
            set
            {
                if (value != this._pPWOPItemYear)
                {
                    _pPWOPItemYear = value;
                }
            }
        }
        public int PPWOPItemWeek
        {
            get { return _pPWOPItemWeek; }
            set
            {
                if (value != this._pPWOPItemWeek)
                {
                    _pPWOPItemWeek = value;
                }
            }
        }
        public int FK_ARSOID
        {
            get { return _fK_ARSOID; }
            set
            {
                if (value != this._fK_ARSOID)
                {
                    _fK_ARSOID = value;
                }
            }
        }
        public int FK_ARSOItemID
        {
            get { return _fK_ARSOItemID; }
            set
            {
                if (value != this._fK_ARSOItemID)
                {
                    _fK_ARSOItemID = value;
                }
            }
        }
        public DateTime PPWOPItemShpDate
        {
            get { return _pPWOPItemShpDate; }
            set
            {
                if (value != this._pPWOPItemShpDate)
                {
                    _pPWOPItemShpDate = value;
                }
            }
        }
        public String PPWOPItemLotNo
        {
            get { return _pPWOPItemLotNo; }
            set
            {
                if (value != this._pPWOPItemLotNo)
                {
                    _pPWOPItemLotNo = value;
                }
            }
        }
        public int FK_ARContractID
        {
            get { return _fK_ARContractID; }
            set
            {
                if (value != this._fK_ARContractID)
                {
                    _fK_ARContractID = value;
                }
            }
        }
        public int FK_ARContractItemID
        {
            get { return _fK_ARContractItemID; }
            set
            {
                if (value != this._fK_ARContractItemID)
                {
                    _fK_ARContractItemID = value;
                }
            }
        }
        public int PPWOPItemKey
        {
            get { return _pPWOPItemKey; }
            set
            {
                if (value != this._pPWOPItemKey)
                {
                    _pPWOPItemKey = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemWasteQty
        {
            get { return _pPWOPItemWasteQty; }
            set
            {
                if (value != this._pPWOPItemWasteQty)
                {
                    _pPWOPItemWasteQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemInvQty
        {
            get { return _pPWOPItemInvQty; }
            set
            {
                if (value != this._pPWOPItemInvQty)
                {
                    _pPWOPItemInvQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemPOQty
        {
            get { return _pPWOPItemPOQty; }
            set
            {
                if (value != this._pPWOPItemPOQty)
                {
                    _pPWOPItemPOQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemBalanceQty
        {
            get { return _pPWOPItemBalanceQty; }
            set
            {
                if (value != this._pPWOPItemBalanceQty)
                {
                    _pPWOPItemBalanceQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemActAllocateQty
        {
            get { return _pPWOPItemActAllocateQty; }
            set
            {
                if (value != this._pPWOPItemActAllocateQty)
                {
                    _pPWOPItemActAllocateQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemAllocateQty
        {
            get { return _pPWOPItemAllocateQty; }
            set
            {
                if (value != this._pPWOPItemAllocateQty)
                {
                    _pPWOPItemAllocateQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemWOQty
        {
            get { return _pPWOPItemWOQty; }
            set
            {
                if (value != this._pPWOPItemWOQty)
                {
                    _pPWOPItemWOQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemWastePct
        {
            get { return _pPWOPItemWastePct; }
            set
            {
                if (value != this._pPWOPItemWastePct)
                {
                    _pPWOPItemWastePct = value;
                }
            }
        }
        public String GLTOF01Combo
        {
            get { return _gLTOF01Combo; }
            set
            {
                if (value != this._gLTOF01Combo)
                {
                    _gLTOF01Combo = value;
                }
            }
        }
        public String GLTOF02Combo
        {
            get { return _gLTOF02Combo; }
            set
            {
                if (value != this._gLTOF02Combo)
                {
                    _gLTOF02Combo = value;
                }
            }
        }
        public String GLTOF03Combo
        {
            get { return _gLTOF03Combo; }
            set
            {
                if (value != this._gLTOF03Combo)
                {
                    _gLTOF03Combo = value;
                }
            }
        }
        public String GLTOF04Combo
        {
            get { return _gLTOF04Combo; }
            set
            {
                if (value != this._gLTOF04Combo)
                {
                    _gLTOF04Combo = value;
                }
            }
        }
        public String GLTOF05Combo
        {
            get { return _gLTOF05Combo; }
            set
            {
                if (value != this._gLTOF05Combo)
                {
                    _gLTOF05Combo = value;
                }
            }
        }
        public String GLTOF06Combo
        {
            get { return _gLTOF06Combo; }
            set
            {
                if (value != this._gLTOF06Combo)
                {
                    _gLTOF06Combo = value;
                }
            }
        }
        public String GLTOF07Combo
        {
            get { return _gLTOF07Combo; }
            set
            {
                if (value != this._gLTOF07Combo)
                {
                    _gLTOF07Combo = value;
                }
            }
        }
        public String GLTOF08Combo
        {
            get { return _gLTOF08Combo; }
            set
            {
                if (value != this._gLTOF08Combo)
                {
                    _gLTOF08Combo = value;
                }
            }
        }
        public String GLTOF09Combo
        {
            get { return _gLTOF09Combo; }
            set
            {
                if (value != this._gLTOF09Combo)
                {
                    _gLTOF09Combo = value;
                }
            }
        }
        public String GLTOF10Combo
        {
            get { return _gLTOF10Combo; }
            set
            {
                if (value != this._gLTOF10Combo)
                {
                    _gLTOF10Combo = value;
                }
            }
        }
        public String GLTOF11Combo
        {
            get { return _gLTOF11Combo; }
            set
            {
                if (value != this._gLTOF11Combo)
                {
                    _gLTOF11Combo = value;
                }
            }
        }
        public String GLTOF12Combo
        {
            get { return _gLTOF12Combo; }
            set
            {
                if (value != this._gLTOF12Combo)
                {
                    _gLTOF12Combo = value;
                }
            }
        }
        public String GLTOF13Combo
        {
            get { return _gLTOF13Combo; }
            set
            {
                if (value != this._gLTOF13Combo)
                {
                    _gLTOF13Combo = value;
                }
            }
        }
        public String GLTOF14Combo
        {
            get { return _gLTOF14Combo; }
            set
            {
                if (value != this._gLTOF14Combo)
                {
                    _gLTOF14Combo = value;
                }
            }
        }
        public String GLTOF15Combo
        {
            get { return _gLTOF15Combo; }
            set
            {
                if (value != this._gLTOF15Combo)
                {
                    _gLTOF15Combo = value;
                }
            }
        }
        public String PPWOPItemMSRevision
        {
            get { return _pPWOPItemMSRevision; }
            set
            {
                if (value != this._pPWOPItemMSRevision)
                {
                    _pPWOPItemMSRevision = value;
                }
            }
        }
        public int FK_ARSaleReturnID
        {
            get { return _fK_ARSaleReturnID; }
            set
            {
                if (value != this._fK_ARSaleReturnID)
                {
                    _fK_ARSaleReturnID = value;
                }
            }
        }
        public int FK_ARSaleReturnItemID
        {
            get { return _fK_ARSaleReturnItemID; }
            set
            {
                if (value != this._fK_ARSaleReturnItemID)
                {
                    _fK_ARSaleReturnItemID = value;
                }
            }
        }
        public String PPWOPItemPONumber
        {
            get { return _pPWOPItemPONumber; }
            set
            {
                if (value != this._pPWOPItemPONumber)
                {
                    _pPWOPItemPONumber = value;
                }
            }
        }
        public String PPWOPItemDesc2
        {
            get { return _pPWOPItemDesc2; }
            set
            {
                if (value != this._pPWOPItemDesc2)
                {
                    _pPWOPItemDesc2 = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemCQty
        {
            get { return _pPWOPItemCQty; }
            set
            {
                if (value != this._pPWOPItemCQty)
                {
                    _pPWOPItemCQty = value;
                }
            }
        }
        public int PPWOPItemBOMLevel
        {
            get { return _pPWOPItemBOMLevel; }
            set
            {
                if (value != this._pPWOPItemBOMLevel)
                {
                    _pPWOPItemBOMLevel = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemMinStockQty
        {
            get { return _pPWOPItemMinStockQty; }
            set
            {
                if (value != this._pPWOPItemMinStockQty)
                {
                    _pPWOPItemMinStockQty = value;
                }
            }
        }
        public int FK_PPMPSID
        {
            get { return _fK_PPMPSID; }
            set
            {
                if (value != this._fK_PPMPSID)
                {
                    _fK_PPMPSID = value;
                }
            }
        }
        public String PPWOPItemBOMRevision
        {
            get { return _pPWOPItemBOMRevision; }
            set
            {
                if (value != this._pPWOPItemBOMRevision)
                {
                    _pPWOPItemBOMRevision = value;
                }
            }
        }
        public int FK_PPRoutingID
        {
            get { return _fK_PPRoutingID; }
            set
            {
                if (value != this._fK_PPRoutingID)
                {
                    _fK_PPRoutingID = value;
                }
            }
        }
        public int FK_PPResourceID
        {
            get { return _fK_PPResourceID; }
            set
            {
                if (value != this._fK_PPResourceID)
                {
                    _fK_PPResourceID = value;
                }
            }
        }
        public String PPWOPItemPOF01Combo
        {
            get { return _pPWOPItemPOF01Combo; }
            set
            {
                if (value != this._pPWOPItemPOF01Combo)
                {
                    _pPWOPItemPOF01Combo = value;
                }
            }
        }
        public String PPWOPItemPOF02Combo
        {
            get { return _pPWOPItemPOF02Combo; }
            set
            {
                if (value != this._pPWOPItemPOF02Combo)
                {
                    _pPWOPItemPOF02Combo = value;
                }
            }
        }
        public String PPWOPItemPOF03Combo
        {
            get { return _pPWOPItemPOF03Combo; }
            set
            {
                if (value != this._pPWOPItemPOF03Combo)
                {
                    _pPWOPItemPOF03Combo = value;
                }
            }
        }
        public String PPWOPItemPOF04Combo
        {
            get { return _pPWOPItemPOF04Combo; }
            set
            {
                if (value != this._pPWOPItemPOF04Combo)
                {
                    _pPWOPItemPOF04Combo = value;
                }
            }
        }
        public String PPWOPItemPOF05Combo
        {
            get { return _pPWOPItemPOF05Combo; }
            set
            {
                if (value != this._pPWOPItemPOF05Combo)
                {
                    _pPWOPItemPOF05Combo = value;
                }
            }
        }
        public int PPWOPItemSortOrder
        {
            get { return _pPWOPItemSortOrder; }
            set
            {
                if (value != this._pPWOPItemSortOrder)
                {
                    _pPWOPItemSortOrder = value;
                }
            }
        }
        public int FK_PPWOParentID
        {
            get { return _fK_PPWOParentID; }
            set
            {
                if (value != this._fK_PPWOParentID)
                {
                    _fK_PPWOParentID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemRollLengthQty
        {
            get { return _pPWOPItemRollLengthQty; }
            set
            {
                if (value != this._pPWOPItemRollLengthQty)
                {
                    _pPWOPItemRollLengthQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemThicknessQty
        {
            get { return _pPWOPItemThicknessQty; }
            set
            {
                if (value != this._pPWOPItemThicknessQty)
                {
                    _pPWOPItemThicknessQty = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOPItemDensityQty
        {
            get { return _pPWOPItemDensityQty; }
            set
            {
                if (value != this._pPWOPItemDensityQty)
                {
                    _pPWOPItemDensityQty = value;
                }
            }
        }
        public int PPWOPItemWOKey
        {
            get { return _pPWOPItemWOKey; }
            set
            {
                if (value != this._pPWOPItemWOKey)
                {
                    _pPWOPItemWOKey = value;
                }
            }
        }
        public int FK_PPWORID
        {
            get { return _fK_PPWORID; }
            set
            {
                if (value != this._fK_PPWORID)
                {
                    _fK_PPWORID = value;
                }
            }
        }
        public int FK_PPWORItemID
        {
            get { return _fK_PPWORItemID; }
            set
            {
                if (value != this._fK_PPWORItemID)
                {
                    _fK_PPWORItemID = value;
                }
            }
        }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal PPWOPItemLastQty
        {
            get { return _pPWOPItemLastQty; }
            set
            {
                if (value != this._pPWOPItemLastQty)
                {
                    _pPWOPItemLastQty = value;
                }
            }
        }

        #endregion
    }
    #endregion
}