using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region PPWOs
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: PPWOsInfo
    //Created Date: Monday, 29 Sep 2025
    //-----------------------------------------------------------
    [Table("PPWOs")]
    public class PPWOsInfo : BaseInfo
    {
        #region Variables
        protected int _pPWOID;
        protected String _aAStatus = DefaultAAStatus;
        protected String _aACreatedUser = String.Empty;
        protected String _aAUpdatedUser = String.Empty;
        protected Nullable<DateTime> _aACreatedDate;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _pPWONo = String.Empty;
        protected String _pPWOName = String.Empty;
        protected String _pPWODesc = String.Empty;
        protected Nullable<DateTime> _pPWODate;
        protected String _pPWOStatus = DefaultStatus;
        protected Nullable<DateTime> _pPWOEstDate;
        protected Nullable<DateTime> _pPWOActDate;
        protected int _fK_HREmployeeID;
        protected int _fK_PPProductPlnID;
        protected int _fK_ARSOID;
        protected bool _aASelected = true;
        protected String _pPWOStatusCombo = DefaultStatus;
        protected int _fK_PPWBSID;
        protected Nullable<DateTime> _pPWOEstStartDate;
        protected Nullable<DateTime> _pPWOEstEndDate;
        protected decimal _pPWOEstTotDays;
        protected Nullable<DateTime> _pPWOActStartDate;
        protected Nullable<DateTime> _pPWOActEndDate;
        protected decimal _pPWOActTotDays;
        protected Nullable<DateTime> _pPWOIssueDate;
        protected decimal _pPWOEstTotManHour;
        protected decimal _pPWOActTotManHour;
        protected String _pPWOStatusDetail = DefaultStatus;
        protected decimal _pPWOCompPct;
        protected String _pPWOStatusManhour = DefaultStatus;
        protected decimal _pPWOTotWeight;
        protected decimal _pPWOActManHourPct;
        protected String _pPWOCostStatusCombo = DefaultStatus;
        protected String _pPWOSchedStatusCombo = DefaultStatus;
        protected int _fK_PMProjectID;
        protected String _pPWOCompleteApproveStatusCombo = DefaultStatus;
        protected int _fK_HRWorkshopID;
        protected String _pPWOSupervisorRemark = String.Empty;
        protected String _pPWOProductionRemark = String.Empty;
        protected String _pPWOCMRemark = String.Empty;
        protected String _pPWORemark = String.Empty;
        protected String _pPWOPriorityStatusCombo = DefaultStatus;
        protected String _pPWOCompleteActionTypeCombo = String.Empty;
        protected int _pPWOCompleteActionRequest;
        protected int _pPWOCompleteActionReject;
        protected int _pPWOAttachDocumentCount;
        protected int _fK_HREmpRequestToID;
        protected decimal _pPWOEstWeightKg;
        protected decimal _pPWOActWeightKg;
        protected String _pPWOPlanningApproveStatusCombo = DefaultStatus;
        protected String _pPWOPlanningActionTypeCombo = String.Empty;
        protected int _fK_PPWOGroupID;
        protected int _fK_PPProjectDiscID;
        protected int _fK_PPProjectFieldID;
        protected int _fK_PPWOParentID;
        protected String _pPWOChangeSourceCombo = String.Empty;
        protected int _fK_ADUserSendID;
        protected int _fK_ADUserReceiveID;
        protected int _fK_PMChangeOrdID;
        protected int _fK_PMChangeTypeID;
        protected String _pPWOQCStatusCombo = DefaultStatus;
        protected String _pPWOAreaDesc = String.Empty;
        protected String _pPWOAreaDocNo = String.Empty;
        protected String _pPWOAreaServerPath = String.Empty;
        protected String _pPWOExecutorTypeCombo = String.Empty;
        protected int _fK_PPMPSID;
        protected String _aAModule = String.Empty;
        protected String _pPWOTypeCombo = String.Empty;
        protected int _fK_BRBranchID;
        protected int _fK_GLTranCfgID;
        protected String _pPWOCStatusCombo = DefaultStatus;
        protected int _fK_PPWORID;
        protected int _fK_PPRoutingID;

        #endregion
        #region Public properties
        [Key]
        public int PPWOID
        {
            get { return _pPWOID; }
            set
            {
                if (value != this._pPWOID)
                {
                    _pPWOID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String PPWONo
        {
            get { return _pPWONo; }
            set
            {
                if (value != this._pPWONo)
                {
                    _pPWONo = value;
                }
            }
        }
        public String PPWOName
        {
            get { return _pPWOName; }
            set
            {
                if (value != this._pPWOName)
                {
                    _pPWOName = value;
                }
            }
        }
        public String PPWODesc
        {
            get { return _pPWODesc; }
            set
            {
                if (value != this._pPWODesc)
                {
                    _pPWODesc = value;
                }
            }
        }
        public Nullable<DateTime> PPWODate
        {
            get { return _pPWODate; }
            set
            {
                if (value != this._pPWODate)
                {
                    _pPWODate = value;
                }
            }
        }
        public String PPWOStatus
        {
            get { return _pPWOStatus; }
            set
            {
                if (value != this._pPWOStatus)
                {
                    _pPWOStatus = value;
                }
            }
        }
        public Nullable<DateTime> PPWOEstDate
        {
            get { return _pPWOEstDate; }
            set
            {
                if (value != this._pPWOEstDate)
                {
                    _pPWOEstDate = value;
                }
            }
        }
        public Nullable<DateTime> PPWOActDate
        {
            get { return _pPWOActDate; }
            set
            {
                if (value != this._pPWOActDate)
                {
                    _pPWOActDate = value;
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                }
            }
        }
        public int FK_PPProductPlnID
        {
            get { return _fK_PPProductPlnID; }
            set
            {
                if (value != this._fK_PPProductPlnID)
                {
                    _fK_PPProductPlnID = value;
                }
            }
        }
        public int FK_ARSOID
        {
            get { return _fK_ARSOID; }
            set
            {
                if (value != this._fK_ARSOID)
                {
                    _fK_ARSOID = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public String PPWOStatusCombo
        {
            get { return _pPWOStatusCombo; }
            set
            {
                if (value != this._pPWOStatusCombo)
                {
                    _pPWOStatusCombo = value;
                }
            }
        }
        public int FK_PPWBSID
        {
            get { return _fK_PPWBSID; }
            set
            {
                if (value != this._fK_PPWBSID)
                {
                    _fK_PPWBSID = value;
                }
            }
        }
        public Nullable<DateTime> PPWOEstStartDate
        {
            get { return _pPWOEstStartDate; }
            set
            {
                if (value != this._pPWOEstStartDate)
                {
                    _pPWOEstStartDate = value;
                }
            }
        }
        public Nullable<DateTime> PPWOEstEndDate
        {
            get { return _pPWOEstEndDate; }
            set
            {
                if (value != this._pPWOEstEndDate)
                {
                    _pPWOEstEndDate = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOEstTotDays
        {
            get { return _pPWOEstTotDays; }
            set
            {
                if (value != this._pPWOEstTotDays)
                {
                    _pPWOEstTotDays = value;
                }
            }
        }
        public Nullable<DateTime> PPWOActStartDate
        {
            get { return _pPWOActStartDate; }
            set
            {
                if (value != this._pPWOActStartDate)
                {
                    _pPWOActStartDate = value;
                }
            }
        }
        public Nullable<DateTime> PPWOActEndDate
        {
            get { return _pPWOActEndDate; }
            set
            {
                if (value != this._pPWOActEndDate)
                {
                    _pPWOActEndDate = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOActTotDays
        {
            get { return _pPWOActTotDays; }
            set
            {
                if (value != this._pPWOActTotDays)
                {
                    _pPWOActTotDays = value;
                }
            }
        }
        public Nullable<DateTime> PPWOIssueDate
        {
            get { return _pPWOIssueDate; }
            set
            {
                if (value != this._pPWOIssueDate)
                {
                    _pPWOIssueDate = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOEstTotManHour
        {
            get { return _pPWOEstTotManHour; }
            set
            {
                if (value != this._pPWOEstTotManHour)
                {
                    _pPWOEstTotManHour = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOActTotManHour
        {
            get { return _pPWOActTotManHour; }
            set
            {
                if (value != this._pPWOActTotManHour)
                {
                    _pPWOActTotManHour = value;
                }
            }
        }
        public String PPWOStatusDetail
        {
            get { return _pPWOStatusDetail; }
            set
            {
                if (value != this._pPWOStatusDetail)
                {
                    _pPWOStatusDetail = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOCompPct
        {
            get { return _pPWOCompPct; }
            set
            {
                if (value != this._pPWOCompPct)
                {
                    _pPWOCompPct = value;
                }
            }
        }
        public String PPWOStatusManhour
        {
            get { return _pPWOStatusManhour; }
            set
            {
                if (value != this._pPWOStatusManhour)
                {
                    _pPWOStatusManhour = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOTotWeight
        {
            get { return _pPWOTotWeight; }
            set
            {
                if (value != this._pPWOTotWeight)
                {
                    _pPWOTotWeight = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOActManHourPct
        {
            get { return _pPWOActManHourPct; }
            set
            {
                if (value != this._pPWOActManHourPct)
                {
                    _pPWOActManHourPct = value;
                }
            }
        }
        public String PPWOCostStatusCombo
        {
            get { return _pPWOCostStatusCombo; }
            set
            {
                if (value != this._pPWOCostStatusCombo)
                {
                    _pPWOCostStatusCombo = value;
                }
            }
        }
        public String PPWOSchedStatusCombo
        {
            get { return _pPWOSchedStatusCombo; }
            set
            {
                if (value != this._pPWOSchedStatusCombo)
                {
                    _pPWOSchedStatusCombo = value;
                }
            }
        }
        public int FK_PMProjectID
        {
            get { return _fK_PMProjectID; }
            set
            {
                if (value != this._fK_PMProjectID)
                {
                    _fK_PMProjectID = value;
                }
            }
        }
        public String PPWOCompleteApproveStatusCombo
        {
            get { return _pPWOCompleteApproveStatusCombo; }
            set
            {
                if (value != this._pPWOCompleteApproveStatusCombo)
                {
                    _pPWOCompleteApproveStatusCombo = value;
                }
            }
        }
        public int FK_HRWorkshopID
        {
            get { return _fK_HRWorkshopID; }
            set
            {
                if (value != this._fK_HRWorkshopID)
                {
                    _fK_HRWorkshopID = value;
                }
            }
        }
        public String PPWOSupervisorRemark
        {
            get { return _pPWOSupervisorRemark; }
            set
            {
                if (value != this._pPWOSupervisorRemark)
                {
                    _pPWOSupervisorRemark = value;
                }
            }
        }
        public String PPWOProductionRemark
        {
            get { return _pPWOProductionRemark; }
            set
            {
                if (value != this._pPWOProductionRemark)
                {
                    _pPWOProductionRemark = value;
                }
            }
        }
        public String PPWOCMRemark
        {
            get { return _pPWOCMRemark; }
            set
            {
                if (value != this._pPWOCMRemark)
                {
                    _pPWOCMRemark = value;
                }
            }
        }
        public String PPWORemark
        {
            get { return _pPWORemark; }
            set
            {
                if (value != this._pPWORemark)
                {
                    _pPWORemark = value;
                }
            }
        }
        public String PPWOPriorityStatusCombo
        {
            get { return _pPWOPriorityStatusCombo; }
            set
            {
                if (value != this._pPWOPriorityStatusCombo)
                {
                    _pPWOPriorityStatusCombo = value;
                }
            }
        }
        public String PPWOCompleteActionTypeCombo
        {
            get { return _pPWOCompleteActionTypeCombo; }
            set
            {
                if (value != this._pPWOCompleteActionTypeCombo)
                {
                    _pPWOCompleteActionTypeCombo = value;
                }
            }
        }
        public int PPWOCompleteActionRequest
        {
            get { return _pPWOCompleteActionRequest; }
            set
            {
                if (value != this._pPWOCompleteActionRequest)
                {
                    _pPWOCompleteActionRequest = value;
                }
            }
        }
        public int PPWOCompleteActionReject
        {
            get { return _pPWOCompleteActionReject; }
            set
            {
                if (value != this._pPWOCompleteActionReject)
                {
                    _pPWOCompleteActionReject = value;
                }
            }
        }
        public int PPWOAttachDocumentCount
        {
            get { return _pPWOAttachDocumentCount; }
            set
            {
                if (value != this._pPWOAttachDocumentCount)
                {
                    _pPWOAttachDocumentCount = value;
                }
            }
        }
        public int FK_HREmpRequestToID
        {
            get { return _fK_HREmpRequestToID; }
            set
            {
                if (value != this._fK_HREmpRequestToID)
                {
                    _fK_HREmpRequestToID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOEstWeightKg
        {
            get { return _pPWOEstWeightKg; }
            set
            {
                if (value != this._pPWOEstWeightKg)
                {
                    _pPWOEstWeightKg = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PPWOActWeightKg
        {
            get { return _pPWOActWeightKg; }
            set
            {
                if (value != this._pPWOActWeightKg)
                {
                    _pPWOActWeightKg = value;
                }
            }
        }
        public String PPWOPlanningApproveStatusCombo
        {
            get { return _pPWOPlanningApproveStatusCombo; }
            set
            {
                if (value != this._pPWOPlanningApproveStatusCombo)
                {
                    _pPWOPlanningApproveStatusCombo = value;
                }
            }
        }
        public String PPWOPlanningActionTypeCombo
        {
            get { return _pPWOPlanningActionTypeCombo; }
            set
            {
                if (value != this._pPWOPlanningActionTypeCombo)
                {
                    _pPWOPlanningActionTypeCombo = value;
                }
            }
        }
        public int FK_PPWOGroupID
        {
            get { return _fK_PPWOGroupID; }
            set
            {
                if (value != this._fK_PPWOGroupID)
                {
                    _fK_PPWOGroupID = value;
                }
            }
        }
        public int FK_PPProjectDiscID
        {
            get { return _fK_PPProjectDiscID; }
            set
            {
                if (value != this._fK_PPProjectDiscID)
                {
                    _fK_PPProjectDiscID = value;
                }
            }
        }
        public int FK_PPProjectFieldID
        {
            get { return _fK_PPProjectFieldID; }
            set
            {
                if (value != this._fK_PPProjectFieldID)
                {
                    _fK_PPProjectFieldID = value;
                }
            }
        }
        public int FK_PPWOParentID
        {
            get { return _fK_PPWOParentID; }
            set
            {
                if (value != this._fK_PPWOParentID)
                {
                    _fK_PPWOParentID = value;
                }
            }
        }
        public String PPWOChangeSourceCombo
        {
            get { return _pPWOChangeSourceCombo; }
            set
            {
                if (value != this._pPWOChangeSourceCombo)
                {
                    _pPWOChangeSourceCombo = value;
                }
            }
        }
        public int FK_ADUserSendID
        {
            get { return _fK_ADUserSendID; }
            set
            {
                if (value != this._fK_ADUserSendID)
                {
                    _fK_ADUserSendID = value;
                }
            }
        }
        public int FK_ADUserReceiveID
        {
            get { return _fK_ADUserReceiveID; }
            set
            {
                if (value != this._fK_ADUserReceiveID)
                {
                    _fK_ADUserReceiveID = value;
                }
            }
        }
        public int FK_PMChangeOrdID
        {
            get { return _fK_PMChangeOrdID; }
            set
            {
                if (value != this._fK_PMChangeOrdID)
                {
                    _fK_PMChangeOrdID = value;
                }
            }
        }
        public int FK_PMChangeTypeID
        {
            get { return _fK_PMChangeTypeID; }
            set
            {
                if (value != this._fK_PMChangeTypeID)
                {
                    _fK_PMChangeTypeID = value;
                }
            }
        }
        public String PPWOQCStatusCombo
        {
            get { return _pPWOQCStatusCombo; }
            set
            {
                if (value != this._pPWOQCStatusCombo)
                {
                    _pPWOQCStatusCombo = value;
                }
            }
        }
        public String PPWOAreaDesc
        {
            get { return _pPWOAreaDesc; }
            set
            {
                if (value != this._pPWOAreaDesc)
                {
                    _pPWOAreaDesc = value;
                }
            }
        }
        public String PPWOAreaDocNo
        {
            get { return _pPWOAreaDocNo; }
            set
            {
                if (value != this._pPWOAreaDocNo)
                {
                    _pPWOAreaDocNo = value;
                }
            }
        }
        public String PPWOAreaServerPath
        {
            get { return _pPWOAreaServerPath; }
            set
            {
                if (value != this._pPWOAreaServerPath)
                {
                    _pPWOAreaServerPath = value;
                }
            }
        }
        public String PPWOExecutorTypeCombo
        {
            get { return _pPWOExecutorTypeCombo; }
            set
            {
                if (value != this._pPWOExecutorTypeCombo)
                {
                    _pPWOExecutorTypeCombo = value;
                }
            }
        }
        public int FK_PPMPSID
        {
            get { return _fK_PPMPSID; }
            set
            {
                if (value != this._fK_PPMPSID)
                {
                    _fK_PPMPSID = value;
                }
            }
        }
        public String AAModule
        {
            get { return _aAModule; }
            set
            {
                if (value != this._aAModule)
                {
                    _aAModule = value;
                }
            }
        }
        public String PPWOTypeCombo
        {
            get { return _pPWOTypeCombo; }
            set
            {
                if (value != this._pPWOTypeCombo)
                {
                    _pPWOTypeCombo = value;
                }
            }
        }
        public int FK_BRBranchID
        {
            get { return _fK_BRBranchID; }
            set
            {
                if (value != this._fK_BRBranchID)
                {
                    _fK_BRBranchID = value;
                }
            }
        }
        public int FK_GLTranCfgID
        {
            get { return _fK_GLTranCfgID; }
            set
            {
                if (value != this._fK_GLTranCfgID)
                {
                    _fK_GLTranCfgID = value;
                }
            }
        }
        public String PPWOCStatusCombo
        {
            get { return _pPWOCStatusCombo; }
            set
            {
                if (value != this._pPWOCStatusCombo)
                {
                    _pPWOCStatusCombo = value;
                }
            }
        }
        public int FK_PPWORID
        {
            get { return _fK_PPWORID; }
            set
            {
                if (value != this._fK_PPWORID)
                {
                    _fK_PPWORID = value;
                }
            }
        }
        public int FK_PPRoutingID
        {
            get { return _fK_PPRoutingID; }
            set
            {
                if (value != this._fK_PPRoutingID)
                {
                    _fK_PPRoutingID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}