using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region PMProjectTaskDocuments
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: PMProjectTaskDocumentsInfo
    //Created Date: Thursday, 15 May 2025
    //-----------------------------------------------------------
    [Table("PMProjectTaskDocuments")]
    public class PMProjectTaskDocumentsInfo : BaseInfo
    {
        #region Variables
        protected int _pMProjectTaskDocumentID;
        protected Nullable<DateTime> _aACreatedDate;
        protected String _aACreatedUser = String.Empty;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected bool _aASelected = true;
        protected String _pMProjectTaskDocumentDesc = String.Empty;
        protected String _pMProjectTaskDocumentRemark = String.Empty;
        protected String _pMProjectTaskDocumentUser = String.Empty;
        protected DateTime _pMProjectTaskDocumentDate = DateTime.Now;
        protected String _pMProjectTaskDocumentDocNo = String.Empty;
        protected Nullable<DateTime> _pMProjectTaskDocumentDocDate;
        protected int _pMProjectTaskDocumentDocID;
        protected String _pMProjectTaskDocumentDocModule = String.Empty;
        protected String _pMProjectTaskDocumentDocTableName = String.Empty;
        protected int _fK_PMProjectTaskID;
        protected int _fK_ADUserID;

        #endregion
        #region Public properties
        [Key]
        public int PMProjectTaskDocumentID
        {
            get { return _pMProjectTaskDocumentID; }
            set
            {
                if (value != this._pMProjectTaskDocumentID)
                {
                    _pMProjectTaskDocumentID = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public String PMProjectTaskDocumentDesc
        {
            get { return _pMProjectTaskDocumentDesc; }
            set
            {
                if (value != this._pMProjectTaskDocumentDesc)
                {
                    _pMProjectTaskDocumentDesc = value;
                }
            }
        }
        public String PMProjectTaskDocumentRemark
        {
            get { return _pMProjectTaskDocumentRemark; }
            set
            {
                if (value != this._pMProjectTaskDocumentRemark)
                {
                    _pMProjectTaskDocumentRemark = value;
                }
            }
        }
        public String PMProjectTaskDocumentUser
        {
            get { return _pMProjectTaskDocumentUser; }
            set
            {
                if (value != this._pMProjectTaskDocumentUser)
                {
                    _pMProjectTaskDocumentUser = value;
                }
            }
        }
        public DateTime PMProjectTaskDocumentDate
        {
            get { return _pMProjectTaskDocumentDate; }
            set
            {
                if (value != this._pMProjectTaskDocumentDate)
                {
                    _pMProjectTaskDocumentDate = value;
                }
            }
        }
        public String PMProjectTaskDocumentDocNo
        {
            get { return _pMProjectTaskDocumentDocNo; }
            set
            {
                if (value != this._pMProjectTaskDocumentDocNo)
                {
                    _pMProjectTaskDocumentDocNo = value;
                }
            }
        }
        public Nullable<DateTime> PMProjectTaskDocumentDocDate
        {
            get { return _pMProjectTaskDocumentDocDate; }
            set
            {
                if (value != this._pMProjectTaskDocumentDocDate)
                {
                    _pMProjectTaskDocumentDocDate = value;
                }
            }
        }
        public int PMProjectTaskDocumentDocID
        {
            get { return _pMProjectTaskDocumentDocID; }
            set
            {
                if (value != this._pMProjectTaskDocumentDocID)
                {
                    _pMProjectTaskDocumentDocID = value;
                }
            }
        }
        public String PMProjectTaskDocumentDocModule
        {
            get { return _pMProjectTaskDocumentDocModule; }
            set
            {
                if (value != this._pMProjectTaskDocumentDocModule)
                {
                    _pMProjectTaskDocumentDocModule = value;
                }
            }
        }
        public String PMProjectTaskDocumentDocTableName
        {
            get { return _pMProjectTaskDocumentDocTableName; }
            set
            {
                if (value != this._pMProjectTaskDocumentDocTableName)
                {
                    _pMProjectTaskDocumentDocTableName = value;
                }
            }
        }
        public int FK_PMProjectTaskID
        {
            get { return _fK_PMProjectTaskID; }
            set
            {
                if (value != this._fK_PMProjectTaskID)
                {
                    _fK_PMProjectTaskID = value;
                }
            }
        }
        public int FK_ADUserID
        {
            get { return _fK_ADUserID; }
            set
            {
                if (value != this._fK_ADUserID)
                {
                    _fK_ADUserID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}