using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region PMProjectTaskComments
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: PMProjectTaskCommentsInfo
    //Created Date: Thursday, 15 May 2025
    //-----------------------------------------------------------
    [Table("PMProjectTaskComments")]
    public class PMProjectTaskCommentsInfo : BaseInfo
    {
        #region Variables
        protected int _pMProjectTaskCommentID;
        protected Nullable<DateTime> _aACreatedDate;
        protected String _aACreatedUser = String.Empty;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected bool _aASelected = true;
        protected String _pMProjectTaskCommentDesc = String.Empty;
        protected String _pMProjectTaskCommentRemark = String.Empty;
        protected String _pMProjectTaskCommentUser = String.Empty;
        protected DateTime _pMProjectTaskCommentDate = DateTime.Now;
        protected String _pMProjectTaskCommentServerPath = String.Empty;
        protected int _fK_PMProjectTaskID;
        protected int _fK_ADUserID;

        #endregion
        #region Public properties
        [Key]
        public int PMProjectTaskCommentID
        {
            get { return _pMProjectTaskCommentID; }
            set
            {
                if (value != this._pMProjectTaskCommentID)
                {
                    _pMProjectTaskCommentID = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public String PMProjectTaskCommentDesc
        {
            get { return _pMProjectTaskCommentDesc; }
            set
            {
                if (value != this._pMProjectTaskCommentDesc)
                {
                    _pMProjectTaskCommentDesc = value;
                }
            }
        }
        public String PMProjectTaskCommentRemark
        {
            get { return _pMProjectTaskCommentRemark; }
            set
            {
                if (value != this._pMProjectTaskCommentRemark)
                {
                    _pMProjectTaskCommentRemark = value;
                }
            }
        }
        public String PMProjectTaskCommentUser
        {
            get { return _pMProjectTaskCommentUser; }
            set
            {
                if (value != this._pMProjectTaskCommentUser)
                {
                    _pMProjectTaskCommentUser = value;
                }
            }
        }
        public DateTime PMProjectTaskCommentDate
        {
            get { return _pMProjectTaskCommentDate; }
            set
            {
                if (value != this._pMProjectTaskCommentDate)
                {
                    _pMProjectTaskCommentDate = value;
                }
            }
        }
        public String PMProjectTaskCommentServerPath
        {
            get { return _pMProjectTaskCommentServerPath; }
            set
            {
                if (value != this._pMProjectTaskCommentServerPath)
                {
                    _pMProjectTaskCommentServerPath = value;
                }
            }
        }
        public int FK_PMProjectTaskID
        {
            get { return _fK_PMProjectTaskID; }
            set
            {
                if (value != this._fK_PMProjectTaskID)
                {
                    _fK_PMProjectTaskID = value;
                }
            }
        }
        public int FK_ADUserID
        {
            get { return _fK_ADUserID; }
            set
            {
                if (value != this._fK_ADUserID)
                {
                    _fK_ADUserID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}