using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region PMProjects
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: PMProjectsInfo
    //Created Date: Thursday, 15 May 2025
    //-----------------------------------------------------------
    [Table("PMProjects")]
    public class PMProjectsInfo : BaseInfo
    {
        #region Variables
        protected int _pMProjectID;
        protected String _aAStatus = DefaultAAStatus;
        protected String _aACreatedUser = String.Empty;
        protected String _aAUpdatedUser = String.Empty;
        protected Nullable<DateTime> _aACreatedDate;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _pMProjectNo = String.Empty;
        protected String _pMProjectName = String.Empty;
        protected String _pMProjectDesc = String.Empty;
        protected String _pMProjectRemark = String.Empty;
        protected String _pMProjectInfo = String.Empty;
        protected bool _pMProjectActiveCheck = true;
        protected Nullable<DateTime> _pMProjectStartDate;
        protected DateTime _pMProjectDate = DateTime.Now;
        protected String _pMProjectOF01 = String.Empty;
        protected String _pMProjectOF02 = String.Empty;
        protected String _pMProjectOF03 = String.Empty;
        protected String _pMProjectOF04 = String.Empty;
        protected String _pMProjectOF05 = String.Empty;
        protected String _pMProjectOF06 = String.Empty;
        protected String _pMProjectOF07 = String.Empty;
        protected String _pMProjectOF08 = String.Empty;
        protected String _pMProjectOF09 = String.Empty;
        protected String _pMProjectOF10 = String.Empty;
        protected String _pMProjectOF11 = String.Empty;
        protected String _pMProjectOF12 = String.Empty;
        protected int _fK_ARCustomerID;
        protected int _fK_PMDocPrfID;
        protected int _fK_PMOfferID;
        protected String _pMProjectTypeCombo = String.Empty;
        protected String _pMProjectStatus = DefaultStatus;
        protected Nullable<DateTime> _pMProjectEstimatedStartDate;
        protected Nullable<DateTime> _pMProjectActualStartDate;
        protected Nullable<DateTime> _pMProjectEstimatedEndDate;
        protected Nullable<DateTime> _pMProjectActualEndDate;
        protected int _pMProjectEstimatedTotalDays;
        protected int _pMProjectActualTotalDays;
        protected int _pMProjectEstimatedTotalHours;
        protected int _pMProjectActualTotalHours;
        protected int _pMProjectEstimatedExtendDays;
        protected int _pMProjectActualExtendDays;
        protected int _pMProjectEstimatedExtendHours;
        protected int _pMProjectActualExtendHours;
        protected decimal _pMProjectEstimatedTotalCost;
        protected decimal _pMProjectActualTotalCost;
        protected int _fK_HREmployeeID;
        protected String _pMProjectOwnerName = String.Empty;
        protected String _pMProjectOwnerTel1 = String.Empty;
        protected String _pMProjectOwnerTel2 = String.Empty;
        protected String _pMProjectOwnerTel3 = String.Empty;
        protected String _pMProjectOwnerEmail = String.Empty;
        protected String _pMProjectOwnerFax = String.Empty;
        protected String _pMProjectOwnerAddressStreet = String.Empty;
        protected String _pMProjectOwnerAddressLine1 = String.Empty;
        protected String _pMProjectOwnerAddressLine2 = String.Empty;
        protected String _pMProjectOwnerAddressLine3 = String.Empty;
        protected String _pMProjectOwnerAddressCity = String.Empty;
        protected String _pMProjectOwnerAddressPostalCode = String.Empty;
        protected String _pMProjectOwnerAddressStateProvince = String.Empty;
        protected String _pMProjectOwnerAddressZipCode = String.Empty;
        protected String _pMProjectOwnerAddressCountry = String.Empty;
        protected decimal _pMProjectCapacity;
        protected decimal _pMProjectAper;
        protected decimal _pMProjectLiftH;
        protected bool _pMProjectApprovedCostPlanningCheck = true;
        protected bool _pMProjectApprovedOrgChartCheck = true;
        protected bool _aASelected = true;

        #endregion
        #region Public properties
        [Key]
        public int PMProjectID
        {
            get { return _pMProjectID; }
            set
            {
                if (value != this._pMProjectID)
                {
                    _pMProjectID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String PMProjectNo
        {
            get { return _pMProjectNo; }
            set
            {
                if (value != this._pMProjectNo)
                {
                    _pMProjectNo = value;
                }
            }
        }
        public String PMProjectName
        {
            get { return _pMProjectName; }
            set
            {
                if (value != this._pMProjectName)
                {
                    _pMProjectName = value;
                }
            }
        }
        public String PMProjectDesc
        {
            get { return _pMProjectDesc; }
            set
            {
                if (value != this._pMProjectDesc)
                {
                    _pMProjectDesc = value;
                }
            }
        }
        public String PMProjectRemark
        {
            get { return _pMProjectRemark; }
            set
            {
                if (value != this._pMProjectRemark)
                {
                    _pMProjectRemark = value;
                }
            }
        }
        public String PMProjectInfo
        {
            get { return _pMProjectInfo; }
            set
            {
                if (value != this._pMProjectInfo)
                {
                    _pMProjectInfo = value;
                }
            }
        }
        public bool PMProjectActiveCheck
        {
            get { return _pMProjectActiveCheck; }
            set
            {
                if (value != this._pMProjectActiveCheck)
                {
                    _pMProjectActiveCheck = value;
                }
            }
        }
        public Nullable<DateTime> PMProjectStartDate
        {
            get { return _pMProjectStartDate; }
            set
            {
                if (value != this._pMProjectStartDate)
                {
                    _pMProjectStartDate = value;
                }
            }
        }
        public DateTime PMProjectDate
        {
            get { return _pMProjectDate; }
            set
            {
                if (value != this._pMProjectDate)
                {
                    _pMProjectDate = value;
                }
            }
        }
        public String PMProjectOF01
        {
            get { return _pMProjectOF01; }
            set
            {
                if (value != this._pMProjectOF01)
                {
                    _pMProjectOF01 = value;
                }
            }
        }
        public String PMProjectOF02
        {
            get { return _pMProjectOF02; }
            set
            {
                if (value != this._pMProjectOF02)
                {
                    _pMProjectOF02 = value;
                }
            }
        }
        public String PMProjectOF03
        {
            get { return _pMProjectOF03; }
            set
            {
                if (value != this._pMProjectOF03)
                {
                    _pMProjectOF03 = value;
                }
            }
        }
        public String PMProjectOF04
        {
            get { return _pMProjectOF04; }
            set
            {
                if (value != this._pMProjectOF04)
                {
                    _pMProjectOF04 = value;
                }
            }
        }
        public String PMProjectOF05
        {
            get { return _pMProjectOF05; }
            set
            {
                if (value != this._pMProjectOF05)
                {
                    _pMProjectOF05 = value;
                }
            }
        }
        public String PMProjectOF06
        {
            get { return _pMProjectOF06; }
            set
            {
                if (value != this._pMProjectOF06)
                {
                    _pMProjectOF06 = value;
                }
            }
        }
        public String PMProjectOF07
        {
            get { return _pMProjectOF07; }
            set
            {
                if (value != this._pMProjectOF07)
                {
                    _pMProjectOF07 = value;
                }
            }
        }
        public String PMProjectOF08
        {
            get { return _pMProjectOF08; }
            set
            {
                if (value != this._pMProjectOF08)
                {
                    _pMProjectOF08 = value;
                }
            }
        }
        public String PMProjectOF09
        {
            get { return _pMProjectOF09; }
            set
            {
                if (value != this._pMProjectOF09)
                {
                    _pMProjectOF09 = value;
                }
            }
        }
        public String PMProjectOF10
        {
            get { return _pMProjectOF10; }
            set
            {
                if (value != this._pMProjectOF10)
                {
                    _pMProjectOF10 = value;
                }
            }
        }
        public String PMProjectOF11
        {
            get { return _pMProjectOF11; }
            set
            {
                if (value != this._pMProjectOF11)
                {
                    _pMProjectOF11 = value;
                }
            }
        }
        public String PMProjectOF12
        {
            get { return _pMProjectOF12; }
            set
            {
                if (value != this._pMProjectOF12)
                {
                    _pMProjectOF12 = value;
                }
            }
        }
        public int FK_ARCustomerID
        {
            get { return _fK_ARCustomerID; }
            set
            {
                if (value != this._fK_ARCustomerID)
                {
                    _fK_ARCustomerID = value;
                }
            }
        }
        public int FK_PMDocPrfID
        {
            get { return _fK_PMDocPrfID; }
            set
            {
                if (value != this._fK_PMDocPrfID)
                {
                    _fK_PMDocPrfID = value;
                }
            }
        }
        public int FK_PMOfferID
        {
            get { return _fK_PMOfferID; }
            set
            {
                if (value != this._fK_PMOfferID)
                {
                    _fK_PMOfferID = value;
                }
            }
        }
        public String PMProjectTypeCombo
        {
            get { return _pMProjectTypeCombo; }
            set
            {
                if (value != this._pMProjectTypeCombo)
                {
                    _pMProjectTypeCombo = value;
                }
            }
        }
        public String PMProjectStatus
        {
            get { return _pMProjectStatus; }
            set
            {
                if (value != this._pMProjectStatus)
                {
                    _pMProjectStatus = value;
                }
            }
        }
        public Nullable<DateTime> PMProjectEstimatedStartDate
        {
            get { return _pMProjectEstimatedStartDate; }
            set
            {
                if (value != this._pMProjectEstimatedStartDate)
                {
                    _pMProjectEstimatedStartDate = value;
                }
            }
        }
        public Nullable<DateTime> PMProjectActualStartDate
        {
            get { return _pMProjectActualStartDate; }
            set
            {
                if (value != this._pMProjectActualStartDate)
                {
                    _pMProjectActualStartDate = value;
                }
            }
        }
        public Nullable<DateTime> PMProjectEstimatedEndDate
        {
            get { return _pMProjectEstimatedEndDate; }
            set
            {
                if (value != this._pMProjectEstimatedEndDate)
                {
                    _pMProjectEstimatedEndDate = value;
                }
            }
        }
        public Nullable<DateTime> PMProjectActualEndDate
        {
            get { return _pMProjectActualEndDate; }
            set
            {
                if (value != this._pMProjectActualEndDate)
                {
                    _pMProjectActualEndDate = value;
                }
            }
        }
        public int PMProjectEstimatedTotalDays
        {
            get { return _pMProjectEstimatedTotalDays; }
            set
            {
                if (value != this._pMProjectEstimatedTotalDays)
                {
                    _pMProjectEstimatedTotalDays = value;
                }
            }
        }
        public int PMProjectActualTotalDays
        {
            get { return _pMProjectActualTotalDays; }
            set
            {
                if (value != this._pMProjectActualTotalDays)
                {
                    _pMProjectActualTotalDays = value;
                }
            }
        }
        public int PMProjectEstimatedTotalHours
        {
            get { return _pMProjectEstimatedTotalHours; }
            set
            {
                if (value != this._pMProjectEstimatedTotalHours)
                {
                    _pMProjectEstimatedTotalHours = value;
                }
            }
        }
        public int PMProjectActualTotalHours
        {
            get { return _pMProjectActualTotalHours; }
            set
            {
                if (value != this._pMProjectActualTotalHours)
                {
                    _pMProjectActualTotalHours = value;
                }
            }
        }
        public int PMProjectEstimatedExtendDays
        {
            get { return _pMProjectEstimatedExtendDays; }
            set
            {
                if (value != this._pMProjectEstimatedExtendDays)
                {
                    _pMProjectEstimatedExtendDays = value;
                }
            }
        }
        public int PMProjectActualExtendDays
        {
            get { return _pMProjectActualExtendDays; }
            set
            {
                if (value != this._pMProjectActualExtendDays)
                {
                    _pMProjectActualExtendDays = value;
                }
            }
        }
        public int PMProjectEstimatedExtendHours
        {
            get { return _pMProjectEstimatedExtendHours; }
            set
            {
                if (value != this._pMProjectEstimatedExtendHours)
                {
                    _pMProjectEstimatedExtendHours = value;
                }
            }
        }
        public int PMProjectActualExtendHours
        {
            get { return _pMProjectActualExtendHours; }
            set
            {
                if (value != this._pMProjectActualExtendHours)
                {
                    _pMProjectActualExtendHours = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PMProjectEstimatedTotalCost
        {
            get { return _pMProjectEstimatedTotalCost; }
            set
            {
                if (value != this._pMProjectEstimatedTotalCost)
                {
                    _pMProjectEstimatedTotalCost = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PMProjectActualTotalCost
        {
            get { return _pMProjectActualTotalCost; }
            set
            {
                if (value != this._pMProjectActualTotalCost)
                {
                    _pMProjectActualTotalCost = value;
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                }
            }
        }
        public String PMProjectOwnerName
        {
            get { return _pMProjectOwnerName; }
            set
            {
                if (value != this._pMProjectOwnerName)
                {
                    _pMProjectOwnerName = value;
                }
            }
        }
        public String PMProjectOwnerTel1
        {
            get { return _pMProjectOwnerTel1; }
            set
            {
                if (value != this._pMProjectOwnerTel1)
                {
                    _pMProjectOwnerTel1 = value;
                }
            }
        }
        public String PMProjectOwnerTel2
        {
            get { return _pMProjectOwnerTel2; }
            set
            {
                if (value != this._pMProjectOwnerTel2)
                {
                    _pMProjectOwnerTel2 = value;
                }
            }
        }
        public String PMProjectOwnerTel3
        {
            get { return _pMProjectOwnerTel3; }
            set
            {
                if (value != this._pMProjectOwnerTel3)
                {
                    _pMProjectOwnerTel3 = value;
                }
            }
        }
        public String PMProjectOwnerEmail
        {
            get { return _pMProjectOwnerEmail; }
            set
            {
                if (value != this._pMProjectOwnerEmail)
                {
                    _pMProjectOwnerEmail = value;
                }
            }
        }
        public String PMProjectOwnerFax
        {
            get { return _pMProjectOwnerFax; }
            set
            {
                if (value != this._pMProjectOwnerFax)
                {
                    _pMProjectOwnerFax = value;
                }
            }
        }
        public String PMProjectOwnerAddressStreet
        {
            get { return _pMProjectOwnerAddressStreet; }
            set
            {
                if (value != this._pMProjectOwnerAddressStreet)
                {
                    _pMProjectOwnerAddressStreet = value;
                }
            }
        }
        public String PMProjectOwnerAddressLine1
        {
            get { return _pMProjectOwnerAddressLine1; }
            set
            {
                if (value != this._pMProjectOwnerAddressLine1)
                {
                    _pMProjectOwnerAddressLine1 = value;
                }
            }
        }
        public String PMProjectOwnerAddressLine2
        {
            get { return _pMProjectOwnerAddressLine2; }
            set
            {
                if (value != this._pMProjectOwnerAddressLine2)
                {
                    _pMProjectOwnerAddressLine2 = value;
                }
            }
        }
        public String PMProjectOwnerAddressLine3
        {
            get { return _pMProjectOwnerAddressLine3; }
            set
            {
                if (value != this._pMProjectOwnerAddressLine3)
                {
                    _pMProjectOwnerAddressLine3 = value;
                }
            }
        }
        public String PMProjectOwnerAddressCity
        {
            get { return _pMProjectOwnerAddressCity; }
            set
            {
                if (value != this._pMProjectOwnerAddressCity)
                {
                    _pMProjectOwnerAddressCity = value;
                }
            }
        }
        public String PMProjectOwnerAddressPostalCode
        {
            get { return _pMProjectOwnerAddressPostalCode; }
            set
            {
                if (value != this._pMProjectOwnerAddressPostalCode)
                {
                    _pMProjectOwnerAddressPostalCode = value;
                }
            }
        }
        public String PMProjectOwnerAddressStateProvince
        {
            get { return _pMProjectOwnerAddressStateProvince; }
            set
            {
                if (value != this._pMProjectOwnerAddressStateProvince)
                {
                    _pMProjectOwnerAddressStateProvince = value;
                }
            }
        }
        public String PMProjectOwnerAddressZipCode
        {
            get { return _pMProjectOwnerAddressZipCode; }
            set
            {
                if (value != this._pMProjectOwnerAddressZipCode)
                {
                    _pMProjectOwnerAddressZipCode = value;
                }
            }
        }
        public String PMProjectOwnerAddressCountry
        {
            get { return _pMProjectOwnerAddressCountry; }
            set
            {
                if (value != this._pMProjectOwnerAddressCountry)
                {
                    _pMProjectOwnerAddressCountry = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PMProjectCapacity
        {
            get { return _pMProjectCapacity; }
            set
            {
                if (value != this._pMProjectCapacity)
                {
                    _pMProjectCapacity = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PMProjectAper
        {
            get { return _pMProjectAper; }
            set
            {
                if (value != this._pMProjectAper)
                {
                    _pMProjectAper = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal PMProjectLiftH
        {
            get { return _pMProjectLiftH; }
            set
            {
                if (value != this._pMProjectLiftH)
                {
                    _pMProjectLiftH = value;
                }
            }
        }
        public bool PMProjectApprovedCostPlanningCheck
        {
            get { return _pMProjectApprovedCostPlanningCheck; }
            set
            {
                if (value != this._pMProjectApprovedCostPlanningCheck)
                {
                    _pMProjectApprovedCostPlanningCheck = value;
                }
            }
        }
        public bool PMProjectApprovedOrgChartCheck
        {
            get { return _pMProjectApprovedOrgChartCheck; }
            set
            {
                if (value != this._pMProjectApprovedOrgChartCheck)
                {
                    _pMProjectApprovedOrgChartCheck = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }

        #endregion
    }
    #endregion
}