 using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region APPOSchPmts
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: APPOSchPmtsInfo
    //Created Date: Thursday, 05 Dec 2024
    //-----------------------------------------------------------
    [Table("APPOSchPmts")]
    public class APPOSchPmtsInfo : BaseInfo
    {
        #region Variables
        protected int _aPPOSchPmtID;
        protected Nullable<DateTime> _aACreatedDate;
        protected String _aACreatedUser = String.Empty;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected bool _aASelected = true;
        protected int _fK_APPOID;
        protected int _fK_ICProductID;
        protected String _aPPOSchPmtNo = String.Empty;
        protected String _aPPOSchPmtDesc = String.Empty;
        protected decimal _aPPOSchPmtPct;
        protected decimal _aPPOSchPmtItemPrice;
        protected decimal _aPPOSchPmtItemTxAmt;
        protected decimal _aPPOSchPmtItemDiscAmt;
        protected decimal _aPPOSchPmtItemAmtTot;
        protected decimal _aPPOSchPmtAmtTot;
        protected decimal _aPPOSchPmtRAmtTot;
        protected Nullable<DateTime> _aPPOSchPmtEstDate;
        protected String _aPPOSchPmtStatus = DefaultStatus;
        protected Nullable<DateTime> _aPPOSchPmtLastDate;
        protected Nullable<DateTime> _aPPOSchPmtCompleteDate;
        protected decimal _aPPOSchPmtReqAmtTot;

        #endregion
        #region Public properties
        [Key]
        public int APPOSchPmtID
        {
            get { return _aPPOSchPmtID; }
            set
            {
                if (value != this._aPPOSchPmtID)
                {
                    _aPPOSchPmtID = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public int FK_APPOID
        {
            get { return _fK_APPOID; }
            set
            {
                if (value != this._fK_APPOID)
                {
                    _fK_APPOID = value;
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                }
            }
        }
        public String APPOSchPmtNo
        {
            get { return _aPPOSchPmtNo; }
            set
            {
                if (value != this._aPPOSchPmtNo)
                {
                    _aPPOSchPmtNo = value;
                }
            }
        }
        public String APPOSchPmtDesc
        {
            get { return _aPPOSchPmtDesc; }
            set
            {
                if (value != this._aPPOSchPmtDesc)
                {
                    _aPPOSchPmtDesc = value;
                }
            }
        }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal APPOSchPmtPct
        {
            get { return _aPPOSchPmtPct; }
            set
            {
                if (value != this._aPPOSchPmtPct)
                {
                    _aPPOSchPmtPct = value;
                }
            }
        }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal APPOSchPmtItemPrice
        {
            get { return _aPPOSchPmtItemPrice; }
            set
            {
                if (value != this._aPPOSchPmtItemPrice)
                {
                    _aPPOSchPmtItemPrice = value;
                }
            }
        }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal APPOSchPmtItemTxAmt
        {
            get { return _aPPOSchPmtItemTxAmt; }
            set
            {
                if (value != this._aPPOSchPmtItemTxAmt)
                {
                    _aPPOSchPmtItemTxAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal APPOSchPmtItemDiscAmt
        {
            get { return _aPPOSchPmtItemDiscAmt; }
            set
            {
                if (value != this._aPPOSchPmtItemDiscAmt)
                {
                    _aPPOSchPmtItemDiscAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal APPOSchPmtItemAmtTot
        {
            get { return _aPPOSchPmtItemAmtTot; }
            set
            {
                if (value != this._aPPOSchPmtItemAmtTot)
                {
                    _aPPOSchPmtItemAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal APPOSchPmtAmtTot
        {
            get { return _aPPOSchPmtAmtTot; }
            set
            {
                if (value != this._aPPOSchPmtAmtTot)
                {
                    _aPPOSchPmtAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal APPOSchPmtRAmtTot
        {
            get { return _aPPOSchPmtRAmtTot; }
            set
            {
                if (value != this._aPPOSchPmtRAmtTot)
                {
                    _aPPOSchPmtRAmtTot = value;
                }
            }
        }
        public Nullable<DateTime> APPOSchPmtEstDate
        {
            get { return _aPPOSchPmtEstDate; }
            set
            {
                if (value != this._aPPOSchPmtEstDate)
                {
                    _aPPOSchPmtEstDate = value;
                }
            }
        }
        public String APPOSchPmtStatus
        {
            get { return _aPPOSchPmtStatus; }
            set
            {
                if (value != this._aPPOSchPmtStatus)
                {
                    _aPPOSchPmtStatus = value;
                }
            }
        }
        public Nullable<DateTime> APPOSchPmtLastDate
        {
            get { return _aPPOSchPmtLastDate; }
            set
            {
                if (value != this._aPPOSchPmtLastDate)
                {
                    _aPPOSchPmtLastDate = value;
                }
            }
        }
        public Nullable<DateTime> APPOSchPmtCompleteDate
        {
            get { return _aPPOSchPmtCompleteDate; }
            set
            {
                if (value != this._aPPOSchPmtCompleteDate)
                {
                    _aPPOSchPmtCompleteDate = value;
                }
            }
        }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal APPOSchPmtReqAmtTot
        {
            get { return _aPPOSchPmtReqAmtTot; }
            set
            {
                if (value != this._aPPOSchPmtReqAmtTot)
                {
                    _aPPOSchPmtReqAmtTot = value;
                }
            }
        }

        #endregion
    }
    #endregion
}