using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region ADAlertConfigs
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: ADAlertConfigsInfo
    //Created Date: Friday, 23 May 2025
    //-----------------------------------------------------------
    [Table("ADAlertConfigs")]
    public class ADAlertConfigsInfo : BaseInfo
    {
        #region Variables
        protected int _aDAlertConfigID;
        protected String _aDAlertConfigName = String.Empty;
        protected bool _activeCheck = true;
        protected String _toUserQuery = String.Empty;
        protected int _fK_ADMessageTypeID;
        protected String _messageTemplate = String.Empty;
        protected String _aACreatedUser = String.Empty;
        protected String _aDAlertConfigDesc = String.Empty;
        protected String _fromUserQuery = String.Empty;
        protected String _aDAlertConfigFireOnActionCombo = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected String _aAUpdatedUser = String.Empty;
        protected bool _aASelected = true;
        protected String _fromUser = String.Empty;
        protected String _toUser = String.Empty;
        protected String _aDAlertConfigSchedulerTypeCombo = String.Empty;
        protected Nullable<DateTime> _aACreatedDate;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _aDAlertConfigNo = String.Empty;
        protected String _docType = String.Empty;
        protected Nullable<DateTime> _schedulerTime;
        protected String _subjectTemplate = String.Empty;

        #endregion
        #region Public properties
        [Key]
        public int ADAlertConfigID
        {
            get { return _aDAlertConfigID; }
            set
            {
                if (value != this._aDAlertConfigID)
                {
                    _aDAlertConfigID = value;
                }
            }
        }
        public String ADAlertConfigName
        {
            get { return _aDAlertConfigName; }
            set
            {
                if (value != this._aDAlertConfigName)
                {
                    _aDAlertConfigName = value;
                }
            }
        }
        public bool ActiveCheck
        {
            get { return _activeCheck; }
            set
            {
                if (value != this._activeCheck)
                {
                    _activeCheck = value;
                }
            }
        }
        public String ToUserQuery
        {
            get { return _toUserQuery; }
            set
            {
                if (value != this._toUserQuery)
                {
                    _toUserQuery = value;
                }
            }
        }
        public int FK_ADMessageTypeID
        {
            get { return _fK_ADMessageTypeID; }
            set
            {
                if (value != this._fK_ADMessageTypeID)
                {
                    _fK_ADMessageTypeID = value;
                }
            }
        }
        public String MessageTemplate
        {
            get { return _messageTemplate; }
            set
            {
                if (value != this._messageTemplate)
                {
                    _messageTemplate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public String ADAlertConfigDesc
        {
            get { return _aDAlertConfigDesc; }
            set
            {
                if (value != this._aDAlertConfigDesc)
                {
                    _aDAlertConfigDesc = value;
                }
            }
        }
        public String FromUserQuery
        {
            get { return _fromUserQuery; }
            set
            {
                if (value != this._fromUserQuery)
                {
                    _fromUserQuery = value;
                }
            }
        }
        public String ADAlertConfigFireOnActionCombo
        {
            get { return _aDAlertConfigFireOnActionCombo; }
            set
            {
                if (value != this._aDAlertConfigFireOnActionCombo)
                {
                    _aDAlertConfigFireOnActionCombo = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public String FromUser
        {
            get { return _fromUser; }
            set
            {
                if (value != this._fromUser)
                {
                    _fromUser = value;
                }
            }
        }
        public String ToUser
        {
            get { return _toUser; }
            set
            {
                if (value != this._toUser)
                {
                    _toUser = value;
                }
            }
        }
        public String ADAlertConfigSchedulerTypeCombo
        {
            get { return _aDAlertConfigSchedulerTypeCombo; }
            set
            {
                if (value != this._aDAlertConfigSchedulerTypeCombo)
                {
                    _aDAlertConfigSchedulerTypeCombo = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String ADAlertConfigNo
        {
            get { return _aDAlertConfigNo; }
            set
            {
                if (value != this._aDAlertConfigNo)
                {
                    _aDAlertConfigNo = value;
                }
            }
        }
        public String DocType
        {
            get { return _docType; }
            set
            {
                if (value != this._docType)
                {
                    _docType = value;
                }
            }
        }
        public Nullable<DateTime> SchedulerTime
        {
            get { return _schedulerTime; }
            set
            {
                if (value != this._schedulerTime)
                {
                    _schedulerTime = value;
                }
            }
        }
        public String SubjectTemplate
        {
            get { return _subjectTemplate; }
            set
            {
                if (value != this._subjectTemplate)
                {
                    _subjectTemplate = value;
                }
            }
        }

        #endregion
    }
    #endregion
}