using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region ADAttachmentDocs
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.77)
    //Class: ADAttachmentDocsInfo
    //Created Date: Monday, 09 Mar 2026
    //-----------------------------------------------------------
    [Table("ADAttachmentDocs")]
    public class ADAttachmentDocsInfo : BaseInfo
    {
        #region Variables
        protected int _aDAttachmentDocID;
        protected DateTime _aACreatedDate = DateTime.Now;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.Now;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected bool _aASelected = true;
        protected String _aDAttachmentDocNo = String.Empty;
        protected String _aDAttachmentDocDesc = String.Empty;
        protected String _aDAttachmentDocUser = String.Empty;
        protected DateTime _aDAttachmentDocDate = DateTime.Now;
        protected String _aDAttachmentDocServerPath = String.Empty;
        protected int _docID;
        protected String _aAModule = String.Empty;
        protected int _fK_ADUserID;
        protected String _aDAttachmentDocName = String.Empty;
        protected String _aDAttachmentDocServerFileName = String.Empty;
        protected String _aDAttachmentDocFileName = String.Empty;
        protected String _aDAttachmentDocClientPath = String.Empty;

        #endregion
        #region Public properties
        [Key]
        public int ADAttachmentDocID
        {
            get { return _aDAttachmentDocID; }
            set
            {
                if (value != this._aDAttachmentDocID)
                {
                    _aDAttachmentDocID = value;
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public String ADAttachmentDocNo
        {
            get { return _aDAttachmentDocNo; }
            set
            {
                if (value != this._aDAttachmentDocNo)
                {
                    _aDAttachmentDocNo = value;
                }
            }
        }
        public String ADAttachmentDocDesc
        {
            get { return _aDAttachmentDocDesc; }
            set
            {
                if (value != this._aDAttachmentDocDesc)
                {
                    _aDAttachmentDocDesc = value;
                }
            }
        }
        public String ADAttachmentDocUser
        {
            get { return _aDAttachmentDocUser; }
            set
            {
                if (value != this._aDAttachmentDocUser)
                {
                    _aDAttachmentDocUser = value;
                }
            }
        }
        public DateTime ADAttachmentDocDate
        {
            get { return _aDAttachmentDocDate; }
            set
            {
                if (value != this._aDAttachmentDocDate)
                {
                    _aDAttachmentDocDate = value;
                }
            }
        }
        public String ADAttachmentDocServerPath
        {
            get { return _aDAttachmentDocServerPath; }
            set
            {
                if (value != this._aDAttachmentDocServerPath)
                {
                    _aDAttachmentDocServerPath = value;
                }
            }
        }
        public int DocID
        {
            get { return _docID; }
            set
            {
                if (value != this._docID)
                {
                    _docID = value;
                }
            }
        }
        public String AAModule
        {
            get { return _aAModule; }
            set
            {
                if (value != this._aAModule)
                {
                    _aAModule = value;
                }
            }
        }
        public int FK_ADUserID
        {
            get { return _fK_ADUserID; }
            set
            {
                if (value != this._fK_ADUserID)
                {
                    _fK_ADUserID = value;
                }
            }
        }
        public String ADAttachmentDocName
        {
            get { return _aDAttachmentDocName; }
            set
            {
                if (value != this._aDAttachmentDocName)
                {
                    _aDAttachmentDocName = value;
                }
            }
        }
        public String ADAttachmentDocServerFileName
        {
            get { return _aDAttachmentDocServerFileName; }
            set
            {
                if (value != this._aDAttachmentDocServerFileName)
                {
                    _aDAttachmentDocServerFileName = value;
                }
            }
        }
        public String ADAttachmentDocFileName
        {
            get { return _aDAttachmentDocFileName; }
            set
            {
                if (value != this._aDAttachmentDocFileName)
                {
                    _aDAttachmentDocFileName = value;
                }
            }
        }
        public String ADAttachmentDocClientPath
        {
            get { return _aDAttachmentDocClientPath; }
            set
            {
                if (value != this._aDAttachmentDocClientPath)
                {
                    _aDAttachmentDocClientPath = value;
                }
            }
        }

        #endregion
    }
    #endregion
}