using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region ADMessageTypes
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: ADMessageTypesInfo
    //Created Date: Monday, 26 May 2025
    //-----------------------------------------------------------
    [Table("ADMessageTypes")]
    public class ADMessageTypesInfo : BaseInfo
    {
        #region Variables
        protected int _aDMessageTypeID;
        protected String _aAStatus = DefaultAAStatus;
        protected String _aDMessageTypeNo = String.Empty;
        protected String _aDMessageTypeName = String.Empty;
        protected String _aDMessageTypeDesc = String.Empty;
        protected bool _aASelected = true;

        #endregion
        #region Public properties
        [Key]
        public int ADMessageTypeID
        {
            get { return _aDMessageTypeID; }
            set
            {
                if (value != this._aDMessageTypeID)
                {
                    _aDMessageTypeID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public String ADMessageTypeNo
        {
            get { return _aDMessageTypeNo; }
            set
            {
                if (value != this._aDMessageTypeNo)
                {
                    _aDMessageTypeNo = value;
                }
            }
        }
        public String ADMessageTypeName
        {
            get { return _aDMessageTypeName; }
            set
            {
                if (value != this._aDMessageTypeName)
                {
                    _aDMessageTypeName = value;
                }
            }
        }
        public String ADMessageTypeDesc
        {
            get { return _aDMessageTypeDesc; }
            set
            {
                if (value != this._aDMessageTypeDesc)
                {
                    _aDMessageTypeDesc = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }

        #endregion
    }
    #endregion
}