using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region ARCAs
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: ARCAsInfo
    //Created Date: Friday, 13 Jun 2025
    //-----------------------------------------------------------
    [Table("ARCAs")]
    public class ARCAsInfo : BaseInfo
    {
        #region Variables
        protected int _aRCAID;
        protected String _aRCANo = String.Empty;
        protected String _aRCAName = String.Empty;
        protected String _aRCADesc = String.Empty;
        protected Nullable<DateTime> _aACreatedDate;
        protected String _aACreatedUser = String.Empty;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ARCAFormulaID;
        protected Nullable<DateTime> _aRCADate;
        protected Nullable<DateTime> _aRCAFromDate;
        protected Nullable<DateTime> _aRCAToDate;

        #endregion
        #region Public properties
        [Key]
        public int ARCAID
        {
            get { return _aRCAID; }
            set
            {
                if (value != this._aRCAID)
                {
                    _aRCAID = value;
                }
            }
        }
        public String ARCANo
        {
            get { return _aRCANo; }
            set
            {
                if (value != this._aRCANo)
                {
                    _aRCANo = value;
                }
            }
        }
        public String ARCAName
        {
            get { return _aRCAName; }
            set
            {
                if (value != this._aRCAName)
                {
                    _aRCAName = value;
                }
            }
        }
        public String ARCADesc
        {
            get { return _aRCADesc; }
            set
            {
                if (value != this._aRCADesc)
                {
                    _aRCADesc = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public int FK_ARCAFormulaID
        {
            get { return _fK_ARCAFormulaID; }
            set
            {
                if (value != this._fK_ARCAFormulaID)
                {
                    _fK_ARCAFormulaID = value;
                }
            }
        }
        public Nullable<DateTime> ARCADate
        {
            get { return _aRCADate; }
            set
            {
                if (value != this._aRCADate)
                {
                    _aRCADate = value;
                }
            }
        }
        public Nullable<DateTime> ARCAFromDate
        {
            get { return _aRCAFromDate; }
            set
            {
                if (value != this._aRCAFromDate)
                {
                    _aRCAFromDate = value;
                }
            }
        }
        public Nullable<DateTime> ARCAToDate
        {
            get { return _aRCAToDate; }
            set
            {
                if (value != this._aRCAToDate)
                {
                    _aRCAToDate = value;
                }
            }
        }

        #endregion
    }
    #endregion
}