using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region ARQuotItemSOItems
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: ARQuotItemSOItemsInfo
    //Created Date: Thursday, 12 Jun 2025
    //-----------------------------------------------------------
    [Table("ARQuotItemSOItems")]
    public class ARQuotItemSOItemsInfo : BaseInfo
    {
        #region Variables
        protected int _aRQuotItemSOItemID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ARQuotItemID;
        protected int _fK_ARSOItemID;

        #endregion
        #region Public properties
        [Key]
        public int ARQuotItemSOItemID
        {
            get { return _aRQuotItemSOItemID; }
            set
            {
                if (value != this._aRQuotItemSOItemID)
                {
                    _aRQuotItemSOItemID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public int FK_ARQuotItemID
        {
            get { return _fK_ARQuotItemID; }
            set
            {
                if (value != this._fK_ARQuotItemID)
                {
                    _fK_ARQuotItemID = value;
                }
            }
        }
        public int FK_ARSOItemID
        {
            get { return _fK_ARSOItemID; }
            set
            {
                if (value != this._fK_ARSOItemID)
                {
                    _fK_ARSOItemID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}