using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region ARQuotSOs
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.77)
    //Class: ARQuotSOsInfo
    //Created Date: Monday, 02 Feb 2026
    //-----------------------------------------------------------
    [Table("ARQuotSOs")]
    public class ARQuotSOsInfo : BaseInfo
    {
        #region Variables
        protected int _aRQuotSOID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ARQuotID;
        protected int _fK_ARSOID;

        #endregion
        #region Public properties
        [Key]
        public int ARQuotSOID
        {
            get { return _aRQuotSOID; }
            set
            {
                if (value != this._aRQuotSOID)
                {
                    _aRQuotSOID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public int FK_ARQuotID
        {
            get { return _fK_ARQuotID; }
            set
            {
                if (value != this._fK_ARQuotID)
                {
                    _fK_ARQuotID = value;
                }
            }
        }
        public int FK_ARSOID
        {
            get { return _fK_ARSOID; }
            set
            {
                if (value != this._fK_ARSOID)
                {
                    _fK_ARSOID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}