using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace gmc_api.Entities
{
    #region SaleReturnItems
    //-----------------------------------------------------------
    //Generated By: Expert Studio
    //Class:CreditNoteItemsEntity
    //Created Date:Saturday, March 12, 2011
    //-----------------------------------------------------------
    [Table("ARSaleReturnItems")]
    public partial class SaleReturnItemsEntity : BaseInfo
    {
        #region Variables
        protected int _aRSaleReturnItemID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ARSaleReturnID;
        protected int _fK_ICProductID;
        protected int _fK_ICStockID;
        protected int _fK_ICStockSlotID;
        protected int _fK_ICProductTypeID;
        protected int _fK_ARPriceListID;
        protected int _fK_TXTaxCodeID;
        protected int _fK_ARInvoiceID;
        protected String _aRSaleReturnItemSerialNo = String.Empty;
        protected bool _aRSaleReturnItemIsStkItm = true;
        protected String _aRSaleReturnItemTypeCombo = String.Empty;
        protected String _aRSaleReturnItemDesc = String.Empty;
        protected decimal _aRSaleReturnItemFact;
        protected String _aRSalePriceCombo = String.Empty;
        protected decimal _aRSaleReturnItemUnitPrice;
        protected decimal _aRSaleReturnItemUnitCost;
        protected decimal _aRSaleReturnItemDiscPct;
        protected decimal _aRSaleReturnItemTxPct;
        protected decimal _aRSaleReturnItemQty;
        protected decimal _aRSaleReturnItemStkQty;
        protected decimal _aRSaleReturnItemRQty;
        protected decimal _aRSaleReturnItemShpRQty;
        protected decimal _aRSaleReturnItemRStkQty;
        protected decimal _aRSaleReturnItemPrice;
        protected String _aRSaleReturnItemComment = String.Empty;
        protected decimal _aRSaleReturnItemUnitVol;
        protected decimal _aRSaleReturnItemUnitWeight;
        protected decimal _aRSaleReturnItemTxAmt;
        protected decimal _aRSaleReturnItemDiscAmt;
        protected decimal _aRSaleReturnItemNetAmt;
        protected decimal _aRSaleReturnItemAmtTot;
        protected decimal _aRSaleReturnItemCostTot;
        protected String _aRSaleReturnItemStatusCombo = DefaultStatus;
        protected decimal _aRSaleReturnItemAmt;
        protected decimal _aRSaleReturnItemCAmt;
        protected bool _aASelected = true;
        protected int _fK_GLDebitAccountID;
        protected int _fK_GLCreditAccountID;
        protected int _fK_GLDebitVATAccountID;
        protected int _fK_GLCreditVATAccountID;
        protected decimal _aRSaleReturnItemFUnitPrice;
        protected decimal _aRSaleReturnItemFPrice;
        protected decimal _aRSaleReturnItemFTxAmt;
        protected decimal _aRSaleReturnItemFNetAmt;
        protected decimal _aRSaleReturnItemFAmtTot;
        protected decimal _aRSaleReturnItemFImpTxAmt;
        protected decimal _aRSaleReturnItemFDiscAmt;
        protected decimal _aRSaleReturnCreditNoteRQty;
        protected decimal _aRSaleReturnShipmentRQty;
        protected decimal _aRSaleReturnReceiptRQty;
        protected String _aRSaleReturnCreditNoteStatusCombo = DefaultStatus;
        protected String _aRSaleReturnShipmentStatusCombo = DefaultStatus;
        protected String _aRSaleReturnReceiptStatusCombo = DefaultStatus;
        protected bool _aRSaleReturnItemIsAvgCost = true;
        protected int _fK_ICUOMID;
        protected int _fK_ICStkUOMID;
        protected int _fK_ICWeightUOMID;
        protected int _fK_ICVolumeUOMID;
        protected decimal _aRSaleReturnItemWTot;
        protected decimal _aRSaleReturnItemVTot;
        protected String _gLTOF01Combo = String.Empty;
        protected String _gLTOF02Combo = String.Empty;
        protected String _gLTOF03Combo = String.Empty;
        protected String _gLTOF04Combo = String.Empty;
        protected String _gLTOF05Combo = String.Empty;
        protected String _gLTOF06Combo = String.Empty;
        protected String _gLTOF07Combo = String.Empty;
        protected String _gLTOF08Combo = String.Empty;
        protected String _gLTOF09Combo = String.Empty;
        protected String _gLTOF10Combo = String.Empty;
        protected decimal _aRSaleReturnItemExcQty;
        protected decimal _aRSaleReturnItemOrgQty;
        protected int _fK_ICOrgUOMID;
        protected String _gLTOF11Combo = String.Empty;
        protected String _gLTOF12Combo = String.Empty;
        protected String _gLTOF13Combo = String.Empty;
        protected String _gLTOF14Combo = String.Empty;
        protected String _gLTOF15Combo = String.Empty;
        protected int _fK_ARCampaignID;
        protected decimal _aRSaleReturnAPCreditNoteRQty;
        protected decimal _aRSaleReturnItemAdjStkQty;
        protected decimal _aRSaleReturnItemAdjUnitPricePct01;
        protected decimal _aRSaleReturnItemAdjUnitPricePct02;
        protected decimal _aRSaleReturnItemAdjUnitPricePct03;
        protected decimal _aRSaleReturnItemAdjUnitPricePct04;
        protected decimal _aRSaleReturnItemAdjUnitPricePct05;
        protected decimal _aRSaleReturnItemAdjDiscPct01;
        protected decimal _aRSaleReturnItemAdjDiscPct02;
        protected decimal _aRSaleReturnItemAdjDiscPct03;
        protected decimal _aRSaleReturnItemAdjDiscPct04;
        protected decimal _aRSaleReturnItemAdjDiscPct05;
        protected decimal _aRSaleReturnItemAdjDiscFAmt01;
        protected decimal _aRSaleReturnItemAdjDiscFAmt02;
        protected decimal _aRSaleReturnItemAdjDiscFAmt03;
        protected decimal _aRSaleReturnItemAdjDiscFAmt04;
        protected decimal _aRSaleReturnItemAdjDiscFAmt05;
        protected decimal _aRSaleReturnItemAdjDiscAmt01;
        protected decimal _aRSaleReturnItemAdjDiscAmt02;
        protected decimal _aRSaleReturnItemAdjDiscAmt03;
        protected decimal _aRSaleReturnItemAdjDiscAmt04;
        protected decimal _aRSaleReturnItemAdjDiscAmt05;
        protected decimal _aRSaleReturnItemNetAmtTot;
        protected decimal _aRSaleReturnItemFNetAmtTot;
        protected decimal _aRSaleReturnItemDiscAmtTot;
        protected decimal _aRSaleReturnItemFDiscAmtTot;
        protected String _aRSaleReturnItemLotNo = String.Empty;
        protected decimal _aRSaleReturnItemOrgFUnitPrice;
        protected int _fK_ARComplainID;
        protected String _aRSaleReturnItemPOF01Combo = String.Empty;
        protected String _aRSaleReturnItemPOF02Combo = String.Empty;
        protected String _aRSaleReturnItemPOF03Combo = String.Empty;
        protected String _aRSaleReturnItemPOF04Combo = String.Empty;
        protected String _aRSaleReturnItemPOF05Combo = String.Empty;
        #endregion

        #region Public properties
        public int ARSaleReturnItemID
        {
            get { return _aRSaleReturnItemID; }
            set
            {
                if (value != this._aRSaleReturnItemID)
                {
                    _aRSaleReturnItemID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public int FK_ARSaleReturnID
        {
            get { return _fK_ARSaleReturnID; }
            set
            {
                if (value != this._fK_ARSaleReturnID)
                {
                    _fK_ARSaleReturnID = value;
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                }
            }
        }
        public int FK_ICStockID
        {
            get { return _fK_ICStockID; }
            set
            {
                if (value != this._fK_ICStockID)
                {
                    _fK_ICStockID = value;
                }
            }
        }
        public int FK_ICStockSlotID
        {
            get { return _fK_ICStockSlotID; }
            set
            {
                if (value != this._fK_ICStockSlotID)
                {
                    _fK_ICStockSlotID = value;
                }
            }
        }
        public int FK_ICProductTypeID
        {
            get { return _fK_ICProductTypeID; }
            set
            {
                if (value != this._fK_ICProductTypeID)
                {
                    _fK_ICProductTypeID = value;
                }
            }
        }
        public int FK_ARPriceListID
        {
            get { return _fK_ARPriceListID; }
            set
            {
                if (value != this._fK_ARPriceListID)
                {
                    _fK_ARPriceListID = value;
                }
            }
        }
        public int FK_TXTaxCodeID
        {
            get { return _fK_TXTaxCodeID; }
            set
            {
                if (value != this._fK_TXTaxCodeID)
                {
                    _fK_TXTaxCodeID = value;
                }
            }
        }
        public int FK_ARInvoiceID
        {
            get { return _fK_ARInvoiceID; }
            set
            {
                if (value != this._fK_ARInvoiceID)
                {
                    _fK_ARInvoiceID = value;
                }
            }
        }
        public String ARSaleReturnItemSerialNo
        {
            get { return _aRSaleReturnItemSerialNo; }
            set
            {
                if (value != this._aRSaleReturnItemSerialNo)
                {
                    _aRSaleReturnItemSerialNo = value;
                }
            }
        }
        public bool ARSaleReturnItemIsStkItm
        {
            get { return _aRSaleReturnItemIsStkItm; }
            set
            {
                if (value != this._aRSaleReturnItemIsStkItm)
                {
                    _aRSaleReturnItemIsStkItm = value;
                }
            }
        }
        public String ARSaleReturnItemTypeCombo
        {
            get { return _aRSaleReturnItemTypeCombo; }
            set
            {
                if (value != this._aRSaleReturnItemTypeCombo)
                {
                    _aRSaleReturnItemTypeCombo = value;
                }
            }
        }
        public String ARSaleReturnItemDesc
        {
            get { return _aRSaleReturnItemDesc; }
            set
            {
                if (value != this._aRSaleReturnItemDesc)
                {
                    _aRSaleReturnItemDesc = value;
                }
            }
        }
        public decimal ARSaleReturnItemFact
        {
            get { return _aRSaleReturnItemFact; }
            set
            {
                if (value != this._aRSaleReturnItemFact)
                {
                    _aRSaleReturnItemFact = value;
                }
            }
        }
        public String ARSalePriceCombo
        {
            get { return _aRSalePriceCombo; }
            set
            {
                if (value != this._aRSalePriceCombo)
                {
                    _aRSalePriceCombo = value;
                }
            }
        }
        public decimal ARSaleReturnItemUnitPrice
        {
            get { return _aRSaleReturnItemUnitPrice; }
            set
            {
                if (value != this._aRSaleReturnItemUnitPrice)
                {
                    _aRSaleReturnItemUnitPrice = value;
                }
            }
        }
        public decimal ARSaleReturnItemUnitCost
        {
            get { return _aRSaleReturnItemUnitCost; }
            set
            {
                if (value != this._aRSaleReturnItemUnitCost)
                {
                    _aRSaleReturnItemUnitCost = value;
                }
            }
        }
        public decimal ARSaleReturnItemDiscPct
        {
            get { return _aRSaleReturnItemDiscPct; }
            set
            {
                if (value != this._aRSaleReturnItemDiscPct)
                {
                    _aRSaleReturnItemDiscPct = value;
                }
            }
        }
        public decimal ARSaleReturnItemTxPct
        {
            get { return _aRSaleReturnItemTxPct; }
            set
            {
                if (value != this._aRSaleReturnItemTxPct)
                {
                    _aRSaleReturnItemTxPct = value;
                }
            }
        }
        public decimal ARSaleReturnItemQty
        {
            get { return _aRSaleReturnItemQty; }
            set
            {
                if (value != this._aRSaleReturnItemQty)
                {
                    _aRSaleReturnItemQty = value;
                }
            }
        }
        public decimal ARSaleReturnItemStkQty
        {
            get { return _aRSaleReturnItemStkQty; }
            set
            {
                if (value != this._aRSaleReturnItemStkQty)
                {
                    _aRSaleReturnItemStkQty = value;
                }
            }
        }
        public decimal ARSaleReturnItemRQty
        {
            get { return _aRSaleReturnItemRQty; }
            set
            {
                if (value != this._aRSaleReturnItemRQty)
                {
                    _aRSaleReturnItemRQty = value;
                }
            }
        }
        public decimal ARSaleReturnItemShpRQty
        {
            get { return _aRSaleReturnItemShpRQty; }
            set
            {
                if (value != this._aRSaleReturnItemShpRQty)
                {
                    _aRSaleReturnItemShpRQty = value;
                }
            }
        }
        public decimal ARSaleReturnItemRStkQty
        {
            get { return _aRSaleReturnItemRStkQty; }
            set
            {
                if (value != this._aRSaleReturnItemRStkQty)
                {
                    _aRSaleReturnItemRStkQty = value;
                }
            }
        }
        public decimal ARSaleReturnItemPrice
        {
            get { return _aRSaleReturnItemPrice; }
            set
            {
                if (value != this._aRSaleReturnItemPrice)
                {
                    _aRSaleReturnItemPrice = value;
                }
            }
        }
        public String ARSaleReturnItemComment
        {
            get { return _aRSaleReturnItemComment; }
            set
            {
                if (value != this._aRSaleReturnItemComment)
                {
                    _aRSaleReturnItemComment = value;
                }
            }
        }
        public decimal ARSaleReturnItemUnitVol
        {
            get { return _aRSaleReturnItemUnitVol; }
            set
            {
                if (value != this._aRSaleReturnItemUnitVol)
                {
                    _aRSaleReturnItemUnitVol = value;
                }
            }
        }
        public decimal ARSaleReturnItemUnitWeight
        {
            get { return _aRSaleReturnItemUnitWeight; }
            set
            {
                if (value != this._aRSaleReturnItemUnitWeight)
                {
                    _aRSaleReturnItemUnitWeight = value;
                }
            }
        }
        public decimal ARSaleReturnItemTxAmt
        {
            get { return _aRSaleReturnItemTxAmt; }
            set
            {
                if (value != this._aRSaleReturnItemTxAmt)
                {
                    _aRSaleReturnItemTxAmt = value;
                }
            }
        }
        public decimal ARSaleReturnItemDiscAmt
        {
            get { return _aRSaleReturnItemDiscAmt; }
            set
            {
                if (value != this._aRSaleReturnItemDiscAmt)
                {
                    _aRSaleReturnItemDiscAmt = value;
                }
            }
        }
        public decimal ARSaleReturnItemNetAmt
        {
            get { return _aRSaleReturnItemNetAmt; }
            set
            {
                if (value != this._aRSaleReturnItemNetAmt)
                {
                    _aRSaleReturnItemNetAmt = value;
                }
            }
        }
        public decimal ARSaleReturnItemAmtTot
        {
            get { return _aRSaleReturnItemAmtTot; }
            set
            {
                if (value != this._aRSaleReturnItemAmtTot)
                {
                    _aRSaleReturnItemAmtTot = value;
                }
            }
        }
        public decimal ARSaleReturnItemCostTot
        {
            get { return _aRSaleReturnItemCostTot; }
            set
            {
                if (value != this._aRSaleReturnItemCostTot)
                {
                    _aRSaleReturnItemCostTot = value;
                }
            }
        }
        public String ARSaleReturnItemStatusCombo
        {
            get { return _aRSaleReturnItemStatusCombo; }
            set
            {
                if (value != this._aRSaleReturnItemStatusCombo)
                {
                    _aRSaleReturnItemStatusCombo = value;
                }
            }
        }
        public decimal ARSaleReturnItemAmt
        {
            get { return _aRSaleReturnItemAmt; }
            set
            {
                if (value != this._aRSaleReturnItemAmt)
                {
                    _aRSaleReturnItemAmt = value;
                }
            }
        }
        public decimal ARSaleReturnItemCAmt
        {
            get { return _aRSaleReturnItemCAmt; }
            set
            {
                if (value != this._aRSaleReturnItemCAmt)
                {
                    _aRSaleReturnItemCAmt = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public int FK_GLDebitAccountID
        {
            get { return _fK_GLDebitAccountID; }
            set
            {
                if (value != this._fK_GLDebitAccountID)
                {
                    _fK_GLDebitAccountID = value;
                }
            }
        }
        public int FK_GLCreditAccountID
        {
            get { return _fK_GLCreditAccountID; }
            set
            {
                if (value != this._fK_GLCreditAccountID)
                {
                    _fK_GLCreditAccountID = value;
                }
            }
        }
        public int FK_GLDebitVATAccountID
        {
            get { return _fK_GLDebitVATAccountID; }
            set
            {
                if (value != this._fK_GLDebitVATAccountID)
                {
                    _fK_GLDebitVATAccountID = value;
                }
            }
        }
        public int FK_GLCreditVATAccountID
        {
            get { return _fK_GLCreditVATAccountID; }
            set
            {
                if (value != this._fK_GLCreditVATAccountID)
                {
                    _fK_GLCreditVATAccountID = value;
                }
            }
        }
        public decimal ARSaleReturnItemFUnitPrice
        {
            get { return _aRSaleReturnItemFUnitPrice; }
            set
            {
                if (value != this._aRSaleReturnItemFUnitPrice)
                {
                    _aRSaleReturnItemFUnitPrice = value;
                }
            }
        }
        public decimal ARSaleReturnItemFPrice
        {
            get { return _aRSaleReturnItemFPrice; }
            set
            {
                if (value != this._aRSaleReturnItemFPrice)
                {
                    _aRSaleReturnItemFPrice = value;
                }
            }
        }
        public decimal ARSaleReturnItemFTxAmt
        {
            get { return _aRSaleReturnItemFTxAmt; }
            set
            {
                if (value != this._aRSaleReturnItemFTxAmt)
                {
                    _aRSaleReturnItemFTxAmt = value;
                }
            }
        }
        public decimal ARSaleReturnItemFNetAmt
        {
            get { return _aRSaleReturnItemFNetAmt; }
            set
            {
                if (value != this._aRSaleReturnItemFNetAmt)
                {
                    _aRSaleReturnItemFNetAmt = value;
                }
            }
        }
        public decimal ARSaleReturnItemFAmtTot
        {
            get { return _aRSaleReturnItemFAmtTot; }
            set
            {
                if (value != this._aRSaleReturnItemFAmtTot)
                {
                    _aRSaleReturnItemFAmtTot = value;
                }
            }
        }
        public decimal ARSaleReturnItemFImpTxAmt
        {
            get { return _aRSaleReturnItemFImpTxAmt; }
            set
            {
                if (value != this._aRSaleReturnItemFImpTxAmt)
                {
                    _aRSaleReturnItemFImpTxAmt = value;
                }
            }
        }
        public decimal ARSaleReturnItemFDiscAmt
        {
            get { return _aRSaleReturnItemFDiscAmt; }
            set
            {
                if (value != this._aRSaleReturnItemFDiscAmt)
                {
                    _aRSaleReturnItemFDiscAmt = value;
                }
            }
        }
        public decimal ARSaleReturnCreditNoteRQty
        {
            get { return _aRSaleReturnCreditNoteRQty; }
            set
            {
                if (value != this._aRSaleReturnCreditNoteRQty)
                {
                    _aRSaleReturnCreditNoteRQty = value;
                }
            }
        }
        public decimal ARSaleReturnShipmentRQty
        {
            get { return _aRSaleReturnShipmentRQty; }
            set
            {
                if (value != this._aRSaleReturnShipmentRQty)
                {
                    _aRSaleReturnShipmentRQty = value;
                }
            }
        }
        public decimal ARSaleReturnReceiptRQty
        {
            get { return _aRSaleReturnReceiptRQty; }
            set
            {
                if (value != this._aRSaleReturnReceiptRQty)
                {
                    _aRSaleReturnReceiptRQty = value;
                }
            }
        }
        public String ARSaleReturnCreditNoteStatusCombo
        {
            get { return _aRSaleReturnCreditNoteStatusCombo; }
            set
            {
                if (value != this._aRSaleReturnCreditNoteStatusCombo)
                {
                    _aRSaleReturnCreditNoteStatusCombo = value;
                }
            }
        }
        public String ARSaleReturnShipmentStatusCombo
        {
            get { return _aRSaleReturnShipmentStatusCombo; }
            set
            {
                if (value != this._aRSaleReturnShipmentStatusCombo)
                {
                    _aRSaleReturnShipmentStatusCombo = value;
                }
            }
        }
        public String ARSaleReturnReceiptStatusCombo
        {
            get { return _aRSaleReturnReceiptStatusCombo; }
            set
            {
                if (value != this._aRSaleReturnReceiptStatusCombo)
                {
                    _aRSaleReturnReceiptStatusCombo = value;
                }
            }
        }
        public bool ARSaleReturnItemIsAvgCost
        {
            get { return _aRSaleReturnItemIsAvgCost; }
            set
            {
                if (value != this._aRSaleReturnItemIsAvgCost)
                {
                    _aRSaleReturnItemIsAvgCost = value;
                }
            }
        }
        public int FK_ICUOMID
        {
            get { return _fK_ICUOMID; }
            set
            {
                if (value != this._fK_ICUOMID)
                {
                    _fK_ICUOMID = value;
                }
            }
        }
        public int FK_ICStkUOMID
        {
            get { return _fK_ICStkUOMID; }
            set
            {
                if (value != this._fK_ICStkUOMID)
                {
                    _fK_ICStkUOMID = value;
                }
            }
        }
        public int FK_ICWeightUOMID
        {
            get { return _fK_ICWeightUOMID; }
            set
            {
                if (value != this._fK_ICWeightUOMID)
                {
                    _fK_ICWeightUOMID = value;
                }
            }
        }
        public int FK_ICVolumeUOMID
        {
            get { return _fK_ICVolumeUOMID; }
            set
            {
                if (value != this._fK_ICVolumeUOMID)
                {
                    _fK_ICVolumeUOMID = value;
                }
            }
        }
        public decimal ARSaleReturnItemWTot
        {
            get { return _aRSaleReturnItemWTot; }
            set
            {
                if (value != this._aRSaleReturnItemWTot)
                {
                    _aRSaleReturnItemWTot = value;
                }
            }
        }
        public decimal ARSaleReturnItemVTot
        {
            get { return _aRSaleReturnItemVTot; }
            set
            {
                if (value != this._aRSaleReturnItemVTot)
                {
                    _aRSaleReturnItemVTot = value;
                }
            }
        }
        public String GLTOF01Combo
        {
            get { return _gLTOF01Combo; }
            set
            {
                if (value != this._gLTOF01Combo)
                {
                    _gLTOF01Combo = value;
                }
            }
        }
        public String GLTOF02Combo
        {
            get { return _gLTOF02Combo; }
            set
            {
                if (value != this._gLTOF02Combo)
                {
                    _gLTOF02Combo = value;
                }
            }
        }
        public String GLTOF03Combo
        {
            get { return _gLTOF03Combo; }
            set
            {
                if (value != this._gLTOF03Combo)
                {
                    _gLTOF03Combo = value;
                }
            }
        }
        public String GLTOF04Combo
        {
            get { return _gLTOF04Combo; }
            set
            {
                if (value != this._gLTOF04Combo)
                {
                    _gLTOF04Combo = value;
                }
            }
        }
        public String GLTOF05Combo
        {
            get { return _gLTOF05Combo; }
            set
            {
                if (value != this._gLTOF05Combo)
                {
                    _gLTOF05Combo = value;
                }
            }
        }
        public String GLTOF06Combo
        {
            get { return _gLTOF06Combo; }
            set
            {
                if (value != this._gLTOF06Combo)
                {
                    _gLTOF06Combo = value;
                }
            }
        }
        public String GLTOF07Combo
        {
            get { return _gLTOF07Combo; }
            set
            {
                if (value != this._gLTOF07Combo)
                {
                    _gLTOF07Combo = value;
                }
            }
        }
        public String GLTOF08Combo
        {
            get { return _gLTOF08Combo; }
            set
            {
                if (value != this._gLTOF08Combo)
                {
                    _gLTOF08Combo = value;
                }
            }
        }
        public String GLTOF09Combo
        {
            get { return _gLTOF09Combo; }
            set
            {
                if (value != this._gLTOF09Combo)
                {
                    _gLTOF09Combo = value;
                }
            }
        }
        public String GLTOF10Combo
        {
            get { return _gLTOF10Combo; }
            set
            {
                if (value != this._gLTOF10Combo)
                {
                    _gLTOF10Combo = value;
                }
            }
        }
        public decimal ARSaleReturnItemExcQty
        {
            get { return _aRSaleReturnItemExcQty; }
            set
            {
                if (value != this._aRSaleReturnItemExcQty)
                {
                    _aRSaleReturnItemExcQty = value;
                }
            }
        }
        public decimal ARSaleReturnItemOrgQty
        {
            get { return _aRSaleReturnItemOrgQty; }
            set
            {
                if (value != this._aRSaleReturnItemOrgQty)
                {
                    _aRSaleReturnItemOrgQty = value;
                }
            }
        }
        public int FK_ICOrgUOMID
        {
            get { return _fK_ICOrgUOMID; }
            set
            {
                if (value != this._fK_ICOrgUOMID)
                {
                    _fK_ICOrgUOMID = value;
                }
            }
        }
        public String GLTOF11Combo
        {
            get { return _gLTOF11Combo; }
            set
            {
                if (value != this._gLTOF11Combo)
                {
                    _gLTOF11Combo = value;
                }
            }
        }
        public String GLTOF12Combo
        {
            get { return _gLTOF12Combo; }
            set
            {
                if (value != this._gLTOF12Combo)
                {
                    _gLTOF12Combo = value;
                }
            }
        }
        public String GLTOF13Combo
        {
            get { return _gLTOF13Combo; }
            set
            {
                if (value != this._gLTOF13Combo)
                {
                    _gLTOF13Combo = value;
                }
            }
        }
        public String GLTOF14Combo
        {
            get { return _gLTOF14Combo; }
            set
            {
                if (value != this._gLTOF14Combo)
                {
                    _gLTOF14Combo = value;
                }
            }
        }
        public String GLTOF15Combo
        {
            get { return _gLTOF15Combo; }
            set
            {
                if (value != this._gLTOF15Combo)
                {
                    _gLTOF15Combo = value;
                }
            }
        }
        public int FK_ARCampaignID
        {
            get { return _fK_ARCampaignID; }
            set
            {
                if (value != this._fK_ARCampaignID)
                {
                    _fK_ARCampaignID = value;
                }
            }
        }
        public decimal ARSaleReturnAPCreditNoteRQty
        {
            get { return _aRSaleReturnAPCreditNoteRQty; }
            set
            {
                if (value != this._aRSaleReturnAPCreditNoteRQty)
                {
                    _aRSaleReturnAPCreditNoteRQty = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjStkQty
        {
            get { return _aRSaleReturnItemAdjStkQty; }
            set
            {
                if (value != this._aRSaleReturnItemAdjStkQty)
                {
                    _aRSaleReturnItemAdjStkQty = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjUnitPricePct01
        {
            get { return _aRSaleReturnItemAdjUnitPricePct01; }
            set
            {
                if (value != this._aRSaleReturnItemAdjUnitPricePct01)
                {
                    _aRSaleReturnItemAdjUnitPricePct01 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjUnitPricePct02
        {
            get { return _aRSaleReturnItemAdjUnitPricePct02; }
            set
            {
                if (value != this._aRSaleReturnItemAdjUnitPricePct02)
                {
                    _aRSaleReturnItemAdjUnitPricePct02 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjUnitPricePct03
        {
            get { return _aRSaleReturnItemAdjUnitPricePct03; }
            set
            {
                if (value != this._aRSaleReturnItemAdjUnitPricePct03)
                {
                    _aRSaleReturnItemAdjUnitPricePct03 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjUnitPricePct04
        {
            get { return _aRSaleReturnItemAdjUnitPricePct04; }
            set
            {
                if (value != this._aRSaleReturnItemAdjUnitPricePct04)
                {
                    _aRSaleReturnItemAdjUnitPricePct04 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjUnitPricePct05
        {
            get { return _aRSaleReturnItemAdjUnitPricePct05; }
            set
            {
                if (value != this._aRSaleReturnItemAdjUnitPricePct05)
                {
                    _aRSaleReturnItemAdjUnitPricePct05 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjDiscPct01
        {
            get { return _aRSaleReturnItemAdjDiscPct01; }
            set
            {
                if (value != this._aRSaleReturnItemAdjDiscPct01)
                {
                    _aRSaleReturnItemAdjDiscPct01 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjDiscPct02
        {
            get { return _aRSaleReturnItemAdjDiscPct02; }
            set
            {
                if (value != this._aRSaleReturnItemAdjDiscPct02)
                {
                    _aRSaleReturnItemAdjDiscPct02 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjDiscPct03
        {
            get { return _aRSaleReturnItemAdjDiscPct03; }
            set
            {
                if (value != this._aRSaleReturnItemAdjDiscPct03)
                {
                    _aRSaleReturnItemAdjDiscPct03 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjDiscPct04
        {
            get { return _aRSaleReturnItemAdjDiscPct04; }
            set
            {
                if (value != this._aRSaleReturnItemAdjDiscPct04)
                {
                    _aRSaleReturnItemAdjDiscPct04 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjDiscPct05
        {
            get { return _aRSaleReturnItemAdjDiscPct05; }
            set
            {
                if (value != this._aRSaleReturnItemAdjDiscPct05)
                {
                    _aRSaleReturnItemAdjDiscPct05 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjDiscFAmt01
        {
            get { return _aRSaleReturnItemAdjDiscFAmt01; }
            set
            {
                if (value != this._aRSaleReturnItemAdjDiscFAmt01)
                {
                    _aRSaleReturnItemAdjDiscFAmt01 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjDiscFAmt02
        {
            get { return _aRSaleReturnItemAdjDiscFAmt02; }
            set
            {
                if (value != this._aRSaleReturnItemAdjDiscFAmt02)
                {
                    _aRSaleReturnItemAdjDiscFAmt02 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjDiscFAmt03
        {
            get { return _aRSaleReturnItemAdjDiscFAmt03; }
            set
            {
                if (value != this._aRSaleReturnItemAdjDiscFAmt03)
                {
                    _aRSaleReturnItemAdjDiscFAmt03 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjDiscFAmt04
        {
            get { return _aRSaleReturnItemAdjDiscFAmt04; }
            set
            {
                if (value != this._aRSaleReturnItemAdjDiscFAmt04)
                {
                    _aRSaleReturnItemAdjDiscFAmt04 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjDiscFAmt05
        {
            get { return _aRSaleReturnItemAdjDiscFAmt05; }
            set
            {
                if (value != this._aRSaleReturnItemAdjDiscFAmt05)
                {
                    _aRSaleReturnItemAdjDiscFAmt05 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjDiscAmt01
        {
            get { return _aRSaleReturnItemAdjDiscAmt01; }
            set
            {
                if (value != this._aRSaleReturnItemAdjDiscAmt01)
                {
                    _aRSaleReturnItemAdjDiscAmt01 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjDiscAmt02
        {
            get { return _aRSaleReturnItemAdjDiscAmt02; }
            set
            {
                if (value != this._aRSaleReturnItemAdjDiscAmt02)
                {
                    _aRSaleReturnItemAdjDiscAmt02 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjDiscAmt03
        {
            get { return _aRSaleReturnItemAdjDiscAmt03; }
            set
            {
                if (value != this._aRSaleReturnItemAdjDiscAmt03)
                {
                    _aRSaleReturnItemAdjDiscAmt03 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjDiscAmt04
        {
            get { return _aRSaleReturnItemAdjDiscAmt04; }
            set
            {
                if (value != this._aRSaleReturnItemAdjDiscAmt04)
                {
                    _aRSaleReturnItemAdjDiscAmt04 = value;
                }
            }
        }
        public decimal ARSaleReturnItemAdjDiscAmt05
        {
            get { return _aRSaleReturnItemAdjDiscAmt05; }
            set
            {
                if (value != this._aRSaleReturnItemAdjDiscAmt05)
                {
                    _aRSaleReturnItemAdjDiscAmt05 = value;
                }
            }
        }
        public decimal ARSaleReturnItemNetAmtTot
        {
            get { return _aRSaleReturnItemNetAmtTot; }
            set
            {
                if (value != this._aRSaleReturnItemNetAmtTot)
                {
                    _aRSaleReturnItemNetAmtTot = value;
                }
            }
        }
        public decimal ARSaleReturnItemFNetAmtTot
        {
            get { return _aRSaleReturnItemFNetAmtTot; }
            set
            {
                if (value != this._aRSaleReturnItemFNetAmtTot)
                {
                    _aRSaleReturnItemFNetAmtTot = value;
                }
            }
        }
        public decimal ARSaleReturnItemDiscAmtTot
        {
            get { return _aRSaleReturnItemDiscAmtTot; }
            set
            {
                if (value != this._aRSaleReturnItemDiscAmtTot)
                {
                    _aRSaleReturnItemDiscAmtTot = value;
                }
            }
        }
        public decimal ARSaleReturnItemFDiscAmtTot
        {
            get { return _aRSaleReturnItemFDiscAmtTot; }
            set
            {
                if (value != this._aRSaleReturnItemFDiscAmtTot)
                {
                    _aRSaleReturnItemFDiscAmtTot = value;
                }
            }
        }
        public String ARSaleReturnItemLotNo
        {
            get { return _aRSaleReturnItemLotNo; }
            set
            {
                if (value != this._aRSaleReturnItemLotNo)
                {
                    _aRSaleReturnItemLotNo = value;
                }
            }
        }
        public decimal ARSaleReturnItemOrgFUnitPrice
        {
            get { return _aRSaleReturnItemOrgFUnitPrice; }
            set
            {
                if (value != this._aRSaleReturnItemOrgFUnitPrice)
                {
                    _aRSaleReturnItemOrgFUnitPrice = value;
                }
            }
        }
        public int FK_ARComplainID
        {
            get { return _fK_ARComplainID; }
            set
            {
                if (value != this._fK_ARComplainID)
                {
                    _fK_ARComplainID = value;
                }
            }
        }
        public String ARSaleReturnItemPOF01Combo
        {
            get { return _aRSaleReturnItemPOF01Combo; }
            set
            {
                if (value != this._aRSaleReturnItemPOF01Combo)
                {
                    _aRSaleReturnItemPOF01Combo = value;
                }
            }
        }
        public String ARSaleReturnItemPOF02Combo
        {
            get { return _aRSaleReturnItemPOF02Combo; }
            set
            {
                if (value != this._aRSaleReturnItemPOF02Combo)
                {
                    _aRSaleReturnItemPOF02Combo = value;
                }
            }
        }
        public String ARSaleReturnItemPOF03Combo
        {
            get { return _aRSaleReturnItemPOF03Combo; }
            set
            {
                if (value != this._aRSaleReturnItemPOF03Combo)
                {
                    _aRSaleReturnItemPOF03Combo = value;
                }
            }
        }
        public String ARSaleReturnItemPOF04Combo
        {
            get { return _aRSaleReturnItemPOF04Combo; }
            set
            {
                if (value != this._aRSaleReturnItemPOF04Combo)
                {
                    _aRSaleReturnItemPOF04Combo = value;
                }
            }
        }
        public String ARSaleReturnItemPOF05Combo
        {
            get { return _aRSaleReturnItemPOF05Combo; }
            set
            {
                if (value != this._aRSaleReturnItemPOF05Combo)
                {
                    _aRSaleReturnItemPOF05Combo = value;
                }
            }
        }
        #endregion
    }
    #endregion
}