using ExpertLib;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace gmc_api.Entities
{
    #region APCreditNoteItemPInvoiceItems
    //-----------------------------------------------------------
    //Generated By: SQLDBTools - LINHCLH (v2.1.89)
    //Class: APCreditNoteItemPInvoiceItemsInfo
    //Created Date: Monday, 21 Aug 2017
    //-----------------------------------------------------------
    [Table("APCreditNoteItemPInvoiceItems")]
    public class APCreditNoteItemPInvoiceItemsInfo : BaseInfo
    {
        public APCreditNoteItemPInvoiceItemsInfo()
        {
        }
        #region Variables
        protected int _aPCreditNoteItemPInvoiceItemID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_APCreditNoteItemID;
        protected int _fK_APPInvoiceItemID;

        #endregion
        [Key]
        #region Public properties
        public int APCreditNoteItemPInvoiceItemID
        {
            get { return _aPCreditNoteItemPInvoiceItemID; }
            set
            {
                if (value != this._aPCreditNoteItemPInvoiceItemID)
                {
                    _aPCreditNoteItemPInvoiceItemID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public int FK_APCreditNoteItemID
        {
            get { return _fK_APCreditNoteItemID; }
            set
            {
                if (value != this._fK_APCreditNoteItemID)
                {
                    _fK_APCreditNoteItemID = value;
                }
            }
        }
        public int FK_APPInvoiceItemID
        {
            get { return _fK_APPInvoiceItemID; }
            set
            {
                if (value != this._fK_APPInvoiceItemID)
                {
                    _fK_APPInvoiceItemID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}