using ExpertLib;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace gmc_api.Entities
{
    #region APPInvoiceItemReceiptItems
    //-----------------------------------------------------------
    //Generated By: GMC Studio
    //Class:APPInvoiceItemReceiptItemsInfo
    //Created Date:Wednesday, October 21, 2009
    //-----------------------------------------------------------
    [Table("APPInvoiceItemReceiptItems")]
    public class APPInvoiceItemReceiptItemsInfo : BaseInfo
    {
        public APPInvoiceItemReceiptItemsInfo()
        {
        }
        #region Variables
        protected int _aPPInvoiceItemReceiptItemID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_APPInvoiceItemID;
        protected int _fK_ICReceiptItemID;
        #endregion
        [Key]
        #region Public properties
        public int APPInvoiceItemReceiptItemID
        {
            get { return _aPPInvoiceItemReceiptItemID; }
            set
            {
                if (value != this._aPPInvoiceItemReceiptItemID)
                {
                    _aPPInvoiceItemReceiptItemID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public int FK_APPInvoiceItemID
        {
            get { return _fK_APPInvoiceItemID; }
            set
            {
                if (value != this._fK_APPInvoiceItemID)
                {
                    _fK_APPInvoiceItemID = value;
                }
            }
        }
        public int FK_ICReceiptItemID
        {
            get { return _fK_ICReceiptItemID; }
            set
            {
                if (value != this._fK_ICReceiptItemID)
                {
                    _fK_ICReceiptItemID = value;
                }
            }
        }
        #endregion
    }
    #endregion
}