 using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region ICReceiptPInvoices
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: ICReceiptPInvoicesInfo
    //Created Date: Tuesday, 05 Nov 2024
    //-----------------------------------------------------------
    [Table("ICReceiptPInvoices")]
    public class ICReceiptPInvoicesInfo : BaseInfo
    {
        #region Variables
        protected int _iCReceiptPInvoiceID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_APPInvoiceID;
        protected int _fK_ICReceiptID;

        #endregion
        #region Public properties
        [Key]
        public int ICReceiptPInvoiceID
        {
            get { return _iCReceiptPInvoiceID; }
            set
            {
                if (value != this._iCReceiptPInvoiceID)
                {
                    _iCReceiptPInvoiceID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public int FK_APPInvoiceID
        {
            get { return _fK_APPInvoiceID; }
            set
            {
                if (value != this._fK_APPInvoiceID)
                {
                    _fK_APPInvoiceID = value;
                }
            }
        }
        public int FK_ICReceiptID
        {
            get { return _fK_ICReceiptID; }
            set
            {
                if (value != this._fK_ICReceiptID)
                {
                    _fK_ICReceiptID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}