using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region GLConfigs
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: GLConfigsInfo
    //Created Date: Thursday, 05 Dec 2024
    //-----------------------------------------------------------
    [Table("GLConfigs")]
    public class GLConfigsInfo : BaseInfo
    {
        #region Variables
        protected int _gLConfigID;
        protected int _fK_GLReceivableAccount;
        protected int _fK_GLPayableAccount;
        protected int _fK_GLVATOutAccount;
        protected int _fK_GLVATInAccount;
        protected int _fK_GLCashAccount;
        protected int _fK_GLBankAccount;
        protected int _fK_GLSaleNonInvoiceAccount;
        protected bool _gLConfigAutoPost = true;
        protected String _gLConfigJounalNumberingTypeCombo = String.Empty;
        protected int _fK_GLProductionInCompleteAccountID;
        protected bool _gLConfigCheckTranCfgCheck = true;
        protected String _gLCurrencyExcRateMethodCombo = String.Empty;
        protected bool _gLConfigCheckCashFlowCheck = true;

        #endregion
        #region Public properties
        [Key]
        public int GLConfigID
        {
            get { return _gLConfigID; }
            set
            {
                if (value != this._gLConfigID)
                {
                    _gLConfigID = value;
                }
            }
        }
        public int FK_GLReceivableAccount
        {
            get { return _fK_GLReceivableAccount; }
            set
            {
                if (value != this._fK_GLReceivableAccount)
                {
                    _fK_GLReceivableAccount = value;
                }
            }
        }
        public int FK_GLPayableAccount
        {
            get { return _fK_GLPayableAccount; }
            set
            {
                if (value != this._fK_GLPayableAccount)
                {
                    _fK_GLPayableAccount = value;
                }
            }
        }
        public int FK_GLVATOutAccount
        {
            get { return _fK_GLVATOutAccount; }
            set
            {
                if (value != this._fK_GLVATOutAccount)
                {
                    _fK_GLVATOutAccount = value;
                }
            }
        }
        public int FK_GLVATInAccount
        {
            get { return _fK_GLVATInAccount; }
            set
            {
                if (value != this._fK_GLVATInAccount)
                {
                    _fK_GLVATInAccount = value;
                }
            }
        }
        public int FK_GLCashAccount
        {
            get { return _fK_GLCashAccount; }
            set
            {
                if (value != this._fK_GLCashAccount)
                {
                    _fK_GLCashAccount = value;
                }
            }
        }
        public int FK_GLBankAccount
        {
            get { return _fK_GLBankAccount; }
            set
            {
                if (value != this._fK_GLBankAccount)
                {
                    _fK_GLBankAccount = value;
                }
            }
        }
        public int FK_GLSaleNonInvoiceAccount
        {
            get { return _fK_GLSaleNonInvoiceAccount; }
            set
            {
                if (value != this._fK_GLSaleNonInvoiceAccount)
                {
                    _fK_GLSaleNonInvoiceAccount = value;
                }
            }
        }
        public bool GLConfigAutoPost
        {
            get { return _gLConfigAutoPost; }
            set
            {
                if (value != this._gLConfigAutoPost)
                {
                    _gLConfigAutoPost = value;
                }
            }
        }
        public String GLConfigJounalNumberingTypeCombo
        {
            get { return _gLConfigJounalNumberingTypeCombo; }
            set
            {
                if (value != this._gLConfigJounalNumberingTypeCombo)
                {
                    _gLConfigJounalNumberingTypeCombo = value;
                }
            }
        }
        public int FK_GLProductionInCompleteAccountID
        {
            get { return _fK_GLProductionInCompleteAccountID; }
            set
            {
                if (value != this._fK_GLProductionInCompleteAccountID)
                {
                    _fK_GLProductionInCompleteAccountID = value;
                }
            }
        }
        public bool GLConfigCheckTranCfgCheck
        {
            get { return _gLConfigCheckTranCfgCheck; }
            set
            {
                if (value != this._gLConfigCheckTranCfgCheck)
                {
                    _gLConfigCheckTranCfgCheck = value;
                }
            }
        }
        public String GLCurrencyExcRateMethodCombo
        {
            get { return _gLCurrencyExcRateMethodCombo; }
            set
            {
                if (value != this._gLCurrencyExcRateMethodCombo)
                {
                    _gLCurrencyExcRateMethodCombo = value;
                }
            }
        }
        public bool GLConfigCheckCashFlowCheck
        {
            get { return _gLConfigCheckCashFlowCheck; }
            set
            {
                if (value != this._gLConfigCheckCashFlowCheck)
                {
                    _gLConfigCheckCashFlowCheck = value;
                }
            }
        }

        #endregion
    }
    #endregion
}