using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region GLUserGroupOFItems
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: GLUserGroupOFItemsInfo
    //Created Date: Monday, 06 Jan 2025
    //-----------------------------------------------------------
    [Table("GLUserGroupOFItems")]
    public class GLUserGroupOFItemsInfo : BaseInfo
    {
        #region Variables
        protected int _gLUserGroupOFItemID;
        protected int _fK_GLUserGroupID;
        protected String _gLUserGroupOFItemModuleName = String.Empty;
        protected int _fK_ADOFID;
        protected int _fK_ADOFItemID;
        protected Nullable<DateTime> _aACreatedDate;
        protected String _aACreatedUser = String.Empty;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected bool _aASelected = true;

        #endregion
        #region Public properties
        [Key]
        public int GLUserGroupOFItemID
        {
            get { return _gLUserGroupOFItemID; }
            set
            {
                if (value != this._gLUserGroupOFItemID)
                {
                    _gLUserGroupOFItemID = value;
                }
            }
        }
        public int FK_GLUserGroupID
        {
            get { return _fK_GLUserGroupID; }
            set
            {
                if (value != this._fK_GLUserGroupID)
                {
                    _fK_GLUserGroupID = value;
                }
            }
        }
        public String GLUserGroupOFItemModuleName
        {
            get { return _gLUserGroupOFItemModuleName; }
            set
            {
                if (value != this._gLUserGroupOFItemModuleName)
                {
                    _gLUserGroupOFItemModuleName = value;
                }
            }
        }
        public int FK_ADOFID
        {
            get { return _fK_ADOFID; }
            set
            {
                if (value != this._fK_ADOFID)
                {
                    _fK_ADOFID = value;
                }
            }
        }
        public int FK_ADOFItemID
        {
            get { return _fK_ADOFItemID; }
            set
            {
                if (value != this._fK_ADOFItemID)
                {
                    _fK_ADOFItemID = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }

        #endregion
    }
    #endregion
}