using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region GLVoucherItems
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: GLVoucherItemsInfo
    //Created Date: Monday, 13 Jan 2025
    //-----------------------------------------------------------
    [Table("GLVoucherItems")]
    public class GLVoucherItems : BaseInfo
    {
        #region Variables
        protected int _gLVoucherItemID;
        protected Nullable<DateTime> _aACreatedDate;
        protected String _aACreatedUser = String.Empty;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_GLVoucherID;
        protected int _fK_BRBranchID;
        protected int _fK_BRFBranchID;
        protected int _fK_BRAgentID;
        protected int _fK_ICBrandID;
        protected int _fK_GLCostCenterID;
        protected int _fK_GLDebitAccountID;
        protected int _fK_GLCreditAccountID;
        protected int _fK_GLCreditVATAccountID;
        protected int _fK_GLDebitVATAccountID;
        protected String _gLVoucherItemDesc = String.Empty;
        protected decimal _gLVoucherItemCAmt;
        protected decimal _gLVoucherItemAmt;
        protected int _fK_ARCustomerID;
        protected int _fK_APSupplierID;
        protected String _gLVoucherItemObjectTypeCombo = String.Empty;
        protected int _fK_HREmployeeID;
        protected int _fK_GLJobID;
        protected String _gLVoucherItemInvNo = String.Empty;
        protected String _gLVoucherItemInvSeries = String.Empty;
        protected Nullable<DateTime> _gLVoucherItemInvDate;
        protected String _gLVoucherItemObjectName = String.Empty;
        protected String _gLVoucherItemObjectAdd = String.Empty;
        protected String _gLVoucherItemObjectTxNo = String.Empty;
        protected int _fK_ICProductID;
        protected int _fK_ICProductGroupID;
        protected int _fK_HRDepartmentID;
        protected int _fK_GLBankID;
        protected decimal _gLVoucherItemTaxAmtTot;
        protected int _fK_TXTaxCodeID;
        protected decimal _gLVoucherItemTaxCAmtTot;
        protected int _fK_GLObjectID;
        protected decimal _gLVoucherItemTaxPct;
        protected decimal _gLVoucherItemPrice;
        protected decimal _gLVoucherItemFPrice;
        protected decimal _gLVoucherItemFTaxAmtTot;
        protected decimal _gLVoucherItemAmtTot;
        protected decimal _gLVoucherItemFAmtTot;
        protected decimal _gLVoucherItemCustomerAmt;
        protected decimal _gLVoucherItemCompanyAmt;
        protected int _fK_LOCarAllocateID;
        protected int _fK_LOCarID;
        protected String _gLVoucherItemStatusCombo = DefaultStatus;
        protected int _fK_GLProfitCenterID;
        protected String _gLVoucherItemTypeCombo = String.Empty;
        protected int _fK_LOCarAllocateItemID;
        protected Nullable<DateTime> _gLVoucherItemDueDate;
        protected String _gLVoucherItemDocNo = String.Empty;
        protected String _gLVoucherItemDescFee = String.Empty;
        protected int _fK_APPInvoiceID;
        protected int _fK_ARInvoiceID;
        protected decimal _gLVoucherItemAllocateAmt;
        protected int _fK_ICServiceChargeItemID;
        protected int _fK_GLCostCenter1ID;
        protected int _fK_GLCostCenter2ID;
        protected int _fK_GLCostCenter3ID;
        protected int _fK_GLCostCenter4ID;
        protected int _fK_GLCostCenter5ID;
        protected int _fK_GLCostDistID;
        protected int _fK_GLTranCfgID;
        protected int _fK_ARCustomerIDCredit;
        protected int _fK_APSupplierIDCredit;
        protected int _fK_HREmployeeIDCredit;
        protected int _fK_GEInvTypeID;
        protected String _gLVoucherItemInvForm = String.Empty;
        protected int _fK_PPCostCenterID;
        protected int _fK_GLAccountID;
        protected String _gLObjectType = String.Empty;
        protected decimal _gLVoucherItemDebitAmt;
        protected decimal _gLVoucherItemCreditAmt;
        protected decimal _gLVoucherItemDebitFAmt;
        protected decimal _gLVoucherItemCreditFAmt;
        protected int _fK_GECurrencyID;
        protected decimal _gLVoucherItemExcRate;
        protected int _gLVoucherItemJournalGroup;
        protected String _gLVoucherItemProductName = String.Empty;
        protected String _gLTOF01Combo = String.Empty;
        protected String _gLTOF02Combo = String.Empty;
        protected String _gLTOF03Combo = String.Empty;
        protected String _gLTOF04Combo = String.Empty;
        protected String _gLTOF05Combo = String.Empty;
        protected String _gLTOF06Combo = String.Empty;
        protected String _gLTOF07Combo = String.Empty;
        protected String _gLTOF08Combo = String.Empty;
        protected String _gLTOF09Combo = String.Empty;
        protected String _gLTOF10Combo = String.Empty;
        protected int _fK_FAAssetConstructionID;
        protected int _fK_GLVoucherItemPmtReqID;
        protected decimal _gLVoucherItemRFPrice;
        protected decimal _gLVoucherItemRPrice;
        protected int _fK_APPOID;
        protected int _fK_GLLoanAgreementID;
        protected int _fK_FAAssetID;
        protected int _fK_APSupplierBankID;
        protected int _fK_GLCashFlowID;
        protected int _fK_ARSOID;
        protected int _fK_GLNationID;
        protected int _fK_ARContractID;
        protected Nullable<DateTime> _gLVoucherItemEstPmtDate;
        protected decimal _gLVoucherItemDiffAmt;
        protected decimal _gLVoucherItemCalcTaxFAmt;
        protected decimal _gLVoucherItemCalcTaxAmt;
        protected int _fK_GLBudgetID;
        protected int _fK_GLBudgetCfgID;
        protected int _fK_GLBudgetAllocateAdjID;
        protected int _fK_GLBudgetAllocateAdjItemID;
        protected int _fK_GLBudgetAllocateAdjDetailID;
        protected decimal _gLVoucherItemRAmtTot;
        protected decimal _gLVoucherItemRFAmtTot;
        protected bool _aASelected = true;
        protected String _gLTOF11Combo = String.Empty;
        protected String _gLTOF12Combo = String.Empty;
        protected String _gLTOF13Combo = String.Empty;
        protected String _gLTOF14Combo = String.Empty;
        protected String _gLTOF15Combo = String.Empty;
        protected String _gLVoucherItemComment = String.Empty;
        protected int _fK_GLVoucherPmtReqID;
        protected String _gLVoucherItemDesc1 = String.Empty;
        protected String _gLVoucherItemDesc2 = String.Empty;
        protected String _gLVoucherItemDesc3 = String.Empty;
        protected String _gLVoucherItemDesc4 = String.Empty;
        protected String _gLVoucherItemDesc5 = String.Empty;
        protected int _fK_PMProjectID;
        protected int _fK_GLVoucherHARPmtID;
        protected int _fK_GLAdvanceReqProposalID;
        protected int _fK_GLAdvanceReqProposalItemID;
        protected int _fK_GLVoucherFeePaymnetID;
        protected int _fK_GLVoucherFeePaymnetItemID;
        protected int _fK_GLObjectBankID;

        #endregion
        #region Public properties
        [Key]
        public int GLVoucherItemID
        {
            get { return _gLVoucherItemID; }
            set
            {
                if (value != this._gLVoucherItemID)
                {
                    _gLVoucherItemID = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public int FK_GLVoucherID
        {
            get { return _fK_GLVoucherID; }
            set
            {
                if (value != this._fK_GLVoucherID)
                {
                    _fK_GLVoucherID = value;
                }
            }
        }
        public int FK_BRBranchID
        {
            get { return _fK_BRBranchID; }
            set
            {
                if (value != this._fK_BRBranchID)
                {
                    _fK_BRBranchID = value;
                }
            }
        }
        public int FK_BRFBranchID
        {
            get { return _fK_BRFBranchID; }
            set
            {
                if (value != this._fK_BRFBranchID)
                {
                    _fK_BRFBranchID = value;
                }
            }
        }
        public int FK_BRAgentID
        {
            get { return _fK_BRAgentID; }
            set
            {
                if (value != this._fK_BRAgentID)
                {
                    _fK_BRAgentID = value;
                }
            }
        }
        public int FK_ICBrandID
        {
            get { return _fK_ICBrandID; }
            set
            {
                if (value != this._fK_ICBrandID)
                {
                    _fK_ICBrandID = value;
                }
            }
        }
        public int FK_GLCostCenterID
        {
            get { return _fK_GLCostCenterID; }
            set
            {
                if (value != this._fK_GLCostCenterID)
                {
                    _fK_GLCostCenterID = value;
                }
            }
        }
        public int FK_GLDebitAccountID
        {
            get { return _fK_GLDebitAccountID; }
            set
            {
                if (value != this._fK_GLDebitAccountID)
                {
                    _fK_GLDebitAccountID = value;
                }
            }
        }
        public int FK_GLCreditAccountID
        {
            get { return _fK_GLCreditAccountID; }
            set
            {
                if (value != this._fK_GLCreditAccountID)
                {
                    _fK_GLCreditAccountID = value;
                }
            }
        }
        public int FK_GLCreditVATAccountID
        {
            get { return _fK_GLCreditVATAccountID; }
            set
            {
                if (value != this._fK_GLCreditVATAccountID)
                {
                    _fK_GLCreditVATAccountID = value;
                }
            }
        }
        public int FK_GLDebitVATAccountID
        {
            get { return _fK_GLDebitVATAccountID; }
            set
            {
                if (value != this._fK_GLDebitVATAccountID)
                {
                    _fK_GLDebitVATAccountID = value;
                }
            }
        }
        public String GLVoucherItemDesc
        {
            get { return _gLVoucherItemDesc; }
            set
            {
                if (value != this._gLVoucherItemDesc)
                {
                    _gLVoucherItemDesc = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemCAmt
        {
            get { return _gLVoucherItemCAmt; }
            set
            {
                if (value != this._gLVoucherItemCAmt)
                {
                    _gLVoucherItemCAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemAmt
        {
            get { return _gLVoucherItemAmt; }
            set
            {
                if (value != this._gLVoucherItemAmt)
                {
                    _gLVoucherItemAmt = value;
                }
            }
        }
        public int FK_ARCustomerID
        {
            get { return _fK_ARCustomerID; }
            set
            {
                if (value != this._fK_ARCustomerID)
                {
                    _fK_ARCustomerID = value;
                }
            }
        }
        public int FK_APSupplierID
        {
            get { return _fK_APSupplierID; }
            set
            {
                if (value != this._fK_APSupplierID)
                {
                    _fK_APSupplierID = value;
                }
            }
        }
        public String GLVoucherItemObjectTypeCombo
        {
            get { return _gLVoucherItemObjectTypeCombo; }
            set
            {
                if (value != this._gLVoucherItemObjectTypeCombo)
                {
                    _gLVoucherItemObjectTypeCombo = value;
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                }
            }
        }
        public int FK_GLJobID
        {
            get { return _fK_GLJobID; }
            set
            {
                if (value != this._fK_GLJobID)
                {
                    _fK_GLJobID = value;
                }
            }
        }
        public String GLVoucherItemInvNo
        {
            get { return _gLVoucherItemInvNo; }
            set
            {
                if (value != this._gLVoucherItemInvNo)
                {
                    _gLVoucherItemInvNo = value;
                }
            }
        }
        public String GLVoucherItemInvSeries
        {
            get { return _gLVoucherItemInvSeries; }
            set
            {
                if (value != this._gLVoucherItemInvSeries)
                {
                    _gLVoucherItemInvSeries = value;
                }
            }
        }
        public Nullable<DateTime> GLVoucherItemInvDate
        {
            get { return _gLVoucherItemInvDate; }
            set
            {
                if (value != this._gLVoucherItemInvDate)
                {
                    _gLVoucherItemInvDate = value;
                }
            }
        }
        public String GLVoucherItemObjectName
        {
            get { return _gLVoucherItemObjectName; }
            set
            {
                if (value != this._gLVoucherItemObjectName)
                {
                    _gLVoucherItemObjectName = value;
                }
            }
        }
        public String GLVoucherItemObjectAdd
        {
            get { return _gLVoucherItemObjectAdd; }
            set
            {
                if (value != this._gLVoucherItemObjectAdd)
                {
                    _gLVoucherItemObjectAdd = value;
                }
            }
        }
        public String GLVoucherItemObjectTxNo
        {
            get { return _gLVoucherItemObjectTxNo; }
            set
            {
                if (value != this._gLVoucherItemObjectTxNo)
                {
                    _gLVoucherItemObjectTxNo = value;
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                }
            }
        }
        public int FK_ICProductGroupID
        {
            get { return _fK_ICProductGroupID; }
            set
            {
                if (value != this._fK_ICProductGroupID)
                {
                    _fK_ICProductGroupID = value;
                }
            }
        }
        public int FK_HRDepartmentID
        {
            get { return _fK_HRDepartmentID; }
            set
            {
                if (value != this._fK_HRDepartmentID)
                {
                    _fK_HRDepartmentID = value;
                }
            }
        }
        public int FK_GLBankID
        {
            get { return _fK_GLBankID; }
            set
            {
                if (value != this._fK_GLBankID)
                {
                    _fK_GLBankID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemTaxAmtTot
        {
            get { return _gLVoucherItemTaxAmtTot; }
            set
            {
                if (value != this._gLVoucherItemTaxAmtTot)
                {
                    _gLVoucherItemTaxAmtTot = value;
                }
            }
        }
        public int FK_TXTaxCodeID
        {
            get { return _fK_TXTaxCodeID; }
            set
            {
                if (value != this._fK_TXTaxCodeID)
                {
                    _fK_TXTaxCodeID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemTaxCAmtTot
        {
            get { return _gLVoucherItemTaxCAmtTot; }
            set
            {
                if (value != this._gLVoucherItemTaxCAmtTot)
                {
                    _gLVoucherItemTaxCAmtTot = value;
                }
            }
        }
        public int FK_GLObjectID
        {
            get { return _fK_GLObjectID; }
            set
            {
                if (value != this._fK_GLObjectID)
                {
                    _fK_GLObjectID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemTaxPct
        {
            get { return _gLVoucherItemTaxPct; }
            set
            {
                if (value != this._gLVoucherItemTaxPct)
                {
                    _gLVoucherItemTaxPct = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemPrice
        {
            get { return _gLVoucherItemPrice; }
            set
            {
                if (value != this._gLVoucherItemPrice)
                {
                    _gLVoucherItemPrice = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemFPrice
        {
            get { return _gLVoucherItemFPrice; }
            set
            {
                if (value != this._gLVoucherItemFPrice)
                {
                    _gLVoucherItemFPrice = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemFTaxAmtTot
        {
            get { return _gLVoucherItemFTaxAmtTot; }
            set
            {
                if (value != this._gLVoucherItemFTaxAmtTot)
                {
                    _gLVoucherItemFTaxAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemAmtTot
        {
            get { return _gLVoucherItemAmtTot; }
            set
            {
                if (value != this._gLVoucherItemAmtTot)
                {
                    _gLVoucherItemAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemFAmtTot
        {
            get { return _gLVoucherItemFAmtTot; }
            set
            {
                if (value != this._gLVoucherItemFAmtTot)
                {
                    _gLVoucherItemFAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemCustomerAmt
        {
            get { return _gLVoucherItemCustomerAmt; }
            set
            {
                if (value != this._gLVoucherItemCustomerAmt)
                {
                    _gLVoucherItemCustomerAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemCompanyAmt
        {
            get { return _gLVoucherItemCompanyAmt; }
            set
            {
                if (value != this._gLVoucherItemCompanyAmt)
                {
                    _gLVoucherItemCompanyAmt = value;
                }
            }
        }
        public int FK_LOCarAllocateID
        {
            get { return _fK_LOCarAllocateID; }
            set
            {
                if (value != this._fK_LOCarAllocateID)
                {
                    _fK_LOCarAllocateID = value;
                }
            }
        }
        public int FK_LOCarID
        {
            get { return _fK_LOCarID; }
            set
            {
                if (value != this._fK_LOCarID)
                {
                    _fK_LOCarID = value;
                }
            }
        }
        public String GLVoucherItemStatusCombo
        {
            get { return _gLVoucherItemStatusCombo; }
            set
            {
                if (value != this._gLVoucherItemStatusCombo)
                {
                    _gLVoucherItemStatusCombo = value;
                }
            }
        }
        public int FK_GLProfitCenterID
        {
            get { return _fK_GLProfitCenterID; }
            set
            {
                if (value != this._fK_GLProfitCenterID)
                {
                    _fK_GLProfitCenterID = value;
                }
            }
        }
        public String GLVoucherItemTypeCombo
        {
            get { return _gLVoucherItemTypeCombo; }
            set
            {
                if (value != this._gLVoucherItemTypeCombo)
                {
                    _gLVoucherItemTypeCombo = value;
                }
            }
        }
        public int FK_LOCarAllocateItemID
        {
            get { return _fK_LOCarAllocateItemID; }
            set
            {
                if (value != this._fK_LOCarAllocateItemID)
                {
                    _fK_LOCarAllocateItemID = value;
                }
            }
        }
        public Nullable<DateTime> GLVoucherItemDueDate
        {
            get { return _gLVoucherItemDueDate; }
            set
            {
                if (value != this._gLVoucherItemDueDate)
                {
                    _gLVoucherItemDueDate = value;
                }
            }
        }
        public String GLVoucherItemDocNo
        {
            get { return _gLVoucherItemDocNo; }
            set
            {
                if (value != this._gLVoucherItemDocNo)
                {
                    _gLVoucherItemDocNo = value;
                }
            }
        }
        public String GLVoucherItemDescFee
        {
            get { return _gLVoucherItemDescFee; }
            set
            {
                if (value != this._gLVoucherItemDescFee)
                {
                    _gLVoucherItemDescFee = value;
                }
            }
        }
        public int FK_APPInvoiceID
        {
            get { return _fK_APPInvoiceID; }
            set
            {
                if (value != this._fK_APPInvoiceID)
                {
                    _fK_APPInvoiceID = value;
                }
            }
        }
        public int FK_ARInvoiceID
        {
            get { return _fK_ARInvoiceID; }
            set
            {
                if (value != this._fK_ARInvoiceID)
                {
                    _fK_ARInvoiceID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemAllocateAmt
        {
            get { return _gLVoucherItemAllocateAmt; }
            set
            {
                if (value != this._gLVoucherItemAllocateAmt)
                {
                    _gLVoucherItemAllocateAmt = value;
                }
            }
        }
        public int FK_ICServiceChargeItemID
        {
            get { return _fK_ICServiceChargeItemID; }
            set
            {
                if (value != this._fK_ICServiceChargeItemID)
                {
                    _fK_ICServiceChargeItemID = value;
                }
            }
        }
        public int FK_GLCostCenter1ID
        {
            get { return _fK_GLCostCenter1ID; }
            set
            {
                if (value != this._fK_GLCostCenter1ID)
                {
                    _fK_GLCostCenter1ID = value;
                }
            }
        }
        public int FK_GLCostCenter2ID
        {
            get { return _fK_GLCostCenter2ID; }
            set
            {
                if (value != this._fK_GLCostCenter2ID)
                {
                    _fK_GLCostCenter2ID = value;
                }
            }
        }
        public int FK_GLCostCenter3ID
        {
            get { return _fK_GLCostCenter3ID; }
            set
            {
                if (value != this._fK_GLCostCenter3ID)
                {
                    _fK_GLCostCenter3ID = value;
                }
            }
        }
        public int FK_GLCostCenter4ID
        {
            get { return _fK_GLCostCenter4ID; }
            set
            {
                if (value != this._fK_GLCostCenter4ID)
                {
                    _fK_GLCostCenter4ID = value;
                }
            }
        }
        public int FK_GLCostCenter5ID
        {
            get { return _fK_GLCostCenter5ID; }
            set
            {
                if (value != this._fK_GLCostCenter5ID)
                {
                    _fK_GLCostCenter5ID = value;
                }
            }
        }
        public int FK_GLCostDistID
        {
            get { return _fK_GLCostDistID; }
            set
            {
                if (value != this._fK_GLCostDistID)
                {
                    _fK_GLCostDistID = value;
                }
            }
        }
        public int FK_GLTranCfgID
        {
            get { return _fK_GLTranCfgID; }
            set
            {
                if (value != this._fK_GLTranCfgID)
                {
                    _fK_GLTranCfgID = value;
                }
            }
        }
        public int FK_ARCustomerIDCredit
        {
            get { return _fK_ARCustomerIDCredit; }
            set
            {
                if (value != this._fK_ARCustomerIDCredit)
                {
                    _fK_ARCustomerIDCredit = value;
                }
            }
        }
        public int FK_APSupplierIDCredit
        {
            get { return _fK_APSupplierIDCredit; }
            set
            {
                if (value != this._fK_APSupplierIDCredit)
                {
                    _fK_APSupplierIDCredit = value;
                }
            }
        }
        public int FK_HREmployeeIDCredit
        {
            get { return _fK_HREmployeeIDCredit; }
            set
            {
                if (value != this._fK_HREmployeeIDCredit)
                {
                    _fK_HREmployeeIDCredit = value;
                }
            }
        }
        public int FK_GEInvTypeID
        {
            get { return _fK_GEInvTypeID; }
            set
            {
                if (value != this._fK_GEInvTypeID)
                {
                    _fK_GEInvTypeID = value;
                }
            }
        }
        public String GLVoucherItemInvForm
        {
            get { return _gLVoucherItemInvForm; }
            set
            {
                if (value != this._gLVoucherItemInvForm)
                {
                    _gLVoucherItemInvForm = value;
                }
            }
        }
        public int FK_PPCostCenterID
        {
            get { return _fK_PPCostCenterID; }
            set
            {
                if (value != this._fK_PPCostCenterID)
                {
                    _fK_PPCostCenterID = value;
                }
            }
        }
        public int FK_GLAccountID
        {
            get { return _fK_GLAccountID; }
            set
            {
                if (value != this._fK_GLAccountID)
                {
                    _fK_GLAccountID = value;
                }
            }
        }
        public String GLObjectType
        {
            get { return _gLObjectType; }
            set
            {
                if (value != this._gLObjectType)
                {
                    _gLObjectType = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemDebitAmt
        {
            get { return _gLVoucherItemDebitAmt; }
            set
            {
                if (value != this._gLVoucherItemDebitAmt)
                {
                    _gLVoucherItemDebitAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemCreditAmt
        {
            get { return _gLVoucherItemCreditAmt; }
            set
            {
                if (value != this._gLVoucherItemCreditAmt)
                {
                    _gLVoucherItemCreditAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemDebitFAmt
        {
            get { return _gLVoucherItemDebitFAmt; }
            set
            {
                if (value != this._gLVoucherItemDebitFAmt)
                {
                    _gLVoucherItemDebitFAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemCreditFAmt
        {
            get { return _gLVoucherItemCreditFAmt; }
            set
            {
                if (value != this._gLVoucherItemCreditFAmt)
                {
                    _gLVoucherItemCreditFAmt = value;
                }
            }
        }
        public int FK_GECurrencyID
        {
            get { return _fK_GECurrencyID; }
            set
            {
                if (value != this._fK_GECurrencyID)
                {
                    _fK_GECurrencyID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemExcRate
        {
            get { return _gLVoucherItemExcRate; }
            set
            {
                if (value != this._gLVoucherItemExcRate)
                {
                    _gLVoucherItemExcRate = value;
                }
            }
        }
        public int GLVoucherItemJournalGroup
        {
            get { return _gLVoucherItemJournalGroup; }
            set
            {
                if (value != this._gLVoucherItemJournalGroup)
                {
                    _gLVoucherItemJournalGroup = value;
                }
            }
        }
        public String GLVoucherItemProductName
        {
            get { return _gLVoucherItemProductName; }
            set
            {
                if (value != this._gLVoucherItemProductName)
                {
                    _gLVoucherItemProductName = value;
                }
            }
        }
        public String GLTOF01Combo
        {
            get { return _gLTOF01Combo; }
            set
            {
                if (value != this._gLTOF01Combo)
                {
                    _gLTOF01Combo = value;
                }
            }
        }
        public String GLTOF02Combo
        {
            get { return _gLTOF02Combo; }
            set
            {
                if (value != this._gLTOF02Combo)
                {
                    _gLTOF02Combo = value;
                }
            }
        }
        public String GLTOF03Combo
        {
            get { return _gLTOF03Combo; }
            set
            {
                if (value != this._gLTOF03Combo)
                {
                    _gLTOF03Combo = value;
                }
            }
        }
        public String GLTOF04Combo
        {
            get { return _gLTOF04Combo; }
            set
            {
                if (value != this._gLTOF04Combo)
                {
                    _gLTOF04Combo = value;
                }
            }
        }
        public String GLTOF05Combo
        {
            get { return _gLTOF05Combo; }
            set
            {
                if (value != this._gLTOF05Combo)
                {
                    _gLTOF05Combo = value;
                }
            }
        }
        public String GLTOF06Combo
        {
            get { return _gLTOF06Combo; }
            set
            {
                if (value != this._gLTOF06Combo)
                {
                    _gLTOF06Combo = value;
                }
            }
        }
        public String GLTOF07Combo
        {
            get { return _gLTOF07Combo; }
            set
            {
                if (value != this._gLTOF07Combo)
                {
                    _gLTOF07Combo = value;
                }
            }
        }
        public String GLTOF08Combo
        {
            get { return _gLTOF08Combo; }
            set
            {
                if (value != this._gLTOF08Combo)
                {
                    _gLTOF08Combo = value;
                }
            }
        }
        public String GLTOF09Combo
        {
            get { return _gLTOF09Combo; }
            set
            {
                if (value != this._gLTOF09Combo)
                {
                    _gLTOF09Combo = value;
                }
            }
        }
        public String GLTOF10Combo
        {
            get { return _gLTOF10Combo; }
            set
            {
                if (value != this._gLTOF10Combo)
                {
                    _gLTOF10Combo = value;
                }
            }
        }
        public int FK_FAAssetConstructionID
        {
            get { return _fK_FAAssetConstructionID; }
            set
            {
                if (value != this._fK_FAAssetConstructionID)
                {
                    _fK_FAAssetConstructionID = value;
                }
            }
        }
        public int FK_GLVoucherItemPmtReqID
        {
            get { return _fK_GLVoucherItemPmtReqID; }
            set
            {
                if (value != this._fK_GLVoucherItemPmtReqID)
                {
                    _fK_GLVoucherItemPmtReqID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemRFPrice
        {
            get { return _gLVoucherItemRFPrice; }
            set
            {
                if (value != this._gLVoucherItemRFPrice)
                {
                    _gLVoucherItemRFPrice = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemRPrice
        {
            get { return _gLVoucherItemRPrice; }
            set
            {
                if (value != this._gLVoucherItemRPrice)
                {
                    _gLVoucherItemRPrice = value;
                }
            }
        }
        public int FK_APPOID
        {
            get { return _fK_APPOID; }
            set
            {
                if (value != this._fK_APPOID)
                {
                    _fK_APPOID = value;
                }
            }
        }
        public int FK_GLLoanAgreementID
        {
            get { return _fK_GLLoanAgreementID; }
            set
            {
                if (value != this._fK_GLLoanAgreementID)
                {
                    _fK_GLLoanAgreementID = value;
                }
            }
        }
        public int FK_FAAssetID
        {
            get { return _fK_FAAssetID; }
            set
            {
                if (value != this._fK_FAAssetID)
                {
                    _fK_FAAssetID = value;
                }
            }
        }
        public int FK_APSupplierBankID
        {
            get { return _fK_APSupplierBankID; }
            set
            {
                if (value != this._fK_APSupplierBankID)
                {
                    _fK_APSupplierBankID = value;
                }
            }
        }
        public int FK_GLCashFlowID
        {
            get { return _fK_GLCashFlowID; }
            set
            {
                if (value != this._fK_GLCashFlowID)
                {
                    _fK_GLCashFlowID = value;
                }
            }
        }
        public int FK_ARSOID
        {
            get { return _fK_ARSOID; }
            set
            {
                if (value != this._fK_ARSOID)
                {
                    _fK_ARSOID = value;
                }
            }
        }
        public int FK_GLNationID
        {
            get { return _fK_GLNationID; }
            set
            {
                if (value != this._fK_GLNationID)
                {
                    _fK_GLNationID = value;
                }
            }
        }
        public int FK_ARContractID
        {
            get { return _fK_ARContractID; }
            set
            {
                if (value != this._fK_ARContractID)
                {
                    _fK_ARContractID = value;
                }
            }
        }
        public Nullable<DateTime> GLVoucherItemEstPmtDate
        {
            get { return _gLVoucherItemEstPmtDate; }
            set
            {
                if (value != this._gLVoucherItemEstPmtDate)
                {
                    _gLVoucherItemEstPmtDate = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemDiffAmt
        {
            get { return _gLVoucherItemDiffAmt; }
            set
            {
                if (value != this._gLVoucherItemDiffAmt)
                {
                    _gLVoucherItemDiffAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemCalcTaxFAmt
        {
            get { return _gLVoucherItemCalcTaxFAmt; }
            set
            {
                if (value != this._gLVoucherItemCalcTaxFAmt)
                {
                    _gLVoucherItemCalcTaxFAmt = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemCalcTaxAmt
        {
            get { return _gLVoucherItemCalcTaxAmt; }
            set
            {
                if (value != this._gLVoucherItemCalcTaxAmt)
                {
                    _gLVoucherItemCalcTaxAmt = value;
                }
            }
        }
        public int FK_GLBudgetID
        {
            get { return _fK_GLBudgetID; }
            set
            {
                if (value != this._fK_GLBudgetID)
                {
                    _fK_GLBudgetID = value;
                }
            }
        }
        public int FK_GLBudgetCfgID
        {
            get { return _fK_GLBudgetCfgID; }
            set
            {
                if (value != this._fK_GLBudgetCfgID)
                {
                    _fK_GLBudgetCfgID = value;
                }
            }
        }
        public int FK_GLBudgetAllocateAdjID
        {
            get { return _fK_GLBudgetAllocateAdjID; }
            set
            {
                if (value != this._fK_GLBudgetAllocateAdjID)
                {
                    _fK_GLBudgetAllocateAdjID = value;
                }
            }
        }
        public int FK_GLBudgetAllocateAdjItemID
        {
            get { return _fK_GLBudgetAllocateAdjItemID; }
            set
            {
                if (value != this._fK_GLBudgetAllocateAdjItemID)
                {
                    _fK_GLBudgetAllocateAdjItemID = value;
                }
            }
        }
        public int FK_GLBudgetAllocateAdjDetailID
        {
            get { return _fK_GLBudgetAllocateAdjDetailID; }
            set
            {
                if (value != this._fK_GLBudgetAllocateAdjDetailID)
                {
                    _fK_GLBudgetAllocateAdjDetailID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemRAmtTot
        {
            get { return _gLVoucherItemRAmtTot; }
            set
            {
                if (value != this._gLVoucherItemRAmtTot)
                {
                    _gLVoucherItemRAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherItemRFAmtTot
        {
            get { return _gLVoucherItemRFAmtTot; }
            set
            {
                if (value != this._gLVoucherItemRFAmtTot)
                {
                    _gLVoucherItemRFAmtTot = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public String GLTOF11Combo
        {
            get { return _gLTOF11Combo; }
            set
            {
                if (value != this._gLTOF11Combo)
                {
                    _gLTOF11Combo = value;
                }
            }
        }
        public String GLTOF12Combo
        {
            get { return _gLTOF12Combo; }
            set
            {
                if (value != this._gLTOF12Combo)
                {
                    _gLTOF12Combo = value;
                }
            }
        }
        public String GLTOF13Combo
        {
            get { return _gLTOF13Combo; }
            set
            {
                if (value != this._gLTOF13Combo)
                {
                    _gLTOF13Combo = value;
                }
            }
        }
        public String GLTOF14Combo
        {
            get { return _gLTOF14Combo; }
            set
            {
                if (value != this._gLTOF14Combo)
                {
                    _gLTOF14Combo = value;
                }
            }
        }
        public String GLTOF15Combo
        {
            get { return _gLTOF15Combo; }
            set
            {
                if (value != this._gLTOF15Combo)
                {
                    _gLTOF15Combo = value;
                }
            }
        }
        public String GLVoucherItemComment
        {
            get { return _gLVoucherItemComment; }
            set
            {
                if (value != this._gLVoucherItemComment)
                {
                    _gLVoucherItemComment = value;
                }
            }
        }
        public int FK_GLVoucherPmtReqID
        {
            get { return _fK_GLVoucherPmtReqID; }
            set
            {
                if (value != this._fK_GLVoucherPmtReqID)
                {
                    _fK_GLVoucherPmtReqID = value;
                }
            }
        }
        public String GLVoucherItemDesc1
        {
            get { return _gLVoucherItemDesc1; }
            set
            {
                if (value != this._gLVoucherItemDesc1)
                {
                    _gLVoucherItemDesc1 = value;
                }
            }
        }
        public String GLVoucherItemDesc2
        {
            get { return _gLVoucherItemDesc2; }
            set
            {
                if (value != this._gLVoucherItemDesc2)
                {
                    _gLVoucherItemDesc2 = value;
                }
            }
        }
        public String GLVoucherItemDesc3
        {
            get { return _gLVoucherItemDesc3; }
            set
            {
                if (value != this._gLVoucherItemDesc3)
                {
                    _gLVoucherItemDesc3 = value;
                }
            }
        }
        public String GLVoucherItemDesc4
        {
            get { return _gLVoucherItemDesc4; }
            set
            {
                if (value != this._gLVoucherItemDesc4)
                {
                    _gLVoucherItemDesc4 = value;
                }
            }
        }
        public String GLVoucherItemDesc5
        {
            get { return _gLVoucherItemDesc5; }
            set
            {
                if (value != this._gLVoucherItemDesc5)
                {
                    _gLVoucherItemDesc5 = value;
                }
            }
        }
        public int FK_PMProjectID
        {
            get { return _fK_PMProjectID; }
            set
            {
                if (value != this._fK_PMProjectID)
                {
                    _fK_PMProjectID = value;
                }
            }
        }
        public int FK_GLVoucherHARPmtID
        {
            get { return _fK_GLVoucherHARPmtID; }
            set
            {
                if (value != this._fK_GLVoucherHARPmtID)
                {
                    _fK_GLVoucherHARPmtID = value;
                }
            }
        }
        public int FK_GLAdvanceReqProposalID
        {
            get { return _fK_GLAdvanceReqProposalID; }
            set
            {
                if (value != this._fK_GLAdvanceReqProposalID)
                {
                    _fK_GLAdvanceReqProposalID = value;
                }
            }
        }
        public int FK_GLAdvanceReqProposalItemID
        {
            get { return _fK_GLAdvanceReqProposalItemID; }
            set
            {
                if (value != this._fK_GLAdvanceReqProposalItemID)
                {
                    _fK_GLAdvanceReqProposalItemID = value;
                }
            }
        }
        public int FK_GLVoucherFeePaymnetID
        {
            get { return _fK_GLVoucherFeePaymnetID; }
            set
            {
                if (value != this._fK_GLVoucherFeePaymnetID)
                {
                    _fK_GLVoucherFeePaymnetID = value;
                }
            }
        }
        public int FK_GLVoucherFeePaymnetItemID
        {
            get { return _fK_GLVoucherFeePaymnetItemID; }
            set
            {
                if (value != this._fK_GLVoucherFeePaymnetItemID)
                {
                    _fK_GLVoucherFeePaymnetItemID = value;
                }
            }
        }
        public int FK_GLObjectBankID
        {
            get { return _fK_GLObjectBankID; }
            set
            {
                if (value != this._fK_GLObjectBankID)
                {
                    _fK_GLObjectBankID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}