using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace gmc_api.Entities
{
    #region GLVouchers
    //-----------------------------------------------------------
    //Generated By: SQLDBTools.Net ♫ Hồռ؏ ₤ĩռᶋ (v3.0.73)
    //Class: GLVouchersInfo
    //Created Date: Monday, 13 Jan 2025
    //-----------------------------------------------------------
    [Table("GLVouchers")]
    public class GLVouchers : BaseInfo
    {
        #region Variables
        protected int _gLVoucherID;
        protected Nullable<DateTime> _aACreatedDate;
        protected String _aACreatedUser = String.Empty;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected String _gLVoucherNo = String.Empty;
        protected String _gLVoucherName = String.Empty;
        protected String _gLVoucherDesc = String.Empty;
        protected DateTime _gLVoucherDate = DateTime.Now;
        protected String _gLVoucherObjectName = String.Empty;
        protected String _gLVoucherOF1Combo = String.Empty;
        protected String _gLVoucherOF2Combo = String.Empty;
        protected String _gLVoucherOF3Combo = String.Empty;
        protected String _gLVoucherTypeCombo = String.Empty;
        protected int _fK_BRBranchID;
        protected int _fK_GECurrencyID;
        protected int _fK_GLTranCfgID;
        protected decimal _gLVoucherExRate;
        protected int _fK_GLAccountID;
        protected int _gLVoucherAccoutDbCr;
        protected decimal _gLVoucherTotAmt;
        protected int _fK_HREmployeeID;
        protected String _gLVoucherObjectTypeCombo = String.Empty;
        protected String _gLVoucherStatusTypeCombo = DefaultStatus;
        protected String _gLVoucherRefNo = String.Empty;
        protected Nullable<DateTime> _gLVoucherRefDate;
        protected bool _aASelected = true;
        protected int _fK_GLCostCenterID;
        protected String _aAPostStatus = DefaultStatus;
        protected int _fK_GLConsolidateGroupID;
        protected int _fK_PMProjectID;
        protected String _aALastPostNo = String.Empty;
        protected Nullable<DateTime> _aALastPostDate;
        protected int _fK_GLRecurringVoucherID;
        protected int _fK_GLBankID;
        protected int _fK_GLTransactionCurrencyID;
        protected decimal _gLVoucherExcRate;
        protected int _fK_LOCarAllocateID;
        protected String _gLVoucherUserGroupStageStatusCombo = DefaultStatus;
        protected String _gLVoucherApproveStageStatusCombo = DefaultStatus;
        protected int _fK_GLProfitCenterID;
        protected String _gLVoucherComment = String.Empty;
        protected String _gLVoucherGroupTypeCombo = String.Empty;
        protected String _approvalStatusCombo = DefaultStatus;
        protected int _fK_ADApprovalProcID;
        protected int _fK_ADApprovalProcStepID;
        protected decimal _gLVoucherFAmtTot;
        protected decimal _gLVoucherAmtTot;
        protected decimal _gLVoucherRFAmtTot;
        protected decimal _gLVoucherRAmtTot;
        protected decimal _gLVoucherPrepaidAmtTot;
        protected decimal _gLVoucherPrepaidFAmtTot;
        protected decimal _gLVoucherPaymentFAmtTot;
        protected decimal _gLVoucherPaymentAmtTot;
        protected String _gLVoucherAllocateTypeCombo = String.Empty;
        protected String _gLOutPmtPayToName = String.Empty;
        protected String _gLOutPmtPayToDesc = String.Empty;
        protected String _gLVoucherOutPaymentTypeCombo = String.Empty;
        protected String _gLVoucherInPaymentTypeCombo = String.Empty;
        protected int _fK_APSupplierID;
        protected int _fK_ARCustomerID;
        protected int _fK_GEPaymentCurrencyID;
        protected decimal _gLVoucherPaymentExcRate;
        protected decimal _gLVoucherAllocateAmtTot;
        protected decimal _gLVoucherDiscFAmtTot;
        protected decimal _gLVoucherDiscAmtTot;
        protected decimal _gLVoucherOverDueFAmtTot;
        protected decimal _gLVoucherOverDueAmtTot;
        protected String _gLVoucherPmtReqStatusCombo = DefaultStatus;
        protected int _fK_ARCustomerRequestID;
        protected int _fK_HRDepartmentID;
        protected int _fK_GLVoucherPmtReqID;
        protected int _fK_GLCostDistID;
        protected String _gLVoucherQuestName = String.Empty;
        protected String _gLVoucherQuestTaxCode = String.Empty;
        protected String _gLVoucherQuestAddress = String.Empty;
        protected String _aACompanyTypeCombo = String.Empty;
        protected String _gLVoucherPmtMethodTypeCombo = String.Empty;
        protected Nullable<DateTime> _gLVoucherDueDate;
        protected int _fK_APPOID;
        protected decimal _gLVoucherPmtReqAmtTot;
        protected decimal _gLVoucherPmtReqFAmtTot;
        protected decimal _gLVoucherPmtReqRAmtTot;
        protected decimal _gLVoucherPmtReqRFAmtTot;
        protected bool _gLVoucherNeedPaymentCheck = true;
        protected String _aAThueRemark = String.Empty;
        protected decimal _gLVoucherAllocateFAmtTot;
        protected String _gLVoucherUNCNo = String.Empty;
        protected String _aAOrgDocNo = String.Empty;
        protected String _gLObjectType = String.Empty;
        protected Nullable<DateTime> _gLVoucherJrnDate;
        protected int _fK_GLVoucherCancelID;
        protected String _gLVoucherTransStatusCombo = DefaultStatus;
        protected int _fK_GLLCID;
        protected String _gLVoucherJrnNo = String.Empty;
        protected int _fK_GECurrencyExObjID;
        protected String _gLVoucherCreateTypeCombo = String.Empty;
        protected decimal _gLVoucherOBFAmtTot;
        protected decimal _gLVoucherEBFAmtTot;
        protected decimal _gLVoucherOBAmtTot;
        protected decimal _gLVoucherEBAmtTot;
        protected decimal _gLVoucherDiffAmount;
        protected String _gLVoucherDiffTypeCombo = String.Empty;
        protected Nullable<DateTime> _gLVoucherPaymentDeadline;
        protected int _fK_GLAdvanceReqProposalID;
        protected String _gLVoucherReferenceNo = String.Empty;
        protected String _gLExecutionStatusCombo = DefaultStatus;
        protected int _fK_GLVoucherFeePaymnetID;
        protected String _gLObjectTypeCombo = String.Empty;
        protected int _fK_GLObjectVoucherItemID;

        #endregion
        #region Public properties
        [Key]
        public int GLVoucherID
        {
            get { return _gLVoucherID; }
            set
            {
                if (value != this._gLVoucherID)
                {
                    _gLVoucherID = value;
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public String GLVoucherNo
        {
            get { return _gLVoucherNo; }
            set
            {
                if (value != this._gLVoucherNo)
                {
                    _gLVoucherNo = value;
                }
            }
        }
        public String GLVoucherName
        {
            get { return _gLVoucherName; }
            set
            {
                if (value != this._gLVoucherName)
                {
                    _gLVoucherName = value;
                }
            }
        }
        public String GLVoucherDesc
        {
            get { return _gLVoucherDesc; }
            set
            {
                if (value != this._gLVoucherDesc)
                {
                    _gLVoucherDesc = value;
                }
            }
        }
        public DateTime GLVoucherDate
        {
            get { return _gLVoucherDate; }
            set
            {
                if (value != this._gLVoucherDate)
                {
                    _gLVoucherDate = value;
                }
            }
        }
        public String GLVoucherObjectName
        {
            get { return _gLVoucherObjectName; }
            set
            {
                if (value != this._gLVoucherObjectName)
                {
                    _gLVoucherObjectName = value;
                }
            }
        }
        public String GLVoucherOF1Combo
        {
            get { return _gLVoucherOF1Combo; }
            set
            {
                if (value != this._gLVoucherOF1Combo)
                {
                    _gLVoucherOF1Combo = value;
                }
            }
        }
        public String GLVoucherOF2Combo
        {
            get { return _gLVoucherOF2Combo; }
            set
            {
                if (value != this._gLVoucherOF2Combo)
                {
                    _gLVoucherOF2Combo = value;
                }
            }
        }
        public String GLVoucherOF3Combo
        {
            get { return _gLVoucherOF3Combo; }
            set
            {
                if (value != this._gLVoucherOF3Combo)
                {
                    _gLVoucherOF3Combo = value;
                }
            }
        }
        public String GLVoucherTypeCombo
        {
            get { return _gLVoucherTypeCombo; }
            set
            {
                if (value != this._gLVoucherTypeCombo)
                {
                    _gLVoucherTypeCombo = value;
                }
            }
        }
        public int FK_BRBranchID
        {
            get { return _fK_BRBranchID; }
            set
            {
                if (value != this._fK_BRBranchID)
                {
                    _fK_BRBranchID = value;
                }
            }
        }
        public int FK_GECurrencyID
        {
            get { return _fK_GECurrencyID; }
            set
            {
                if (value != this._fK_GECurrencyID)
                {
                    _fK_GECurrencyID = value;
                }
            }
        }
        public int FK_GLTranCfgID
        {
            get { return _fK_GLTranCfgID; }
            set
            {
                if (value != this._fK_GLTranCfgID)
                {
                    _fK_GLTranCfgID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherExRate
        {
            get { return _gLVoucherExRate; }
            set
            {
                if (value != this._gLVoucherExRate)
                {
                    _gLVoucherExRate = value;
                }
            }
        }
        public int FK_GLAccountID
        {
            get { return _fK_GLAccountID; }
            set
            {
                if (value != this._fK_GLAccountID)
                {
                    _fK_GLAccountID = value;
                }
            }
        }
        public int GLVoucherAccoutDbCr
        {
            get { return _gLVoucherAccoutDbCr; }
            set
            {
                if (value != this._gLVoucherAccoutDbCr)
                {
                    _gLVoucherAccoutDbCr = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherTotAmt
        {
            get { return _gLVoucherTotAmt; }
            set
            {
                if (value != this._gLVoucherTotAmt)
                {
                    _gLVoucherTotAmt = value;
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                }
            }
        }
        public String GLVoucherObjectTypeCombo
        {
            get { return _gLVoucherObjectTypeCombo; }
            set
            {
                if (value != this._gLVoucherObjectTypeCombo)
                {
                    _gLVoucherObjectTypeCombo = value;
                }
            }
        }
        public String GLVoucherStatusTypeCombo
        {
            get { return _gLVoucherStatusTypeCombo; }
            set
            {
                if (value != this._gLVoucherStatusTypeCombo)
                {
                    _gLVoucherStatusTypeCombo = value;
                }
            }
        }
        public String GLVoucherRefNo
        {
            get { return _gLVoucherRefNo; }
            set
            {
                if (value != this._gLVoucherRefNo)
                {
                    _gLVoucherRefNo = value;
                }
            }
        }
        public Nullable<DateTime> GLVoucherRefDate
        {
            get { return _gLVoucherRefDate; }
            set
            {
                if (value != this._gLVoucherRefDate)
                {
                    _gLVoucherRefDate = value;
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                }
            }
        }
        public int FK_GLCostCenterID
        {
            get { return _fK_GLCostCenterID; }
            set
            {
                if (value != this._fK_GLCostCenterID)
                {
                    _fK_GLCostCenterID = value;
                }
            }
        }
        public String AAPostStatus
        {
            get { return _aAPostStatus; }
            set
            {
                if (value != this._aAPostStatus)
                {
                    _aAPostStatus = value;
                }
            }
        }
        public int FK_GLConsolidateGroupID
        {
            get { return _fK_GLConsolidateGroupID; }
            set
            {
                if (value != this._fK_GLConsolidateGroupID)
                {
                    _fK_GLConsolidateGroupID = value;
                }
            }
        }
        public int FK_PMProjectID
        {
            get { return _fK_PMProjectID; }
            set
            {
                if (value != this._fK_PMProjectID)
                {
                    _fK_PMProjectID = value;
                }
            }
        }
        public String AALastPostNo
        {
            get { return _aALastPostNo; }
            set
            {
                if (value != this._aALastPostNo)
                {
                    _aALastPostNo = value;
                }
            }
        }
        public Nullable<DateTime> AALastPostDate
        {
            get { return _aALastPostDate; }
            set
            {
                if (value != this._aALastPostDate)
                {
                    _aALastPostDate = value;
                }
            }
        }
        public int FK_GLRecurringVoucherID
        {
            get { return _fK_GLRecurringVoucherID; }
            set
            {
                if (value != this._fK_GLRecurringVoucherID)
                {
                    _fK_GLRecurringVoucherID = value;
                }
            }
        }
        public int FK_GLBankID
        {
            get { return _fK_GLBankID; }
            set
            {
                if (value != this._fK_GLBankID)
                {
                    _fK_GLBankID = value;
                }
            }
        }
        public int FK_GLTransactionCurrencyID
        {
            get { return _fK_GLTransactionCurrencyID; }
            set
            {
                if (value != this._fK_GLTransactionCurrencyID)
                {
                    _fK_GLTransactionCurrencyID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherExcRate
        {
            get { return _gLVoucherExcRate; }
            set
            {
                if (value != this._gLVoucherExcRate)
                {
                    _gLVoucherExcRate = value;
                }
            }
        }
        public int FK_LOCarAllocateID
        {
            get { return _fK_LOCarAllocateID; }
            set
            {
                if (value != this._fK_LOCarAllocateID)
                {
                    _fK_LOCarAllocateID = value;
                }
            }
        }
        public String GLVoucherUserGroupStageStatusCombo
        {
            get { return _gLVoucherUserGroupStageStatusCombo; }
            set
            {
                if (value != this._gLVoucherUserGroupStageStatusCombo)
                {
                    _gLVoucherUserGroupStageStatusCombo = value;
                }
            }
        }
        public String GLVoucherApproveStageStatusCombo
        {
            get { return _gLVoucherApproveStageStatusCombo; }
            set
            {
                if (value != this._gLVoucherApproveStageStatusCombo)
                {
                    _gLVoucherApproveStageStatusCombo = value;
                }
            }
        }
        public int FK_GLProfitCenterID
        {
            get { return _fK_GLProfitCenterID; }
            set
            {
                if (value != this._fK_GLProfitCenterID)
                {
                    _fK_GLProfitCenterID = value;
                }
            }
        }
        public String GLVoucherComment
        {
            get { return _gLVoucherComment; }
            set
            {
                if (value != this._gLVoucherComment)
                {
                    _gLVoucherComment = value;
                }
            }
        }
        public String GLVoucherGroupTypeCombo
        {
            get { return _gLVoucherGroupTypeCombo; }
            set
            {
                if (value != this._gLVoucherGroupTypeCombo)
                {
                    _gLVoucherGroupTypeCombo = value;
                }
            }
        }
        public String ApprovalStatusCombo
        {
            get { return _approvalStatusCombo; }
            set
            {
                if (value != this._approvalStatusCombo)
                {
                    _approvalStatusCombo = value;
                }
            }
        }
        public int FK_ADApprovalProcID
        {
            get { return _fK_ADApprovalProcID; }
            set
            {
                if (value != this._fK_ADApprovalProcID)
                {
                    _fK_ADApprovalProcID = value;
                }
            }
        }
        public int FK_ADApprovalProcStepID
        {
            get { return _fK_ADApprovalProcStepID; }
            set
            {
                if (value != this._fK_ADApprovalProcStepID)
                {
                    _fK_ADApprovalProcStepID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherFAmtTot
        {
            get { return _gLVoucherFAmtTot; }
            set
            {
                if (value != this._gLVoucherFAmtTot)
                {
                    _gLVoucherFAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherAmtTot
        {
            get { return _gLVoucherAmtTot; }
            set
            {
                if (value != this._gLVoucherAmtTot)
                {
                    _gLVoucherAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherRFAmtTot
        {
            get { return _gLVoucherRFAmtTot; }
            set
            {
                if (value != this._gLVoucherRFAmtTot)
                {
                    _gLVoucherRFAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherRAmtTot
        {
            get { return _gLVoucherRAmtTot; }
            set
            {
                if (value != this._gLVoucherRAmtTot)
                {
                    _gLVoucherRAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherPrepaidAmtTot
        {
            get { return _gLVoucherPrepaidAmtTot; }
            set
            {
                if (value != this._gLVoucherPrepaidAmtTot)
                {
                    _gLVoucherPrepaidAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherPrepaidFAmtTot
        {
            get { return _gLVoucherPrepaidFAmtTot; }
            set
            {
                if (value != this._gLVoucherPrepaidFAmtTot)
                {
                    _gLVoucherPrepaidFAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherPaymentFAmtTot
        {
            get { return _gLVoucherPaymentFAmtTot; }
            set
            {
                if (value != this._gLVoucherPaymentFAmtTot)
                {
                    _gLVoucherPaymentFAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherPaymentAmtTot
        {
            get { return _gLVoucherPaymentAmtTot; }
            set
            {
                if (value != this._gLVoucherPaymentAmtTot)
                {
                    _gLVoucherPaymentAmtTot = value;
                }
            }
        }
        public String GLVoucherAllocateTypeCombo
        {
            get { return _gLVoucherAllocateTypeCombo; }
            set
            {
                if (value != this._gLVoucherAllocateTypeCombo)
                {
                    _gLVoucherAllocateTypeCombo = value;
                }
            }
        }
        public String GLOutPmtPayToName
        {
            get { return _gLOutPmtPayToName; }
            set
            {
                if (value != this._gLOutPmtPayToName)
                {
                    _gLOutPmtPayToName = value;
                }
            }
        }
        public String GLOutPmtPayToDesc
        {
            get { return _gLOutPmtPayToDesc; }
            set
            {
                if (value != this._gLOutPmtPayToDesc)
                {
                    _gLOutPmtPayToDesc = value;
                }
            }
        }
        public String GLVoucherOutPaymentTypeCombo
        {
            get { return _gLVoucherOutPaymentTypeCombo; }
            set
            {
                if (value != this._gLVoucherOutPaymentTypeCombo)
                {
                    _gLVoucherOutPaymentTypeCombo = value;
                }
            }
        }
        public String GLVoucherInPaymentTypeCombo
        {
            get { return _gLVoucherInPaymentTypeCombo; }
            set
            {
                if (value != this._gLVoucherInPaymentTypeCombo)
                {
                    _gLVoucherInPaymentTypeCombo = value;
                }
            }
        }
        public int FK_APSupplierID
        {
            get { return _fK_APSupplierID; }
            set
            {
                if (value != this._fK_APSupplierID)
                {
                    _fK_APSupplierID = value;
                }
            }
        }
        public int FK_ARCustomerID
        {
            get { return _fK_ARCustomerID; }
            set
            {
                if (value != this._fK_ARCustomerID)
                {
                    _fK_ARCustomerID = value;
                }
            }
        }
        public int FK_GEPaymentCurrencyID
        {
            get { return _fK_GEPaymentCurrencyID; }
            set
            {
                if (value != this._fK_GEPaymentCurrencyID)
                {
                    _fK_GEPaymentCurrencyID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherPaymentExcRate
        {
            get { return _gLVoucherPaymentExcRate; }
            set
            {
                if (value != this._gLVoucherPaymentExcRate)
                {
                    _gLVoucherPaymentExcRate = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherAllocateAmtTot
        {
            get { return _gLVoucherAllocateAmtTot; }
            set
            {
                if (value != this._gLVoucherAllocateAmtTot)
                {
                    _gLVoucherAllocateAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherDiscFAmtTot
        {
            get { return _gLVoucherDiscFAmtTot; }
            set
            {
                if (value != this._gLVoucherDiscFAmtTot)
                {
                    _gLVoucherDiscFAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherDiscAmtTot
        {
            get { return _gLVoucherDiscAmtTot; }
            set
            {
                if (value != this._gLVoucherDiscAmtTot)
                {
                    _gLVoucherDiscAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherOverDueFAmtTot
        {
            get { return _gLVoucherOverDueFAmtTot; }
            set
            {
                if (value != this._gLVoucherOverDueFAmtTot)
                {
                    _gLVoucherOverDueFAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherOverDueAmtTot
        {
            get { return _gLVoucherOverDueAmtTot; }
            set
            {
                if (value != this._gLVoucherOverDueAmtTot)
                {
                    _gLVoucherOverDueAmtTot = value;
                }
            }
        }
        public String GLVoucherPmtReqStatusCombo
        {
            get { return _gLVoucherPmtReqStatusCombo; }
            set
            {
                if (value != this._gLVoucherPmtReqStatusCombo)
                {
                    _gLVoucherPmtReqStatusCombo = value;
                }
            }
        }
        public int FK_ARCustomerRequestID
        {
            get { return _fK_ARCustomerRequestID; }
            set
            {
                if (value != this._fK_ARCustomerRequestID)
                {
                    _fK_ARCustomerRequestID = value;
                }
            }
        }
        public int FK_HRDepartmentID
        {
            get { return _fK_HRDepartmentID; }
            set
            {
                if (value != this._fK_HRDepartmentID)
                {
                    _fK_HRDepartmentID = value;
                }
            }
        }
        public int FK_GLVoucherPmtReqID
        {
            get { return _fK_GLVoucherPmtReqID; }
            set
            {
                if (value != this._fK_GLVoucherPmtReqID)
                {
                    _fK_GLVoucherPmtReqID = value;
                }
            }
        }
        public int FK_GLCostDistID
        {
            get { return _fK_GLCostDistID; }
            set
            {
                if (value != this._fK_GLCostDistID)
                {
                    _fK_GLCostDistID = value;
                }
            }
        }
        public String GLVoucherQuestName
        {
            get { return _gLVoucherQuestName; }
            set
            {
                if (value != this._gLVoucherQuestName)
                {
                    _gLVoucherQuestName = value;
                }
            }
        }
        public String GLVoucherQuestTaxCode
        {
            get { return _gLVoucherQuestTaxCode; }
            set
            {
                if (value != this._gLVoucherQuestTaxCode)
                {
                    _gLVoucherQuestTaxCode = value;
                }
            }
        }
        public String GLVoucherQuestAddress
        {
            get { return _gLVoucherQuestAddress; }
            set
            {
                if (value != this._gLVoucherQuestAddress)
                {
                    _gLVoucherQuestAddress = value;
                }
            }
        }
        public String AACompanyTypeCombo
        {
            get { return _aACompanyTypeCombo; }
            set
            {
                if (value != this._aACompanyTypeCombo)
                {
                    _aACompanyTypeCombo = value;
                }
            }
        }
        public String GLVoucherPmtMethodTypeCombo
        {
            get { return _gLVoucherPmtMethodTypeCombo; }
            set
            {
                if (value != this._gLVoucherPmtMethodTypeCombo)
                {
                    _gLVoucherPmtMethodTypeCombo = value;
                }
            }
        }
        public Nullable<DateTime> GLVoucherDueDate
        {
            get { return _gLVoucherDueDate; }
            set
            {
                if (value != this._gLVoucherDueDate)
                {
                    _gLVoucherDueDate = value;
                }
            }
        }
        public int FK_APPOID
        {
            get { return _fK_APPOID; }
            set
            {
                if (value != this._fK_APPOID)
                {
                    _fK_APPOID = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherPmtReqAmtTot
        {
            get { return _gLVoucherPmtReqAmtTot; }
            set
            {
                if (value != this._gLVoucherPmtReqAmtTot)
                {
                    _gLVoucherPmtReqAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherPmtReqFAmtTot
        {
            get { return _gLVoucherPmtReqFAmtTot; }
            set
            {
                if (value != this._gLVoucherPmtReqFAmtTot)
                {
                    _gLVoucherPmtReqFAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherPmtReqRAmtTot
        {
            get { return _gLVoucherPmtReqRAmtTot; }
            set
            {
                if (value != this._gLVoucherPmtReqRAmtTot)
                {
                    _gLVoucherPmtReqRAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherPmtReqRFAmtTot
        {
            get { return _gLVoucherPmtReqRFAmtTot; }
            set
            {
                if (value != this._gLVoucherPmtReqRFAmtTot)
                {
                    _gLVoucherPmtReqRFAmtTot = value;
                }
            }
        }
        public bool GLVoucherNeedPaymentCheck
        {
            get { return _gLVoucherNeedPaymentCheck; }
            set
            {
                if (value != this._gLVoucherNeedPaymentCheck)
                {
                    _gLVoucherNeedPaymentCheck = value;
                }
            }
        }
        public String AAThueRemark
        {
            get { return _aAThueRemark; }
            set
            {
                if (value != this._aAThueRemark)
                {
                    _aAThueRemark = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherAllocateFAmtTot
        {
            get { return _gLVoucherAllocateFAmtTot; }
            set
            {
                if (value != this._gLVoucherAllocateFAmtTot)
                {
                    _gLVoucherAllocateFAmtTot = value;
                }
            }
        }
        public String GLVoucherUNCNo
        {
            get { return _gLVoucherUNCNo; }
            set
            {
                if (value != this._gLVoucherUNCNo)
                {
                    _gLVoucherUNCNo = value;
                }
            }
        }
        public String AAOrgDocNo
        {
            get { return _aAOrgDocNo; }
            set
            {
                if (value != this._aAOrgDocNo)
                {
                    _aAOrgDocNo = value;
                }
            }
        }
        public String GLObjectType
        {
            get { return _gLObjectType; }
            set
            {
                if (value != this._gLObjectType)
                {
                    _gLObjectType = value;
                }
            }
        }
        public Nullable<DateTime> GLVoucherJrnDate
        {
            get { return _gLVoucherJrnDate; }
            set
            {
                if (value != this._gLVoucherJrnDate)
                {
                    _gLVoucherJrnDate = value;
                }
            }
        }
        public int FK_GLVoucherCancelID
        {
            get { return _fK_GLVoucherCancelID; }
            set
            {
                if (value != this._fK_GLVoucherCancelID)
                {
                    _fK_GLVoucherCancelID = value;
                }
            }
        }
        public String GLVoucherTransStatusCombo
        {
            get { return _gLVoucherTransStatusCombo; }
            set
            {
                if (value != this._gLVoucherTransStatusCombo)
                {
                    _gLVoucherTransStatusCombo = value;
                }
            }
        }
        public int FK_GLLCID
        {
            get { return _fK_GLLCID; }
            set
            {
                if (value != this._fK_GLLCID)
                {
                    _fK_GLLCID = value;
                }
            }
        }
        public String GLVoucherJrnNo
        {
            get { return _gLVoucherJrnNo; }
            set
            {
                if (value != this._gLVoucherJrnNo)
                {
                    _gLVoucherJrnNo = value;
                }
            }
        }
        public int FK_GECurrencyExObjID
        {
            get { return _fK_GECurrencyExObjID; }
            set
            {
                if (value != this._fK_GECurrencyExObjID)
                {
                    _fK_GECurrencyExObjID = value;
                }
            }
        }
        public String GLVoucherCreateTypeCombo
        {
            get { return _gLVoucherCreateTypeCombo; }
            set
            {
                if (value != this._gLVoucherCreateTypeCombo)
                {
                    _gLVoucherCreateTypeCombo = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherOBFAmtTot
        {
            get { return _gLVoucherOBFAmtTot; }
            set
            {
                if (value != this._gLVoucherOBFAmtTot)
                {
                    _gLVoucherOBFAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherEBFAmtTot
        {
            get { return _gLVoucherEBFAmtTot; }
            set
            {
                if (value != this._gLVoucherEBFAmtTot)
                {
                    _gLVoucherEBFAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherOBAmtTot
        {
            get { return _gLVoucherOBAmtTot; }
            set
            {
                if (value != this._gLVoucherOBAmtTot)
                {
                    _gLVoucherOBAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(19, 6)")]
        public decimal GLVoucherEBAmtTot
        {
            get { return _gLVoucherEBAmtTot; }
            set
            {
                if (value != this._gLVoucherEBAmtTot)
                {
                    _gLVoucherEBAmtTot = value;
                }
            }
        }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal GLVoucherDiffAmount
        {
            get { return _gLVoucherDiffAmount; }
            set
            {
                if (value != this._gLVoucherDiffAmount)
                {
                    _gLVoucherDiffAmount = value;
                }
            }
        }
        public String GLVoucherDiffTypeCombo
        {
            get { return _gLVoucherDiffTypeCombo; }
            set
            {
                if (value != this._gLVoucherDiffTypeCombo)
                {
                    _gLVoucherDiffTypeCombo = value;
                }
            }
        }
        public Nullable<DateTime> GLVoucherPaymentDeadline
        {
            get { return _gLVoucherPaymentDeadline; }
            set
            {
                if (value != this._gLVoucherPaymentDeadline)
                {
                    _gLVoucherPaymentDeadline = value;
                }
            }
        }
        public int FK_GLAdvanceReqProposalID
        {
            get { return _fK_GLAdvanceReqProposalID; }
            set
            {
                if (value != this._fK_GLAdvanceReqProposalID)
                {
                    _fK_GLAdvanceReqProposalID = value;
                }
            }
        }
        public String GLVoucherReferenceNo
        {
            get { return _gLVoucherReferenceNo; }
            set
            {
                if (value != this._gLVoucherReferenceNo)
                {
                    _gLVoucherReferenceNo = value;
                }
            }
        }
        public String GLExecutionStatusCombo
        {
            get { return _gLExecutionStatusCombo; }
            set
            {
                if (value != this._gLExecutionStatusCombo)
                {
                    _gLExecutionStatusCombo = value;
                }
            }
        }
        public int FK_GLVoucherFeePaymnetID
        {
            get { return _fK_GLVoucherFeePaymnetID; }
            set
            {
                if (value != this._fK_GLVoucherFeePaymnetID)
                {
                    _fK_GLVoucherFeePaymnetID = value;
                }
            }
        }
        public String GLObjectTypeCombo
        {
            get { return _gLObjectTypeCombo; }
            set
            {
                if (value != this._gLObjectTypeCombo)
                {
                    _gLObjectTypeCombo = value;
                }
            }
        }
        public int FK_GLObjectVoucherItemID
        {
            get { return _fK_GLObjectVoucherItemID; }
            set
            {
                if (value != this._fK_GLObjectVoucherItemID)
                {
                    _fK_GLObjectVoucherItemID = value;
                }
            }
        }

        #endregion
    }
    #endregion
}